In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 50)

In [7]:
data = pd.read_csv("bca/tabel 1")
data

,Unnamed: 0,ASET,Unnamed: 1
0,1.0,Kas,17.218.757
1,2.0,Penempatan pada Bank Indonesia,65.078.325
2,3.0,Penempatan pada bank lain,13.889.766
3,4.0,Tagihan spot dan derivatif/forward,150.626
4,5.0,Surat berharga yang dimiliki,3 89.164.527
5,6.0,Surat berharga yang dijual dengan janji dibeli...,338.965
6,7.0,Tagihan atas surat berharga yang dibeli dengan...,NaN
7,NaN,dijual kembali (reverse repo ),10.601.065
8,8.0,Tagihan akseptasi,10.657.621
9,9.0,Kredit dan pembiayaan yang diberikan,8 75.782.049
10,10.0,Pembiayaan syariah,-
11,11.0,Penyertaan Modal,10.350.797
12,12.0,Aset keuangan lainnya,12.396.928
13,13.0,Cadangan kerugian penurunan nilai aset keuanga...,(34.634.503)
14,NaN,a. Surat berharga yang dimiliki,(381.758)
15,NaN,b. Kredit yang diberikan dan pembiayaan syariah,(33.669.520)
16,NaN,c. Lainnya,(583.225)
17,14.0,Aset tidak berwujud,1.345.627
18,NaN,Akumulasi amortisasi aset tidak berwujud -/-,(939.480)
19,15.0,Aset tetap dan inventaris,37.172.978
20,NaN,Akumulasi penyusutan aset tetap dan inventaris...,(10.624.580)
21,16.0,Aset non produktif,2.014.744
22,NaN,a. Properti terbengkalai,45.063
23,NaN,b. Agunan yang diambil alih,1.782.603
24,NaN,c. Rekening tunda,11.328
25,NaN,d. Aset antarkantor,175.750
26,17.0,Aset lainnya,15.443.204
27,NaN,TOTAL ASET,1 .415.407.416

In [10]:
data['ASET'] = data['ASET'].str.strip()
data['ASET'] = data['ASET'].str.replace('a.', '').str.replace('b.', '').str.replace('c.', '').str.replace('d.', '') 
data['ASET'] = data['ASET'].str.replace('-/-', '').str.replace('\r', '').str.strip()
data = data.map(lambda x: x.replace('(', '').replace(')', '').replace('-', '0') if isinstance(x, str) else x)
data

,Unnamed: 0,ASET,Unnamed: 1
0,1.0,Kas,17.218.757
1,2.0,Penempatan pada Bank Indonesia,65.078.325
2,3.0,Penempatan pada bank lain,13.889.766
3,4.0,Tagihan spot dan derivatif/forward,150.626
4,5.0,Surat berharga yang dimiliki,3 89.164.527
5,6.0,Surat berharga yang dijual dengan janji dibeli...,338.965
6,7.0,Tagihan atas surat berharga yang dibeli dengan...,NaN
7,NaN,dijual kembali reverse repo,10.601.065
8,8.0,Tagihan akseptasi,10.657.621
9,9.0,Kredit dan pembiayaan yang diberikan,8 75.782.049
10,10.0,Pembiayaan syariah,0
11,11.0,Penyertaan Modal,10.350.797
12,12.0,Aset keuangan lainnya,12.396.928
13,13.0,Cadangan kerugian penurunan nilai aset keuangan,34.634.503
14,NaN,Surat berharga yang dimiliki,381.758
15,NaN,Kredit yang diberikan dan pembiayaan syariah,33.669.520
16,NaN,Lainnya,583.225
17,14.0,Aset tidak berwujud,1.345.627
18,NaN,Akumulasi amortisasi aset tidak berwujud,939.480
19,15.0,Aset tetap dan inventaris,37.172.978
20,NaN,Akumulasi penyusutan aset tetap dan inventaris,10.624.580
21,16.0,Aset non produktif,2.014.744
22,NaN,Properti terbengkalai,45.063
23,NaN,Agunan yang diambil alih,1.782.603
24,NaN,Rekening tunda,11.328
25,NaN,Aset antarkantor,175.750
26,17.0,Aset lainnya,15.443.204
27,NaN,TOTAL ASET,1 .415.407.416

In [9]:
# data.columns = ['Category', 'POS', 'Individual 30 June 2023', 'Individual 31 December 2022', 'Consolidated 30 June 2023', 'Consolidated 31 December 2022']
# data['POS'] = data['POS'].str.strip()

# keuangan = data[0:33].reset_index(drop=True)
# liabilitas = data[len(keuangan):].reset_index(drop=True)