In [1]:
import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

Saving penyakit_ginjal_kronik-1.csv to penyakit_ginjal_kronik-1.csv

In [15]:
data = pd.read_csv('penyakit_ginjal_kronik-1.csv')

data

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
0,0,48.0,80.0,1.020,1.0,0.0,NaN,Tidak Normal,121.0,36.0,...,44,7800,5.2,yes,yes,Tidak,baik,Tidak,Tidak,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,Tidak Normal,NaN,18.0,...,38,6000,NaN,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
2,2,62.0,80.0,1.010,2.0,3.0,Tidak Normal,Tidak Normal,423.0,53.0,...,31,7500,NaN,Tidak,yes,Tidak,buruk,Tidak,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,yes,Tidak,Tidak,buruk,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,Tidak Normal,Tidak Normal,106.0,26.0,...,35,7300,4.6,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd

In [12]:
data = data.dropna()

data

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,yes,Tidak,Tidak,buruk,yes,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,Normal,Normal,70.0,107.0,...,29,12100,3.7,yes,yes,Tidak,buruk,Tidak,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,Normal,Normal,380.0,60.0,...,32,4500,3.8,yes,yes,Tidak,buruk,yes,Tidak,ckd
14,14,68.0,80.0,1.010,3.0,2.0,Tidak Normal,Normal,157.0,90.0,...,16,11000,2.6,yes,yes,yes,buruk,yes,Tidak,ckd
20,20,61.0,80.0,1.015,2.0,0.0,Normal,Normal,173.0,148.0,...,24,9200,3.2,yes,yes,yes,buruk,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd

In [17]:
data[['hipertensi', 'diabetes']] = data[['hipertensi', 'diabetes']].replace('yes', 'ya')

data

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
0,0,48.0,80.0,1.020,1.0,0.0,NaN,Tidak Normal,121.0,36.0,...,44,7800,5.2,ya,ya,Tidak,baik,Tidak,Tidak,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,Tidak Normal,NaN,18.0,...,38,6000,NaN,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
2,2,62.0,80.0,1.010,2.0,3.0,Tidak Normal,Tidak Normal,423.0,53.0,...,31,7500,NaN,Tidak,ya,Tidak,buruk,Tidak,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,ya,Tidak,Tidak,buruk,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,Tidak Normal,Tidak Normal,106.0,26.0,...,35,7300,4.6,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd