In [1]:
from google.colab import files

uploaded = files.upload()

Saving dataset_final_project (1).csv to dataset_final_project (1).csv

In [7]:
import pandas as pd

data_backup = pd.read_csv('dataset_final_project (1).csv')
data = pd.read_csv('dataset_final_project (1).csv')

data

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,1/5/2019,13:08,Ewallet,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3/8/2019,10:29,Cash,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,3/3/2019,13:23,Credit card,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,1/27/2019,20:33,Ewallet,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,2/8/2019,10:37,Ewallet,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,1/29/2019,13:46,Ewallet,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,3/2/2019,17:16,Ewallet,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,2/9/2019,13:22,Cash,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,2/22/2019,15:33,Cash,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,2/18/2019,13:28,Cash,6.6

In [6]:
data.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Date', 'Time', 'Payment',
       'Rating'],
      dtype='object')

In [8]:
data['Branch'] = data['Branch'].replace(['A', 'B', 'C'], [1,2,3])
data['City'] = data['City'].replace(['Yangon', 'Naypyitaw', 'Mandalay'], [1,2,3])
data['Customer type'] = data['Customer type'].replace(['Normal', 'Member'], [1,2])
data['Product line'] = data['Product line'].replace(['Electronic accessories',
                                                     'Fashion accessories','Food and beverages',
                                                     'Health and beauty', 'Home and lifestyle',
                                                     'Sports and travel'], [1,2,3,4,5,6])
data['Payment'] = data['Payment'].replace(['Cash', 'Credit card', 'Ewallet'], [1,2,3])
data

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,Rating
0,750-67-8428,1,1,2,Female,4,74.69,7,1/5/2019,13:08,3,9.1
1,226-31-3081,3,2,1,Female,1,15.28,5,3/8/2019,10:29,1,9.6
2,631-41-3108,1,1,1,Male,5,46.33,7,3/3/2019,13:23,2,7.4
3,123-19-1176,1,1,2,Male,4,58.22,8,1/27/2019,20:33,3,8.4
4,373-73-7910,1,1,1,Male,6,86.31,7,2/8/2019,10:37,3,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,3,2,1,Male,4,40.35,1,1/29/2019,13:46,3,6.2
996,303-96-2227,2,3,1,Female,5,97.38,10,3/2/2019,17:16,3,4.4
997,727-02-1313,1,1,2,Male,3,31.84,1,2/9/2019,13:22,1,7.7
998,347-56-2442,1,1,1,Male,5,65.82,1,2/22/2019,15:33,1,4.1
999,849-09-3807,1,1,2,Female,2,88.34,7,2/18/2019,13:28,1,6.6

In [9]:
data['Total'] = data['Unit price'] * data['Quantity']
data['Tax'] = data['Total'] * 0.05
data['Final price'] = data['Total'] - data['Tax']
data

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,Rating,Total,Tax,Final price
0,750-67-8428,1,1,2,Female,4,74.69,7,1/5/2019,13:08,3,9.1,522.83,26.1415,496.6885
1,226-31-3081,3,2,1,Female,1,15.28,5,3/8/2019,10:29,1,9.6,76.40,3.8200,72.5800
2,631-41-3108,1,1,1,Male,5,46.33,7,3/3/2019,13:23,2,7.4,324.31,16.2155,308.0945
3,123-19-1176,1,1,2,Male,4,58.22,8,1/27/2019,20:33,3,8.4,465.76,23.2880,442.4720
4,373-73-7910,1,1,1,Male,6,86.31,7,2/8/2019,10:37,3,5.3,604.17,30.2085,573.9615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,3,2,1,Male,4,40.35,1,1/29/2019,13:46,3,6.2,40.35,2.0175,38.3325
996,303-96-2227,2,3,1,Female,5,97.38,10,3/2/2019,17:16,3,4.4,973.80,48.6900,925.1100
997,727-02-1313,1,1,2,Male,3,31.84,1,2/9/2019,13:22,1,7.7,31.84,1.5920,30.2480
998,347-56-2442,1,1,1,Male,5,65.82,1,2/22/2019,15:33,1,4.1,65.82,3.2910,62.5290
999,849-09-3807,1,1,2,Female,2,88.34,7,2/18/2019,13:28,1,6.6,618.38,30.9190,587.4610

In [10]:
data.dropna()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Date,Time,Payment,Rating,Total,Tax,Final price
0,750-67-8428,1,1,2,Female,4,74.69,7,1/5/2019,13:08,3,9.1,522.83,26.1415,496.6885
1,226-31-3081,3,2,1,Female,1,15.28,5,3/8/2019,10:29,1,9.6,76.40,3.8200,72.5800
2,631-41-3108,1,1,1,Male,5,46.33,7,3/3/2019,13:23,2,7.4,324.31,16.2155,308.0945
3,123-19-1176,1,1,2,Male,4,58.22,8,1/27/2019,20:33,3,8.4,465.76,23.2880,442.4720
4,373-73-7910,1,1,1,Male,6,86.31,7,2/8/2019,10:37,3,5.3,604.17,30.2085,573.9615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,3,2,1,Male,4,40.35,1,1/29/2019,13:46,3,6.2,40.35,2.0175,38.3325
996,303-96-2227,2,3,1,Female,5,97.38,10,3/2/2019,17:16,3,4.4,973.80,48.6900,925.1100
997,727-02-1313,1,1,2,Male,3,31.84,1,2/9/2019,13:22,1,7.7,31.84,1.5920,30.2480
998,347-56-2442,1,1,1,Male,5,65.82,1,2/22/2019,15:33,1,4.1,65.82,3.2910,62.5290
999,849-09-3807,1,1,2,Female,2,88.34,7,2/18/2019,13:28,1,6.6,618.38,30.9190,587.4610

In [16]:
import matplotlib.pyplot as plt
import plotly.express as px

jumlah = data.groupby('Product line')['Quantity'].sum()

plt.figure(figsize=[5,5])
px.bar(jumlah.reset_index(),x = 'Product line', y = 'Quantity')

In [21]:
normal = data[data['Customer type'] == 1]
member = data[data['Customer type'] == 2]

product1 = normal.groupby('Product line')['Customer type'].count()
product2 = member.groupby('Product line')['Customer type'].count()

px.bar(product1.reset_index(),x = 'Product line', y = 'Customer type', title = 'normal')

In [22]:
px.bar(product2.reset_index(),x = 'Product line', y = 'Customer type', title = 'member')

In [36]:
pay = data.groupby('Payment')['Invoice ID'].count()

plt.figure(figsize=[5,5])
px.bar(pay.reset_index(), x = 'Payment', y = 'Invoice ID', title = 'payment')

In [39]:
pie = data.groupby('Payment')['Product line'].count()

plt.figure(figsize=[5,5])
px.pie(pie.reset_index(), names = 'Payment', values = 'Product line')

In [27]:
price = data.groupby('Product line')['Final price'].sum()

px.bar(price.reset_index(), x = 'Product line', y = 'Final price', title = 'payment')