In [53]:
import pandas as pd

data = {
    'Kategori': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Nilai1': [10, 15, 20, 25, 30, 35],
    'Nilai2': [100, 150, 200, 250, 300, 350],
    'Nilai3': [1000, 1500, 2000, 2500, 3000, 3500]
}

df = pd.DataFrame(data)

df

  Kategori  Nilai1  Nilai2  Nilai3
0        A      10     100    1000
1        B      15     150    1500
2        A      20     200    2000
3        B      25     250    2500
4        A      30     300    3000
5        B      35     350    3500

In [54]:
# Mengelompokkan berdasarkan 1 kolom kategori

grouped = df.groupby('Kategori')

grouped.first()

          Nilai1  Nilai2  Nilai3
Kategori
A             10     100    1000
B             15     150    1500

In [58]:
# Mengelompokkan berdasarkan 1 kolom kategori dan 1 kolom data

grouped = df.groupby('Kategori')['Nilai1']

grouped.first()

Kategori
A    10
B    15
Name: Nilai1, dtype: int64

In [38]:
# Mengelompokkan berdasarkan 2 kolom kategori

double = df.groupby(['Nilai1', 'Nilai2'])

double.first()

              Kategori
Nilai1 Nilai2
10     100           A
15     150           B
20     200           A
25     250           B
30     300           A
35     350           B

In [59]:
# Mengelompokkan berdasarkan 2 kolom kategori dan 1 kolom data

double = df.groupby(['Nilai1', 'Nilai2'])['Kategori']

double.first()

Nilai1  Nilai2
10      100       A
15      150       B
20      200       A
25      250       B
30      300       A
35      350       B
Name: Kategori, dtype: object

In [50]:
# Menampilkan 1 kategori berdasarkan value

grouped.get_group('A')

  Kategori  Nilai1  Nilai2
0        A      10     100
2        A      20     200
4        A      30     300

In [47]:
# Menampilkan 2 kategori berdasarkan value

double.get_group((10, 100))

  Kategori  Nilai1  Nilai2
0        A      10     100

In [20]:
# Contoh Penggunaan groupby().mean()

mean_values = grouped.mean()

print(mean_values)

          Nilai1  Nilai2
Kategori
A           20.0   200.0
B           25.0   250.0

In [21]:
# Contoh Penggunaan groupby().sum()

sum_values = grouped.sum()

print(sum_values)

          Nilai1  Nilai2
Kategori
A             60     600
B             75     750

In [22]:
# Contoh Penggunaan groupby().max() dan groupby().min()

max_values = grouped.max()
min_values = grouped.min()

print(max_values)
print(min_values)

          Nilai1  Nilai2
Kategori
A             30     300
B             35     350
          Nilai1  Nilai2
Kategori
A             10     100
B             15     150

In [23]:
# Contoh Penggunaan Iterasi melalui Kelompok

for name, group in grouped:
    print(f'\nKelompok {name}:')
    print(group)

Kelompok A:
  Kategori  Nilai1  Nilai2
0        A      10     100
2        A      20     200
4        A      30     300

Kelompok B:
  Kategori  Nilai1  Nilai2
1        B      15     150
3        B      25     250
5        B      35     350

In [24]:
# Contoh Penggunaan groupby().transform()

df['Rata-rata_Nilai1'] = grouped['Nilai1'].transform('mean')
df['Total_Nilai2'] = grouped['Nilai2'].transform('sum')

print(df)

  Kategori  Nilai1  Nilai2  Rata-rata_Nilai1  Total_Nilai2
0        A      10     100              20.0           600
1        B      15     150              25.0           750
2        A      20     200              20.0           600
3        B      25     250              25.0           750
4        A      30     300              20.0           600
5        B      35     350              25.0           750