In [1]:
import pandas as pd
import numpy as np

data = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

data

   A  B
0  1  4
1  2  5
2  3  6

In [7]:
# map

def custom_function(row): # 1
  return row + 2

mapp = data['A'].map(custom_function) # fungsi map hanya bisa pada data series
applymapp = data[['A']].applymap(custom_function)

contoh = list(map(lambda x: x + 2, data['A']))
a,b,c = map(lambda x: x + 2, data['A'])

# print(contoh)
# print(a)
print(applymapp)

   A
0  3
1  4
2  5

In [11]:
# apply

def custom_function(row):
  return row + 2

applyy = data[['A']].apply(custom_function) # fungsi apply bisa pada data dataframe atau series

applyy

   A
0  3
1  4
2  5

In [ ]:
# transform

def custom_function(row):
  return row + 2

transformm = data[['A']].transform(custom_function) # fungsi transform mirip seperti apply

transformm

   A
0  3
1  4
2  5

In [16]:
# perbedaan apply dan transform 1

# apply dapat melakukan edit data menjadi panjang data yang berbeda , transform tidak bisa

sum_apply = data.apply(lambda x: x.sum())

sum_transform = data.transform(lambda x: x + 1)

sum_apply

A     6
B    15
dtype: int64

In [17]:
df = pd.DataFrame({
    'key': ['a','b','c'] * 3,
    'A': [4,5,6] * 3,
    'B': [1,2,3] * 3,
})

df

  key  A  B
0   a  4  1
1   b  5  2
2   c  6  3
3   a  4  1
4   b  5  2
5   c  6  3
6   a  4  1
7   b  5  2
8   c  6  3

In [19]:
group_apply = df.groupby('key')['A'].sum()

group_apply

key
a    12
b    15
c    18
Name: A, dtype: int64

In [23]:
def group_sum(x):
    return x.sum()

group_apply = df.groupby('key')['A'].apply(group_sum)

group_transform = df.groupby('key')['A'].transform(group_sum)

group_apply

key
a    12
b    15
c    18
Name: A, dtype: int64

In [26]:
# filter

def cek(kondisi): # 2
  return kondisi > 1 # true

adults = list(filter(cek, data['A'])) # filter hanya berproses pada true dan false

print(adults)

[2, 3]

In [38]:
# merge dan concat

df1 = pd.DataFrame({'Nama': ['Alice', 'Bob', 'Charlie']})

df2 = pd.DataFrame({'Nama': ['Alice', 'Agung', 'Charlie'], 'Umur': [25, 30, 35]})

result_merge = pd.merge(df1, df2, on='Nama')

result_merge

      Nama  Umur
0    Alice    25
1  Charlie    35

In [35]:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Nama': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 3], 'Umur': [25, 30, 35]})

result_concat1 = pd.concat([df1, df2])

result_concat2 = pd.concat([df1, df2]).set_index('ID')

result_concat3 = pd.concat([df1, df2], ignore_index = True)

display(result_concat1, result_concat2, result_concat3)

   ID     Nama  Umur
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie   NaN
0   1      NaN  25.0
1   2      NaN  30.0
2   3      NaN  35.0

       Nama  Umur
ID
1     Alice   NaN
2       Bob   NaN
3   Charlie   NaN
1       NaN  25.0
2       NaN  30.0
3       NaN  35.0

   ID     Nama  Umur
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie   NaN
3   1      NaN  25.0
4   2      NaN  30.0
5   3      NaN  35.0

stack mengubah kolom menjadi indeks, sedangkan unstack mengubah indeks menjadi kolom

In [41]:
import pandas as pd

data = {
    'Tinggi': [175, 180],
    'Berat': [70, 75]
}

df = pd.DataFrame(data, index = ['agung', 'koko'])

df

       Tinggi  Berat
agung     175     70
koko      180     75

In [42]:
stacked_df = df.stack()

stacked_df

agung  Tinggi    175
       Berat      70
koko   Tinggi    180
       Berat      75
dtype: int64

In [49]:
stacked_df.loc['agung']

Tinggi    175
Berat      70
dtype: int64

In [50]:
unstacked_df = stacked_df.unstack()

unstacked_df

       Tinggi  Berat
agung     175     70
koko      180     75

In [51]:
unstacked_df = df.unstack()

unstacked_df

Tinggi  agung    175
        koko     180
Berat   agung     70
        koko      75
dtype: int64

In [53]:
unstacked_df.loc[:, 'agung']

Tinggi    175
Berat      70
dtype: int64

In [69]:
from folium.plugins import HeatMap
import folium

data = {
    'Lokasi': ['Denpasar', 'Ubud', 'Kuta', 'Seminyak', 'Canggu'],
    'Latitude': [-8.671483, -8.509692, -8.721267, -8.691243, -8.654356],
    'Longitude': [115.213236, 115.262370, 115.169668, 115.168586, 115.133534],
    'Banyak': [1000, 900, 800, 700, 600]
}

df = pd.DataFrame(data)

df

     Lokasi  Latitude   Longitude  Banyak
0  Denpasar -8.671483  115.213236    1000
1      Ubud -8.509692  115.262370     900
2      Kuta -8.721267  115.169668     800
3  Seminyak -8.691243  115.168586     700
4    Canggu -8.654356  115.133534     600

In [72]:
group = df.groupby(['Latitude','Longitude'])['Banyak'].sum().reset_index()

group

   Latitude   Longitude  Banyak
0 -8.721267  115.169668     800
1 -8.691243  115.168586     700
2 -8.671483  115.213236    1000
3 -8.654356  115.133534     600
4 -8.509692  115.262370     900

In [61]:
basemap = folium.Map()

HeatMap(group, radius = 30).add_to(basemap)

basemap