In [1]:
from google.colab import files

uploaded = files.upload()

Saving laporan-pendapatan-blud-bulan-oktober-2021.csv to laporan-pendapatan-blud-bulan-oktober-2021.csv

In [7]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")
pd.set_option('display.max_rows', None)

data = pd.read_csv("laporan-pendapatan-blud-bulan-oktober-2021.csv")

data_backup = pd.read_csv("laporan-pendapatan-blud-bulan-oktober-2021.csv")

data

,PEMERINTAH PROVINSI JAWA TENGAH,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,RUMAH SAKIT JIWA DAERAH SURAKARTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LAPORAN PENDAPATAN BLUD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BULAN : OKTOBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TAHUN ANGGARAN 2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NO,URAIAN,NaN,JUMLAH ANGGARAN,REALISASI,REALISASI,REALISASI,LEBIH
7,NaN,NaN,NaN,NaN,S / D BULAN,BULAN,S / D BULAN,(KURANG)
8,NaN,NaN,NaN,NaN,LALU,INI,INI,NaN
9,1,2,NaN,3,4,5,6 = 4 + 5,7 = 3 - 6
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,4,PENDAPATAN DAERAH,NaN,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,4.1. Pendapatan Asli Daerah (PAD),NaN,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,4.1.4,LAIN-LAIN PAD YANG SAH,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
16,NaN,4.1.4.16,Pendapatan BLUD,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
17,NaN,4.1.4.16.1,Pendapatan BLUD,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
18,NaN,4.1.4.16.1.1,Pendapatan BLUD,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,4.1.4.16.1.1.01,Pendapatan Diklat,"1,155,000,000","762,446,000","57,960,100","820,406,100","334,593,900"
21,NaN,4.1.4.16.1.1.01.01,Diklat,"1,150,000,000","758,807,500","57,350,000","816,157,500","333,842,500"
22,NaN,4.1.4.16.1.1.01.02,Jasa Ketatausahaan,"5,000,000","3,638,500","610,100","4,248,600","751,400"
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,4.1.4.16.1.1.02,Pendapatan Lain-lain,"560,500,000","545,970,366","61,564,001","607,534,367","-47,034,367"
25,NaN,4.1.4.16.1.1.02.01,Sewa Ambulance,"75,000,000","53,255,500","12,670,000","65,925,500","9,074,500"
26,NaN,4.1.4.16.1.1.02.02,Sewa GOR,"5,000,000","4,667,600",-,"4,667,600","332,400"
27,NaN,4.1.4.16.1.1.02.03,Sewa Kantin,"52,000,000","41,466,800","7,866,720","49,333,520","2,666,480"
28,NaN,4.1.4.16.1.1.02.04,Sewa Ruang,"1,000,000","1,000,000",-,"1,000,000",-
29,NaN,4.1.4.16.1.1.02.05,Sewa Lahan Parkir,"70,000,000","58,140,000","6,000,000","64,140,000","5,860,000"
30,NaN,4.1.4.16.1.1.02.06,Sewa ATM,"35,000,000","35,000,000",-,"35,000,000",-
31,NaN,4.1.4.16.1.1.02.07,Sewa Lahan RS,"15,000,000","14,107,040","1,038,560","15,145,600","-145,600"
32,NaN,4.1.4.16.1.1.02.08,Laundry,"7,500,000","6,362,000","470,000","6,832,000","668,000"
33,NaN,4.1.4.16.1.1.02.09,Pendapatan Lainnya,"300,000,000","331,971,426","33,518,721","365,490,147","-65,490,147"
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,4.1.4.16.1.1.03,Pendapatan Pelayanan Kesehatan,"39,387,800,000","35,701,189,088","2,219,153,600","37,920,342,688","1,467,457,312"
36,NaN,4.1.4.16.1.1.03.01,Instalasi Rawat Jalan,"1,060,000,000","802,626,300","96,210,000","898,836,300","161,163,700"
37,NaN,4.1.4.16.1.1.03.02,Instalasi Gawat Darurat (termasuk ICU/HCU/PICU...,"165,000,000","122,606,000","10,197,500","132,803,500","32,196,500"
38,NaN,4.1.4.16.1.1.03.03,Instalasi Rawat Inap,"500,000,000","392,525,256","38,619,500","431,144,756","68,855,244"
39,NaN,4.1.4.16.1.1.03.04,Instalasi NAPZA & Rehab NAPZA,"500,000","455,000","120,000","575,000","-75,000"
40,NaN,4.1.4.16.1.1.03.05,Instalasi Psikogeriatri,"300,000","280,000",-,"280,000","20,000"
41,NaN,4.1.4.16.1.1.03.06,Instalasi Kesehatan Jiwa Anak dan Remaja,"28,000,000","22,525,000","4,900,000","27,425,000","575,000"
42,NaN,4.1.4.16.1.1.03.07,Instalasi Fisioterapi,"12,000,000","9,031,200","899,000","9,930,200","2,069,800"
43,NaN,4.1.4.16.1.1.03.08,Instalasi Laboratorium,"450,000,000","330,052,300","41,012,400","371,064,700","78,935,300"
44,NaN,4.1.4.16.1.1.03.09,Instalasi Radiologi,"40,000,000","32,899,000","1,858,000","34,757,000","5,243,000"
45,NaN,4.1.4.16.1.1.03.10,Instalasi Elektromedik,"80,000,000","53,437,500","12,450,000","65,887,500","14,112,500"
46,NaN,4.1.4.16.1.1.03.11,Instalasi Rehabilitasi Mental,"15,000,000","11,763,500","417,500","12,181,000","2,819,000"
47,NaN,4.1.4.16.1.1.03.12,Instalasi Gigi dan Mulut,"12,000,000","11,492,500","980,000","12,472,500","-472,500"
48,NaN,4.1.4.16.1.1.03.13,Instalasi Farmasi,"1,100,000,000","877,163,660","82,549,251","959,712,911","140,287,089"
49,NaN,4.1.4.16.1.1.03.14,Instalasi Psikologi,"120,000,000","92,327,500","25,185,000","117,512,500","2,487,500"
50,NaN,4.1.4.16.1.1.03.15,Instalasi Gizi,"10,000,000","7,494,500","610,000","8,104,500","1,895,500"
51,NaN,4.1.4.16.1.1.03.16,Asuhan Keperawatan,"120,000,000","91,154,000","6,200,000","97,354,000","22,646,000"
52,NaN,4.1.4.16.1.1.03.17,Pelayanan Medikolegal,"150,000,000","138,472,500","43,475,000","181,947,500","-31,947,500"
53,NaN,4.1.4.16.1.1.03.18,BPJS Kesehatan,"20,550,000,000","15,112,937,107","1,824,698,149","16,937,635,256","3,612,364,744"
54,NaN,4.1.4.16.1.1.03.19,Jamkesda,"225,000,000","210,442,265","28,772,300","239,214,565","-14,214,565"
55,NaN,4.1.4.16.1.1.03.20,Klaim Covid-19,"14,750,000,000","17,381,504,000",-,"17,381,504,000","-2,631,504,000"
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,TOTAL PENDAPATAN BLUD,NaN,NaN,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,"Surakarta, 31 Oktober 2021",NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,Plt. Direktur Rumah Sakit Jiwa Daerah Surakarta,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,Provinsi Jawa Tengah,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,Wakil Direktur Pelayanan Medis,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,NaN,NaN,NaN,NaN,"dr. Setyowati Raharjo, Sp.KJ, M.Kes",NaN,NaN,NaN
68,NaN,NaN,NaN,NaN,Pembina Tingkat I,NaN,NaN,NaN
69,NaN,NaN,NaN,NaN,NIP. 19740625 200312 2 002,NaN,NaN,NaN

In [14]:
data.drop(index = data.index[58:])

,PEMERINTAH PROVINSI JAWA TENGAH,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,RUMAH SAKIT JIWA DAERAH SURAKARTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LAPORAN PENDAPATAN BLUD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BULAN : OKTOBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TAHUN ANGGARAN 2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NO,URAIAN,NaN,JUMLAH ANGGARAN,REALISASI,REALISASI,REALISASI,LEBIH
7,NaN,NaN,NaN,NaN,S / D BULAN,BULAN,S / D BULAN,(KURANG)
8,NaN,NaN,NaN,NaN,LALU,INI,INI,NaN
9,1,2,NaN,3,4,5,6 = 4 + 5,7 = 3 - 6
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,4,PENDAPATAN DAERAH,NaN,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,4.1. Pendapatan Asli Daerah (PAD),NaN,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,4.1.4,LAIN-LAIN PAD YANG SAH,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
16,NaN,4.1.4.16,Pendapatan BLUD,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
17,NaN,4.1.4.16.1,Pendapatan BLUD,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
18,NaN,4.1.4.16.1.1,Pendapatan BLUD,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,4.1.4.16.1.1.01,Pendapatan Diklat,"1,155,000,000","762,446,000","57,960,100","820,406,100","334,593,900"
21,NaN,4.1.4.16.1.1.01.01,Diklat,"1,150,000,000","758,807,500","57,350,000","816,157,500","333,842,500"
22,NaN,4.1.4.16.1.1.01.02,Jasa Ketatausahaan,"5,000,000","3,638,500","610,100","4,248,600","751,400"
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,4.1.4.16.1.1.02,Pendapatan Lain-lain,"560,500,000","545,970,366","61,564,001","607,534,367","-47,034,367"
25,NaN,4.1.4.16.1.1.02.01,Sewa Ambulance,"75,000,000","53,255,500","12,670,000","65,925,500","9,074,500"
26,NaN,4.1.4.16.1.1.02.02,Sewa GOR,"5,000,000","4,667,600",-,"4,667,600","332,400"
27,NaN,4.1.4.16.1.1.02.03,Sewa Kantin,"52,000,000","41,466,800","7,866,720","49,333,520","2,666,480"
28,NaN,4.1.4.16.1.1.02.04,Sewa Ruang,"1,000,000","1,000,000",-,"1,000,000",-
29,NaN,4.1.4.16.1.1.02.05,Sewa Lahan Parkir,"70,000,000","58,140,000","6,000,000","64,140,000","5,860,000"
30,NaN,4.1.4.16.1.1.02.06,Sewa ATM,"35,000,000","35,000,000",-,"35,000,000",-
31,NaN,4.1.4.16.1.1.02.07,Sewa Lahan RS,"15,000,000","14,107,040","1,038,560","15,145,600","-145,600"
32,NaN,4.1.4.16.1.1.02.08,Laundry,"7,500,000","6,362,000","470,000","6,832,000","668,000"
33,NaN,4.1.4.16.1.1.02.09,Pendapatan Lainnya,"300,000,000","331,971,426","33,518,721","365,490,147","-65,490,147"
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,4.1.4.16.1.1.03,Pendapatan Pelayanan Kesehatan,"39,387,800,000","35,701,189,088","2,219,153,600","37,920,342,688","1,467,457,312"
36,NaN,4.1.4.16.1.1.03.01,Instalasi Rawat Jalan,"1,060,000,000","802,626,300","96,210,000","898,836,300","161,163,700"
37,NaN,4.1.4.16.1.1.03.02,Instalasi Gawat Darurat (termasuk ICU/HCU/PICU...,"165,000,000","122,606,000","10,197,500","132,803,500","32,196,500"
38,NaN,4.1.4.16.1.1.03.03,Instalasi Rawat Inap,"500,000,000","392,525,256","38,619,500","431,144,756","68,855,244"
39,NaN,4.1.4.16.1.1.03.04,Instalasi NAPZA & Rehab NAPZA,"500,000","455,000","120,000","575,000","-75,000"
40,NaN,4.1.4.16.1.1.03.05,Instalasi Psikogeriatri,"300,000","280,000",-,"280,000","20,000"
41,NaN,4.1.4.16.1.1.03.06,Instalasi Kesehatan Jiwa Anak dan Remaja,"28,000,000","22,525,000","4,900,000","27,425,000","575,000"
42,NaN,4.1.4.16.1.1.03.07,Instalasi Fisioterapi,"12,000,000","9,031,200","899,000","9,930,200","2,069,800"
43,NaN,4.1.4.16.1.1.03.08,Instalasi Laboratorium,"450,000,000","330,052,300","41,012,400","371,064,700","78,935,300"
44,NaN,4.1.4.16.1.1.03.09,Instalasi Radiologi,"40,000,000","32,899,000","1,858,000","34,757,000","5,243,000"
45,NaN,4.1.4.16.1.1.03.10,Instalasi Elektromedik,"80,000,000","53,437,500","12,450,000","65,887,500","14,112,500"
46,NaN,4.1.4.16.1.1.03.11,Instalasi Rehabilitasi Mental,"15,000,000","11,763,500","417,500","12,181,000","2,819,000"
47,NaN,4.1.4.16.1.1.03.12,Instalasi Gigi dan Mulut,"12,000,000","11,492,500","980,000","12,472,500","-472,500"
48,NaN,4.1.4.16.1.1.03.13,Instalasi Farmasi,"1,100,000,000","877,163,660","82,549,251","959,712,911","140,287,089"
49,NaN,4.1.4.16.1.1.03.14,Instalasi Psikologi,"120,000,000","92,327,500","25,185,000","117,512,500","2,487,500"
50,NaN,4.1.4.16.1.1.03.15,Instalasi Gizi,"10,000,000","7,494,500","610,000","8,104,500","1,895,500"
51,NaN,4.1.4.16.1.1.03.16,Asuhan Keperawatan,"120,000,000","91,154,000","6,200,000","97,354,000","22,646,000"
52,NaN,4.1.4.16.1.1.03.17,Pelayanan Medikolegal,"150,000,000","138,472,500","43,475,000","181,947,500","-31,947,500"
53,NaN,4.1.4.16.1.1.03.18,BPJS Kesehatan,"20,550,000,000","15,112,937,107","1,824,698,149","16,937,635,256","3,612,364,744"
54,NaN,4.1.4.16.1.1.03.19,Jamkesda,"225,000,000","210,442,265","28,772,300","239,214,565","-14,214,565"
55,NaN,4.1.4.16.1.1.03.20,Klaim Covid-19,"14,750,000,000","17,381,504,000",-,"17,381,504,000","-2,631,504,000"
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,TOTAL PENDAPATAN BLUD,NaN,NaN,"41,103,300,000","37,009,605,454","2,338,677,701","39,348,283,155","1,755,016,845"