In [ ]:
import pandas as pd

country= pd.Series([
    'France',
    'United Kingdom',
    'United Kingdom',
    'Italy',
    'Germany',
    'Germany',
    'Germany',
], index=[
    'Country 1',
    'Country 2',
    'Country 3',
    'Country 4',
    'Country 5',
    'Country 6',
    'Country 7'
])

country

Country 1            France
Country 2    United Kingdom
Country 3    United Kingdom
Country 4             Italy
Country 5           Germany
Country 6           Germany
Country 7           Germany
dtype: object

In [ ]:
country.duplicated(keep='first')

Country 1    False
Country 2    False
Country 3     True
Country 4    False
Country 5    False
Country 6     True
Country 7     True
dtype: bool

In [ ]:
country.duplicated(keep="last")

Country 1    False
Country 2     True
Country 3    False
Country 4    False
Country 5     True
Country 6     True
Country 7    False
dtype: bool

In [ ]:
country.duplicated(keep=False)

Country 1    False
Country 2     True
Country 3     True
Country 4    False
Country 5     True
Country 6     True
Country 7     True
dtype: bool

In [ ]:
country

Country 1            France
Country 2    United Kingdom
Country 3    United Kingdom
Country 4             Italy
Country 5           Germany
Country 6           Germany
Country 7           Germany
dtype: object

In [ ]:
country.drop_duplicates(keep = 'first')

Country 1            France
Country 2    United Kingdom
Country 4             Italy
Country 5           Germany
dtype: object

In [ ]:
country.drop_duplicates(keep = 'last')

Country 1            France
Country 3    United Kingdom
Country 4             Italy
Country 7           Germany
dtype: object

In [ ]:
country.drop_duplicates(keep = False)

Country 1    France
Country 4     Italy
dtype: object

In [ ]:
students = pd.DataFrame({
    'Name': [
        'Kobe Bryant',
        'LeBron James',
        'Kobe Bryant',
        'Carmelo Anthony',
        'Kobe Bryant',
    ],
    'Course': [
        'Python',
        'Unity',
        'Python',
        'Web Design',
        'Web Programming'
    ]
})

students

              Name           Course
0      Kobe Bryant           Python
1     LeBron James            Unity
2      Kobe Bryant           Python
3  Carmelo Anthony       Web Design
4      Kobe Bryant  Web Programming

In [ ]:
students.duplicated(keep = 'first')

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [ ]:
students.duplicated(subset = ['Name'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [1]:
# assignment

from google.colab import files

uploaded = files.upload()

Saving netflix_titles-1 (1).csv to netflix_titles-1 (1).csv

In [9]:
import pandas as pd

data = pd.read_csv('netflix_titles-1 (1).csv')

data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s24,Movie,Go! Go! Cory Carson: Chrissy Takes the Wheel,"Alex Woo, Stanley Moore","Maisie Benson, Paul Killam, Kerry Gudjohnsen, ...",NaN,"September 21, 2021",2021,TV-Y,61 min,Children & Family Movies,From arcade games to sled days and hiccup cure...
...,...,...,...,...,...,...,...,...,...,...,...,...
103,s20,TV Show,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN,"September 22, 2021",2021,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","In the 1960s, a Holocaust survivor joins a gro..."
104,s96,TV Show,The Circle,NaN,Michelle Buteau,"United States, United Kingdom","September 8, 2021",2021,TV-MA,3 Seasons,Reality TV,Status and strategy collide in this social exp...
105,s97,Movie,If I Leave Here Tomorrow: A Film About Lynyrd ...,Stephen Kijak,"Ronnie Van Zandt, Gary Rossington, Allen Colli...",United States,"September 7, 2021",2018,TV-MA,97 min,"Documentaries, Music & Musicals","Using interviews and archival footage, this do..."
106,s98,TV Show,Kid Cosmic,NaN,"Jack Fisher, Tom Kenny, Amanda C. Miller, Kim ...",United States,"September 7, 2021",2021,TV-Y7,2 Seasons,"Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",A boy's superhero dreams come true when he fin...
107,s99,TV Show,Octonauts: Above & Beyond,NaN,"Antonio Aakeel, Chipo Chung, Simon Foster, Ter...",United Kingdom,"September 7, 2021",2021,TV-Y,1 Season,"British TV Shows, Kids' TV",The Octonauts expand their exploration beyond ...

In [4]:
data.duplicated().sum()

9

In [10]:
# id = data['show_id']

# data.index = [id]

# data = data.drop("show_id", axis = 1)

data.set_index('show_id')

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s24,Movie,Go! Go! Cory Carson: Chrissy Takes the Wheel,"Alex Woo, Stanley Moore","Maisie Benson, Paul Killam, Kerry Gudjohnsen, ...",NaN,"September 21, 2021",2021,TV-Y,61 min,Children & Family Movies,From arcade games to sled days and hiccup cure...
...,...,...,...,...,...,...,...,...,...,...,...
s20,TV Show,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN,"September 22, 2021",2021,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","In the 1960s, a Holocaust survivor joins a gro..."
s96,TV Show,The Circle,NaN,Michelle Buteau,"United States, United Kingdom","September 8, 2021",2021,TV-MA,3 Seasons,Reality TV,Status and strategy collide in this social exp...
s97,Movie,If I Leave Here Tomorrow: A Film About Lynyrd ...,Stephen Kijak,"Ronnie Van Zandt, Gary Rossington, Allen Colli...",United States,"September 7, 2021",2018,TV-MA,97 min,"Documentaries, Music & Musicals","Using interviews and archival footage, this do..."
s98,TV Show,Kid Cosmic,NaN,"Jack Fisher, Tom Kenny, Amanda C. Miller, Kim ...",United States,"September 7, 2021",2021,TV-Y7,2 Seasons,"Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",A boy's superhero dreams come true when he fin...
s99,TV Show,Octonauts: Above & Beyond,NaN,"Antonio Aakeel, Chipo Chung, Simon Foster, Ter...",United Kingdom,"September 7, 2021",2021,TV-Y,1 Season,"British TV Shows, Kids' TV",The Octonauts expand their exploration beyond ...

In [20]:
data.shape

(108, 12)

In [19]:
data_simpan = data[data.duplicated(keep=False)]

data_simpan.shape

(15, 12)

In [18]:
data[data.duplicated()].shape

(9, 12)

In [21]:
data.shape

(108, 12)

In [22]:
data_baru = data.drop_duplicates()

data_baru.shape

(99, 12)

In [ ]:
data_baru.duplicated().sum()

0

In [35]:
from google.colab import files

uploaded = files.upload()

Saving user_age (1).csv to user_age (1).csv

In [26]:
from google.colab import files

uploaded = files.upload()

Saving user_age_2017.csv to user_age_2017.csv

In [25]:
from google.colab import files

uploaded = files.upload()

Saving user_age_2018.csv to user_age_2018.csv

In [27]:
data_2017 = pd.read_csv('user_age_2017.csv')
data_2018 = pd.read_csv('user_age_2018.csv')

data_2017

   userid      date
0       7  1/1/2017
1       8  1/2/2017
2       9  1/3/2017

In [28]:
data_2018

   userid      date
0      11  1/1/2018
1      12  1/2/2018
2      13  1/3/2018

In [34]:
data_baru = pd.concat([data_2017, data_2018], ignore_index = True)

data_baru.sort_values(by = ['userid'])

   userid      date
0       7  1/1/2017
1       8  1/2/2017
2       9  1/3/2017
3      11  1/1/2018
4      12  1/2/2018
5      13  1/3/2018

In [43]:
import pandas as pd

data = pd.read_csv('user_age (1).csv')

data

   userid      date
0       1  1/1/2020
1       2  1/2/2019
2       3  1/3/2019
3       4  1/1/2016
4       5  1/2/2016
5       6  1/3/2016
6       7  1/1/2014
7       8  1/2/2014
8       9  1/3/2014

In [52]:
data['date'] = pd.to_datetime(data['date'])

data

   userid       date
0       1 2020-01-01
1       2 2019-02-01
2       3 2019-03-01
3       4 2016-01-01
4       5 2016-02-01
5       6 2016-03-01
6       7 2014-01-01
7       8 2014-02-01
8       9 2014-03-01

In [46]:
data['date'] = data['date'].dt.strftime('%d-%m-%Y')

data

   userid        date
0       1  01-01-2020
1       2  02-01-2019
2       3  03-01-2019
3       4  01-01-2016
4       5  02-01-2016
5       6  03-01-2016
6       7  01-01-2014
7       8  02-01-2014
8       9  03-01-2014

In [56]:
from datetime import datetime

tanggal_sekarang = datetime.now()

data['age'] = (tanggal_sekarang - data['date']).dt.days

data

   userid       date   age
0       1 2020-01-01  1345
1       2 2019-02-01  1679
2       3 2019-03-01  1651
3       4 2016-01-01  2806
4       5 2016-02-01  2775
5       6 2016-03-01  2746
6       7 2014-01-01  3536
7       8 2014-02-01  3505
8       9 2014-03-01  3477

In [ ]:
bins = [0, 1400, 2000, 3000, 4000]

labels = ['< 1400 day', '1400 to 2000 day', '2000 to 3000 day', '4000 > day']

data['age_bin'] = pd.cut(data['age'], bins = bins, labels = labels)

data

   userid       date   age           age_bin
0       1 2020-01-01  1339        < 1400 day
1       2 2019-01-02  1703  1400 to 2000 day
2       3 2019-01-03  1702  1400 to 2000 day
3       4 2016-01-01  2800  2000 to 3000 day
4       5 2016-01-02  2799  2000 to 3000 day
5       6 2016-01-03  2798  2000 to 3000 day
6       7 2014-01-01  3530        4000 > day
7       8 2014-01-02  3529        4000 > day
8       9 2014-01-03  3528        4000 > day