In [ ]:
from google.colab import files

uploaded = files.upload()

Saving bali_tourist.csv to bali_tourist.csv

In [ ]:
import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['bali_tourist.csv']))
print(df)

     year                 area               country  January  February  \
0    2019        ASIA PACIFIC             AUSTRALIAN    95536     67474
1    2019        ASIA PACIFIC                 BHUTAN       60        30
2    2019        ASIA PACIFIC             BANGLADESH     2262      2094
3    2019        ASIA PACIFIC                   FIJI       91        73
4    2019        ASIA PACIFIC               HONGKONG     1313      1367
..    ...                  ...                   ...      ...       ...
357  2018          MIDDLE EAST                TURKEY      899       615
358  2018          MIDDLE EAST  UNITED ARAB EMIRATES      170       132
359  2018          MIDDLE EAST                 YAMAN       98        49
360  2018          MIDDLE EAST                JORDAN      225       153
361  2018  OTHER NATIONALITIES   OTHER NATIONALITIES     6952      1704

     March    April    May    June    July  August  September  October  \
0    83002  90265.0  98625  110815  123293  118556     124416   119382
1       47     38.0     31      31      46      67         43       32
2     2489   2264.0   1938    4265    2656    2307       2035     2371
3       72     77.0     42      62    2656      80         68       78
4      764      6.0      1       5       2       1          0       11
..     ...      ...    ...     ...     ...     ...        ...      ...
357    750    960.0    712     909    1306    1630        979      707
358    266    264.0    111     293     375     306        164      151
359     76     55.0     23      62      40      52         67       37
360    236    352.0    150     260     389     448        283      255
361   1771   2484.0   2167    3711    2054    1269       1762     2604

     November  December
0      105312    110711
1          56        60
2        2164      2671
3          89       189
4           0        45
..        ...       ...
357       514       521
358       147       201
359        60        85
360       218       254
361      3298       673

[362 rows x 15 columns]

In [1]:
from google.colab import files

uploaded = files.upload()

Saving package_tourism (1).csv to package_tourism (1).csv

In [9]:
import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['package_tourism (1).csv']))
df

,Package,City,Place_Tourism1,Place_Tourism2,Place_Tourism3,Place_Tourism4,Place_Tourism5
0,1,Jakarta,Pasar Tanah Abang,Taman Ayodya,Museum Tekstil,NaN,NaN
1,2,Jakarta,Pasar Tanah Abang,Pasar Taman Puring,Pasar Petak Sembilan,NaN,NaN
2,3,Jakarta,Perpustakaan Nasional,Monas,Masjid Istiqlal,NaN,NaN
3,4,Jakarta,Pulau Tidung,Pulau Bidadari,Pulau Pari,Pulau Pramuka,Pulau Pelangi
4,5,Jakarta,Museum Satria Mandala,Museum Wayang,Museum Bahari Jakarta,Museum Macan (Modern and Contemporary Art in N...,NaN
...,...,...,...,...,...,...,...
95,96,Surabaya,Ekowisata Mangrove Wonorejo,Taman Harmoni Keputih,Taman Kunang-Kunang,Taman Ekspresi Dan Perpustakaan,Museum De Javasche Bank
96,97,Surabaya,Ciputra Waterpark,Kenjeran Park,Kebun Binatang Surabaya,Food Junction Grand Pakuwon,| Atlantis Land Surabaya
97,98,Surabaya,Museum Kesehatan Dr. Adhyatma,Patung Buddha Empat Rupa,Taman Hiburan Rakyat,Taman Bungkul,Taman Flora Bratang Surabaya
98,99,Surabaya,Taman Ekspresi Dan Perpustakaan,Museum De Javasche Bank,Surabaya Museum (Gedung Siola),Museum Mpu Tantular,Taman Air Mancur Menari Kenjeran
99,100,Surabaya,Taman Buah Surabaya,Hutan Bambu Keputih,Taman Barunawati,Kebun Bibit Wonorejo,Taman Mundu

In [10]:
df = df.rename(
    columns = {
        'Package' : 'Paket',
        'City' : 'Kota',
        'Place_Tourism1' : 'Destinasi 1',
        'Place_Tourism2' : 'Destinasi 2',
        'Place_Tourism3' : 'Destinasi 3',
        'Place_Tourism4' : 'Destinasi 4',
        'Place_Tourism4' : 'Destinasi 5',
    }
)

df

,Paket,Kota,Destinasi 1,Destinasi 2,Destinasi 3,Destinasi 5,Place_Tourism5
0,1,Jakarta,Pasar Tanah Abang,Taman Ayodya,Museum Tekstil,NaN,NaN
1,2,Jakarta,Pasar Tanah Abang,Pasar Taman Puring,Pasar Petak Sembilan,NaN,NaN
2,3,Jakarta,Perpustakaan Nasional,Monas,Masjid Istiqlal,NaN,NaN
3,4,Jakarta,Pulau Tidung,Pulau Bidadari,Pulau Pari,Pulau Pramuka,Pulau Pelangi
4,5,Jakarta,Museum Satria Mandala,Museum Wayang,Museum Bahari Jakarta,Museum Macan (Modern and Contemporary Art in N...,NaN
...,...,...,...,...,...,...,...
95,96,Surabaya,Ekowisata Mangrove Wonorejo,Taman Harmoni Keputih,Taman Kunang-Kunang,Taman Ekspresi Dan Perpustakaan,Museum De Javasche Bank
96,97,Surabaya,Ciputra Waterpark,Kenjeran Park,Kebun Binatang Surabaya,Food Junction Grand Pakuwon,| Atlantis Land Surabaya
97,98,Surabaya,Museum Kesehatan Dr. Adhyatma,Patung Buddha Empat Rupa,Taman Hiburan Rakyat,Taman Bungkul,Taman Flora Bratang Surabaya
98,99,Surabaya,Taman Ekspresi Dan Perpustakaan,Museum De Javasche Bank,Surabaya Museum (Gedung Siola),Museum Mpu Tantular,Taman Air Mancur Menari Kenjeran
99,100,Surabaya,Taman Buah Surabaya,Hutan Bambu Keputih,Taman Barunawati,Kebun Bibit Wonorejo,Taman Mundu

In [12]:
df.shape

(100, 7)

In [16]:
df.head(10)

,Paket,Kota,Destinasi 1,Destinasi 2,Destinasi 3,Destinasi 5,Place_Tourism5
0,1,Jakarta,Pasar Tanah Abang,Taman Ayodya,Museum Tekstil,NaN,NaN
1,2,Jakarta,Pasar Tanah Abang,Pasar Taman Puring,Pasar Petak Sembilan,NaN,NaN
2,3,Jakarta,Perpustakaan Nasional,Monas,Masjid Istiqlal,NaN,NaN
3,4,Jakarta,Pulau Tidung,Pulau Bidadari,Pulau Pari,Pulau Pramuka,Pulau Pelangi
4,5,Jakarta,Museum Satria Mandala,Museum Wayang,Museum Bahari Jakarta,Museum Macan (Modern and Contemporary Art in N...,NaN
5,6,Jakarta,Waterboom PIK (Pantai Indah Kapuk),Jakarta Aquarium dan Safari,SnowBay Waterpark,NaN,NaN
6,7,Jakarta,Alive Museum Ancol,Ocean Ecopark,SnowBay Waterpark,NaN,NaN
7,8,Jakarta,Kota Tua,Museum Bank Indonesia,Monas,Perpustakaan Nasional,Masjid Istiqlal
8,9,Jakarta,Galeri Nasional Indonesia,Museum Seni Rupa dan Kramik,Galeri Indonesia Kaya,NaN,NaN
9,10,Jakarta,Taman Impian Jaya Ancol,Kota Tua,Museum Bank Indonesia,Museum Fatahillah,Museum Wayang

In [17]:
df.tail(10)

,Paket,Kota,Destinasi 1,Destinasi 2,Destinasi 3,Destinasi 5,Place_Tourism5
90,91,Surabaya,Ekowisata Mangrove Wonorejo,Taman Harmoni Keputih,Taman Air Mancur Menari Kenjeran,NaN,NaN
91,92,Surabaya,Taman Kunang-Kunang,Taman Ekspresi Dan Perpustakaan,Taman Air Mancur Menari Kenjeran,NaN,NaN
92,93,Surabaya,Museum TNI AL Loka Jala Crana,Klenteng Sanggar Agung,Museum Sepuluh Nopember Kota Surabaya,Museum Kesehatan Dr. Adhyatma,Taman Hiburan Rakyat
93,94,Surabaya,Taman Buah Surabaya,Taman Pelangi,Hutan Bambu Keputih,Taman Barunawati,Kebun Bibit Wonorejo
94,95,Surabaya,Museum TNI AL Loka Jala Crana,Taman Hiburan Rakyat,Museum De Javasche Bank,Museum Mpu Tantular,NaN
95,96,Surabaya,Ekowisata Mangrove Wonorejo,Taman Harmoni Keputih,Taman Kunang-Kunang,Taman Ekspresi Dan Perpustakaan,Museum De Javasche Bank
96,97,Surabaya,Ciputra Waterpark,Kenjeran Park,Kebun Binatang Surabaya,Food Junction Grand Pakuwon,| Atlantis Land Surabaya
97,98,Surabaya,Museum Kesehatan Dr. Adhyatma,Patung Buddha Empat Rupa,Taman Hiburan Rakyat,Taman Bungkul,Taman Flora Bratang Surabaya
98,99,Surabaya,Taman Ekspresi Dan Perpustakaan,Museum De Javasche Bank,Surabaya Museum (Gedung Siola),Museum Mpu Tantular,Taman Air Mancur Menari Kenjeran
99,100,Surabaya,Taman Buah Surabaya,Hutan Bambu Keputih,Taman Barunawati,Kebun Bibit Wonorejo,Taman Mundu

In [20]:
df.count(axis = 'columns')

0     5
1     5
2     5
3     7
4     6
     ..
95    7
96    7
97    7
98    7
99    7
Length: 100, dtype: int64

In [30]:
url = 'https://raw.githubusercontent.com/mediatechid/bootcamp-data-analyst/main/zomato_resto_file1.json'

data = pd.read_json(url)

data

,results_found,restaurants,results_shown,results_start,message,code,status
0,17151.0,"[{'restaurant': {'has_online_delivery': 1, 'ph...",20.0,1.0,NaN,NaN,NaN
1,4748.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
2,13786.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
3,10224.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
4,7039.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
474,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
475,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
476,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
477,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
478,NaN,NaN,NaN,NaN,API limit exceeded,440.0,

In [22]:
data.shape

(479, 7)

In [23]:
data.head(10)

,results_found,restaurants,results_shown,results_start,message,code,status
0,17151.0,"[{'restaurant': {'has_online_delivery': 1, 'ph...",20.0,1.0,NaN,NaN,NaN
1,4748.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
2,13786.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
3,10224.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
4,7039.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
5,5678.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
6,5374.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
7,1382.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
8,1534.0,"[{'restaurant': {'has_online_delivery': 1, 'ph...",20.0,1.0,NaN,NaN,NaN
9,2206.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN

In [24]:
data.tail(10)

,results_found,restaurants,results_shown,results_start,message,code,status
469,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
470,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
471,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
472,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
473,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
474,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
475,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
476,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
477,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
478,NaN,NaN,NaN,NaN,API limit exceeded,440.0,

In [41]:
restoran = data[['restaurants']]

restoran

                                           restaurants
0    [{'restaurant': {'has_online_delivery': 1, 'ph...
1    [{'restaurant': {'has_online_delivery': 0, 'ph...
2    [{'restaurant': {'has_online_delivery': 0, 'ph...
3    [{'restaurant': {'has_online_delivery': 0, 'ph...
4    [{'restaurant': {'has_online_delivery': 0, 'ph...
..                                                 ...
474                                                NaN
475                                                NaN
476                                                NaN
477                                                NaN
478                                                NaN

[479 rows x 1 columns]

In [79]:
nama_restoran = []

for key, value in restoran.items():
  for a,b in value.items():
    if isinstance(b, list):
      for x in b:
        for z,y in x['restaurant'].items():
          # print(f" key = {z}, value = {y}")
          if z == 'name':
            nama_restoran.append(y)
            print(y)

Hauz Khas Social
Qubitos - The Terrace Cafe
The Hudson Cafe
Summer House Cafe
38 Barracks
Spezia Bistro
Manhattan Brewery & Bar Exchange
The Wine Company
Farzi Cafe
Indian Grill Room
Cafeteria & Co.
Farzi Cafe
Molecule Air Bar
HotMess
My Bar Headquarters
FLYP@MTV
Tamasha
The Barbeque Company
Saravana Bhavan
Odeon Social
Spice Kraft
Hoppipola
Barbeque Nation
Peter Cat
Barbeque Nation
What's Up
6 Ballygunge Place
TGI Friday's
The Irish House
Asia Kitchen by Mainland China
India Restaurant
Nawwarah
Santa's Fantasea
Mumbai Local
Sigree Global Grill
BarBQ
Mocambo
Gabbar's Bar & Kitchen
Ocean Grill
Flame & Grill
Farzi Cafe
The Fusion Kitchen
Tea Villa Cafe
Mumbai Vibe
38 Degree East
Mirchi And Mime
R' ADDA
The American Joint
Grandmama's Cafe
SpiceKlub
Stacks And Racks
Tea Villa Cafe
Cafe Hydro
Tea Villa Cafe
Joey's Pizza
Joey's Pizza
The Rolling Pin
Tea Villa Cafe
145 Kala Ghoda
The English Department Bar & Diner
Flechazo
Toit
Truffles
ECHOES Koramangala
Big Brewsky
Farzi Cafe
Koramangala Social
Onesta
Three Dots & A Dash
Glen's Bakehouse
Onesta
AB's - Absolute Barbecues
Eat Street
Hoot
Communiti
Onesta
The Fatty Bao - Asian Gastro Bar
Sultans of Spice
Bombay Brasserie
The Black Pearl
Farzi Cafe
Le Plaisir
Tales & Spirits
The Urban Foundry
Barbeque Ville
The Little Next Door
Apache
Kargo
Mineority By Saby
Agent Jack's Bar
Teddy Boy
Sautéed Stories
Barbeque Nation
Effingut Brewerkz
The Sassy Spoon
18 Degrees Resto Lounge
Chili's
Effingut Brewerkz
German Bakery Wunderbar
Blue Water
AB's - Absolute Barbecues
Chili's
Prost Brew Pub
Chili's
United Kitchens of India
Mocha Bar
Dock Forty Five
AB's - Absolute Barbecues
The Fisherman's Wharf
The Grand Trunk Road
Sahib’s Barbeque by Ohri’s
Exotica
Saffron Mantra
Conçu
Jonathan's Kitchen - Holiday Inn Express & Suites
Olive Bistro
Pine & Dine
Heart Cup Coffee
Coffee Cup
Churrolto
Coal Barbecues
Maplai
Haunted
Chili's
Basil With A Twist
Pind
That Madras Place
Palmshore
AB's - Absolute Barbecues
Bombay Brasserie
Fusilli Reasons
Barbeque Nation
Palmshore
Paradise
Palmshore
Writer's Cafe
Kaidi Kitchen
Ciclo Cafe
Pantry d'or
L'amandier
Vintage Machine
Barbeque Nation
Spice Caves
Royal Sky
The Cherry Tree Cafe
Grandson of Tunday Kababi
Bar Bar
Underdoggs Sports Bar & Grill
Dastarkhwan
L 14 - Renaissance Lucknow Hotel
The Chocolate Heaven
Colours by Royal Cafe - Royal Inn
Cappuccino Blast
Percussion
Free Spirit
Frozen Factory
Homeys Cafe
The Pebbles Bistro
The Urban Terrace
Chemistry Café
Cafe 17
Paragon
Tonico Cafe
Kashi Art Cafe
Cocoa Tree
Slice of Spice
Grand Hotel Restaurant
Bloomsbury's Boutique Cafe and Artisan Bakery
Mustake Multicuisine Restaurant
French Toast
ChaiCofi
Nawras Seafood Restaurant
Aangan - Downtown Multicuisine Restaurant
Palaaram
Chiyang
Ali Baba & 41 Dishes
Ifthar
Barbeque Nation
Dhe Puttu
Thakkaaram
Blackout
The Forresta Kitchen & Bar
WTF
Tapri Central
Meraaki Kitchen
Replay
Mutual's
On The House
Cafe LazyMojo
Mamu's Infusion
O2- The Plant Cafe
Zolocrust - Hotel Clarks Amer
Decked Up By Garden Cafe
Calzone- Dine & Rooftop Lounge
Sky Beach
Monarch Restaurant - Holiday Inn Jaipur City Centre
Taruveda Bistro
Chao Chinese Bistro - Holiday Inn Jaipur City Centre
Chokhi Dhani
Nibs Cafe
Mocha
Blue -  Rooftop Cafe Restaurant Bistro
La Pino'z Pizza
Huber & Holly
Yanki Sizzlers
Brick Kitchen
Puffizza
Nini's Kitchen
@Mango
Fozzie's Pizzaiolo
Mazzo
650 - The Global Kitchen
Swati Snacks
MoMo Café - Courtyard By Marriott
The Garden Cafe - The Fern
Kabir Restaurant
Cafe Alfresco
Cryo Lab
Patang - The Revolving Restaurant
Turquoise Villa
OvenFresh
TGI Friday's
Chili's
The Night Factory
Uncle Jack's
Karim's
Barbeque Nation
Taco Bell
Pal Dhaba
Brooklyn Central
Virgin Courtyard
Super Donuts
The Shooters Cafe
Hops n Grains
Nik Baker's
Burgrill
Pirates of Grill
Kylin Experience
Midnight Chef
Mocha
Britto's Bar & Restaurant
Antares
Curlies
Fat Fish
Martin's Corner
Souza Lobo
Ritz Classic
Infantaria
Burger Factory
The Black Sheep Bistro
Baba Au Rhum
Club Cubana
La Plage
St. Anthony's
The Fisherman's Wharf
Fisherman's Cove
Calamari
The Fisherman's Wharf
Cafe Al Fresco by Cantina Bodega
LPK Waterfront
Mocha
Just My Bakes
KYRO
Square - Sayaji Hotel
Oye24
Cafe Terazza
Cafe Palette
The Creative Kitchen - Radisson Blu Hotel
Waffle House
JAL - A Jungle Restaurant
10 Downing Street
Mangosteen Cafe
The Yellow Chilli
Vidorra
Mama Loca
Nafees Restaurant
Cakesmith's Alley
Freito
Cafe Yolo
Hobnob Gourmet Cafébar
Al Arabian Express
Sadhana Restaurant
Barbeque Ville
Spice Route
The Cafe Katta
Barbeque Nation
Soma at Sula
Little Italy
Curry Leaves
12212
RiverDine Restaurant & Bar
Veg Aroma
Chai Tapri
Divtya Budhlya Wada Restaurant
Enter The Dragon
White X Sky Lounge
Eastern Spice
House Of Flavours
The Bake Studio
Hotel Radhakrishna
Barbeque Nation
Bistro 226
Aman Chicken
Nik Bakers
The Yellow Chilli
Bistro Flamme Bois
Hot Breads
Pirates Of Grill
Mocha
Hawai Adda
Kitchen At 95 - Hyatt Regency
The BrewMaster - The Mix Fine Dine
Indian Summer
Belfrance Luxury Chocolates
Basant
Basant Restaurant
Nando's
Spice Cube
District 6
Domino's Pizza
Barbeque Nation
Three Guys
The Zouq : Resto-Cafe
Brooklyn Blues
The Basement Café
The Woking Mama
Yo! China
The Corner Cafe
BrewBakes
Terra Mayaa Restaurant and Lounge
Mocha
Confucius
4 Seasons
Café Riverrun
Shanghai Salsa
Underdoggs Sports Bar & Grill
Chung Fa
Fat Belly
Strawberry Fields
Ziya
Makhan Fish and Chicken Corner
Bharawan Da Dhaba
The Kulcha Land
Brothers Dhaba
Charming Chicken
Kanha Sweets
Beera Chicken Corner
Brothers' Amritsari Dhaba
La Roma Pizzeria
Gurdas Ram Jalebi Wala
Bade Bhai Ka Brothers' Dhaba
Crystal Restaurant
Surjit Food Plaza
Brijwasi Chat Bhandar
Shudh Restaurant
The Yellow Chilli
Bubby Fish & Chicken Corner
Bon Gateau
Sakhis Watz Kukin
Ahuja Milk Bhandar
Upper Crust
Mr Brown
Liquid
Anaicha's Food Joint
Hucka
Verandah
UrbanCrave
Waterside - The Landmark Hotel
Gyan Vaishnav
Dunkin Donuts
Barbeque Nation
Atmosphere Grill Cafe Sheesha
Royal Dine - Hotel Royal Cliff
Little Chef
Dhuaan
Chin Mi
Urban Crave Express
Aromas
The Zaffran
Tadka
The Tamarind Tree
Cafe El Chico
KFC
Hot Stuff
Sagar Ratna
Bean Here
Tandoor Restaurant
Eat On
Dewsis
Friends Forever
The BrewMaster
Paradise
Subway
Bikanerwala
Pizza Hut
Aryan Family's Delight
Hotel Ravisha Continental
Pind Balluchi
Moti Mahal Delux
McDonald's
Kream N Krunch
Bhoj Restaurant
Yalla Yalla
Mokoholic Juice Bar
d' Curry House
Mauj Restaurant
Indiana Veg Restaurant
Downside Up
Kailash Restaurant
Madhuban Restaurant - Welcome Hotel Rama International
Great Sagar Restaurant
Ashoka's Veg Restaurant
Domino's Pizza
Naivedya
Kareem's Fine Dining
Angeethi Restaurant
Hotel Laadli
Balbeer's Kitchen & Bar
Kareem's Kabab & Biryani
That Baat
10 Downing Street
Bake N Shake
Papa Mexicano
Da pizzeria
Bapu Ki Kutia
Kebabsville - Sayaji Hotel
Manohar Dairy And Restaurant
Sagar Gaire Fast Food
Chi Kitchen
Maybe There
Kafe Kulture
Violet Hour
The Kasbah
Black N White Cafe
Manohar Dairy And Restaurant
Pizza Hut
Bake N Shake
Bake N Shake
The Urban Socialite
Indian Coffee House
Prana
Moti Mahal Delux Tandoori Trail
Kaveri Restaurant And Caterers
KFC
Aroma - The Royal Retreat
Yo China Restaurant
The Urban Brava
Kaveri Restaurant And Caterers
Pizza Hut
The Kav's
Waterfront - Radisson Blu
7th Heaven
Yellow Sapphire
Punjab Sweet House
The Best
Food Belle
OMG Cafe
Jungli Moon Dance Restaurant
Kathi Kabab
Hot Lips
The Square - Hotel Novotel
Flying Spaghetti Monster
Barbeque Nation
Pizza Hut
Kamat Restaurant
Alpha Hotel
Double Roti
Pizza Hut
Plot 17
Six Degrees
Percolator Coffee House
My Restaurant
Vista - The Park
Bake My Wish
Kaloreez
Sri Sairam Parlour
Sea Inn - Raju Gaari Dhaba
Tea Trails
D Cabana
Mekong - Hotel GreenPark
Eram Rooftop
Central Perk 7
Aangan Horizon
Adda
Tyre Patty
JUGAAD JN.
Cha cTea
The Chicken Dinesty
Richard's Kitchen & Coffee Bar
Silver Streak
Chai Break
Lal Qila
Chill Ummm
Michael's Kitchen
Taste Of China
99 North Restaurant
Brewberrys The Coffee Bar
Food Fever
Mainland China
Mamma Mia - Mayfair Lagoon
Batlivala & Khanabhoy
Tim's Bistro
Barbeque Nation
Kuchi n Kream
Zucca Pizzeria
Valarmathi Kongunaatu Samayal
Yari
That's Y Food
Burger Ka Baap
On The Go
The Cascade Restaurant
Haribhavanam Hotel
Cafe Totaram
24 Plus Cafe & Restaurant
Cream Centre
Sree Annapoorna
Cream Stone
CakeBee
Bird On Tree
Kites Cafe
Machali
Kobe Sizzlers
Punjab Da Pind
Gajalee Sea Food
Diesel Cafe
Sizzler's Ranch
Spindrift
Barbeque Nation
Brio Cafe and Grill
Liquid Lounge
Giri Manja's
Maharaja Restaurant
Village Restaurant
#45
Froth On Top
Sagar Ratna
Smoke N Oven
Kabab Studio
Crave Desserts & Bakes
Hao Ming
Tomato's
Meraki
Kabir Kitchen
Coffee Culture
La Quello - Mediterranean Kitchen
Barbeque Nation
That Place
Wok On Fire
The Yellow Chilli
VarieTea
El Amigos Kitchen
Little Italy
Gazebo Garden Restaurant
22nd Parallel
Freshco - The Health Café
Offside Lounge
Mandap - Hotel Express Towers
Pizza Hut
Mr Toasties
Kaphi Pibama
Barbeque Nation
The B.A.W.A
The Breakfast Story
House of Caffeine
Mocha
Checker's
The Zuree Urban Kitchen
KFC
Moksh The Restro Lounge
NESCAFÉ Illusions
Cafe Zinea
Hide Out The Street Cafe
FSB
Ashoka Restaurant
Mainland China
Ten Downing Street Restaurant & Bar
Tapri The Chai Books Cafe
Eat Street Express
Nineties
Zaikart
Jahanpanah
Sheroes Hangout
Thaaliwala
Pinch Of Spice
Tea'se Me - Rooftop Tea Boutique
Chapter 1 Cafe
Pind Balluchi
The Latitude - Radisson Blu
Pizza Hut
Peshawri - ITC Mughal
Chokho Jeeman Marwari Jain Bhojanalya
Rangrezz Restaurant
The Charcoal Chimney
Taj Bano - ITC Mughal
Time2Eat - Mama Chicken
Dasaprakash Restaurant
Dawat-e-Nawab - Radisson Blu
MoMo Cafe
Bon Barbecue
G Thal
Barbeque Nation
Kalsang Friends Corner
Jalapenos
TBistro
Punjab Grill
The Great Indian Pub
Eddie's Patisserie
Town Table Restaurant
Anandam
Kalsang AMA Cafe
Doon Darbar
Black Pepper Restaurant
Dunkin Donuts
First Gear Cafe
BMG - All Day Dining
Cafe Marigold
Razzmatazz
Tirupati Restaurant
Y Cafe & Restaurant
The Punjabi Essence Restaurant
Empire Restaurant
Mezzaluna
Jalpaan Dining Saga
Pizza Hut
Barbeque Nation
Cafe Cornucopia
Pakva Lounge
The Old House
The Barge Restaurant
Vinayaka Mylari
Jungle The Restaurant
By The Way
Spring - Radisson Blu Plaza
Nanking
Oyster Bay
Hotel RRR Mysore
Big Chicken
Tandooriwala
Green Leaf
Purple Haze
Baker Street
Le Dupleix
Villa Shanti
Zuka Choco-la
Le Cafe
Cafe des Arts
The Indian Kaffe Express
Le Club
#Dilliwaala6
Bay of Buddha -  The Promenade
Blueline - The Promenade
The Pasta Bar Veneto
Tanto Pizzeria
Rendezvous Cafe Restaurant
Gelateria Montecatini Terme
Spice Route
The Smoothie Bar
Italize
Cafe Ole
Auroville Bakery
Level 5 - Terrace Restro & Cafe
Thalaivaa
Global Local
Falafel Lovers
Wok On Fire
Leonardo Italian Mediterranean Dining
Coffee Culture - The Ristorante Lounge
Black Pepper
The Food Lab
Wok On Fire
The Hog Spot
The Creamery
The Centre Court
World Platter
Golden Dragon
Mysore Cafe
The Sizzling Salsa
Pizza Hut
The Haus
Kansar Gujarati Thali
Baati Chokha
VNS Live Studio
Ming Garden
Deena Chat Bhandar
Pizzeria Vaatika Cafe
Kerala Cafe
Kashi Chat Bhandar
Open Hand Shop & Cafe
3Cherryz Sky Lounge & Cafe
I:ba Cafe & Restaurant
Tandoor Villa
Blue Lassi
Chrystal Bowl Restaurant
Flavours Cafe
Singh's Delight Restaurant
Burger King
eastWEST - Radisson Hotel
Aman Restaurant
Dosa Cafe
The Great Kabab Factory - Radisson Hotel
Swaaddesh
Genuine Broaster Chicken
The Yellow Chilli
Biryani Mahal
Pind Balluchi
Mainland China
17 Degrees
Red Chilli
Pukhtaan-The Royal Taste of India
Bansi Vihar
Indian Summer Cafe
Kapil Dev's Eleven
Roti Restaurant
McDonald's
Raj Rasoi
Sri Basant Vihar
Nirvana
Spice Court - Hotel Maurya
KFC
Angeethi
Grand Barbeque Buffet Restaurant
Farzi Cafe
AB's Absolute Barbecues
AB's Absolute Barbecues
SpiceKlub
Grub Shack
The Farm
The Cheesecake Factory
Tresind - Nassima Royal Hotel
Hard Rock Cafe
Red Lobster
The Coffee Club
SALT
Barbeque Nation
Parker's
Maharaja Bhog
Rasoi Ghar
Applebee's
Carnival By Tresind
Din Tai Fung
Artistry
Artichoke Cafe
Makansutra Gluttons Bay
Bitters & Love
Rhubarb Le Restaurant
Sky On 57
I Am
The Refinery Singapore
Super Loco
Chye Seng Huat Hardware
Al'frank Cookies
Potato Head Folk
Cut By Wolfgang Puck
Jaan
The Lokal
Fratini La Trattoria
Restaurant Andre
Boufe Boutique Cafe
Summer Pavilion
Colony
Rajasthan Al Malaki
Derby
Crafted Blends
Najmat Lahore Restaurant
Saffron
TGI Friday's
Applebee's
Pizza Hut
Nayaab Haandi
Aroos Damascus
Paper Fig
Nando's
Gazebo
Zaroob
Al Mukhtar Bakery
Vadakkan Pepper
Peking Chinese Restaurant
Katis Restaurant
Kamat
Sis Burger
Famous Dave's Barbecue
Tamba
Genghis Grill
Denny's
The Cheesecake Factory
Bait El Khetyar
Cho Gao - Crowne Plaza Abu Dhabi
Punjab Grill
Via Delhi
Olive Garden
Indian By Nature
Applebee's
Pizza Di Rocco
P.F. Chang's
Tikka Tonight
Sangeetha Vegetarian Restaurant
Gazebo
Hot Palayok
Salt
Sofra Istanbul
The Sizzle
Cricket Club Cafe
The Commons
Cafe Beverly
Carnival Ice Cream
Ministry of Crab
Upali's
Burger's King
CIOCONAT Lounge
Elite Indian Restaurant
Butter Boutique
The Paddington
Malay Restaurant
Cafe Shaze
Simply Strawberries By Jagro
Arabian Knights
Queen's Cafe
The Manhattan Fish Market
T.G.I. Friday's
Chinese Dragon Cafe
Bayramoğlu Döner
Draft Gastro Pub
Valonia
J'adore Chocolatier
Karaköy Güllüoğlu
Ceviz Ağacı
Dem Karaköy
Huqqa
Baltazar
Leman Kültür
Virginia Angus
Eataly
Big Chefs
Filizler Köftecisi
Emirgan Sütiş
Aşşk Kahve
MOC İstanbul
Namlı Gurme
Starbucks
Walter's Coffee Roastery
Çukurağa Sofrası
Meşhur Tavacı Recep Usta
Masabaşı Kebapçısı
Hattena Hatay  Sofrası
Düveroğlu
Zigana Pide
Timboo Cafe
Pizza İl Forno
Nusr-Et
Düveroğlu
Turta Home Cafe
The Bigos
Masabaşı
Cafemiz
Kebap 49
Liva
Yıldız Aspava
Timboo Cafe
Meşhur Özçelik Aspava
Gaga Manjero
Dishoom
Duck & Waffle
Bao
Roti Chai
Yauatcha
The Breakfast Club
Flat Iron
sketch Gallery
Restaurant Gordon Ramsay
Gymkhana
Dishoom
Shake Shack
Five Guys
Hakkasan
Nobu
Jamie's Italian
Bone Daddies
Roka
Bocca Di Lupo
Masala Zone
Roti & Boti
7st by Mumbai Spices
The Manhattan FISH MARKET
Zaffran Dining Experience
Gymkhana
Indian Coffee House
Vine - The St. Regis
Mainland China Restaurant
Eatopia
MRA Bakery Sweets & Restaurant
Zaoq
Aalishan
Ponderosa
Coral - InterContinental Doha
Sabai Thai - The Westin Doha Hotel & Spa
Gokul Gujarati Restaurant
Punjab Restaurant
Paper Moon
Texas Roadhouse
Applebee's
Izakaya Kikufuji
The Food Hall by Todd English
Ooma
Spiral - Sofitel Philippine Plaza Manila
NIU by Vikings
Din Tai Fung
Heat - Edsa Shangri-La
Mad Mark's Creamery & Good Eats
Sambo Kojin
Silantro Fil-Mex
Silantro Fil-Mex
Locavore
Balay Dako
Buffet 101
Sodam Korean Restaurant
Vikings
Le Petit Souffle
Wildflour Cafe + Bakery
Hobing Korean Dessert Cafe
Guevarra's
Jarryds
tashas
Coco Safar
Beluga
Willoughby & Co.
Truth Coffee
Gibson's Gourmet Burgers & Ribs
My Sugar
Kloof Street House
Rocomamas
The Creamery
Salushi
Jerry's Burger Bar
Active Sushi
La Parada
The Butcher's Wife
Nobu - One&Only
Grand Café & Beach
Origin Coffee Roasting
Jason Bakery
Jamie's Italian
Gemelli Cucina Bar
Craft
Momo Baohaus
The Big Mouth
The Wolfpack
Marble
Urbanologi
Licorish Bistro
Hudsons
Cafe Del Sol Botanico
Social on Main
Perron
Salsa Mexican Grill
The Smokehouse and Grill
The National
Escondido Tapas
Cube - Tasting Kitchen
Remo's Maximilliano
The Whippet
Coco Bambu
Coco Bambu
Taypá
New Koto
Brazilian American Burgers
Taco Pep
Beirute
Pizza à Bessa
Sandubas Café
Villa Tevere
Chez Michou
Rovereto
Buena Carne
Manzuá
Sushi Loko
Casa do Biscoito Mineiro
Outback Steakhouse
Maori
Gero
Café Daniel Briand
Templo da Carne - Marcos Bassi
Cantina Famiglia Mancini
Esquina Mocotó
Jiquitaia
Red Steak & Burger
Super Grill
Skye - Hotel Unique
Divino Fogão
A Figueira Rubaiyat
Terraço Itália
Meats
Kinoshita
Sainte Marie Gastronomia
Paris 6 Classique
Les 3 Brasseurs
Paribar
Kawa Sushi
Veloso
Gopala Hari
Cantinho da Gula
Santos
Home Sweet Home
Nawaab
San Carlo
Almost Famous Burgers
Archies
Jamie's Italian
Lahore
The Grill On The Alley
Solita
Mughli
The French by Simon Rogan - The Midland
Mr Cooper's House & Garden - The Midland
Gaucho
Monolos Playhouse Restaurant
Zouk Tea Bar & Grill
Manchester House
Teacup
Chaophraya
Akbars
Tipu Sultan
Jamie's Italian
Chaophraya
Purnell's
Fiesta del Asado
Pepe's Piri Piri
Bank
Ju Ju's Cafe
The Warehouse Cafe
Bodega
Bar Estilo
Istanbul Restaurant
Handmade Burger Co.
Chennai Dosa
Damascena Coffee House
Lasan Restaurant
The Plough
Mughal E Azam
San Carlo
Jamjar
Eight - The Langham Hotel
The Kimchi Project
Baduzzi
De Fontein Belgian Beer Cafe
Depot Eatery and Oyster Bar
Kiss Kiss
Winona Forever
Eden Noodles Cafe 四川担担面
Frasers
PappaRich
Federal Delicatessen
Orleans
Milse
Tucks and Bao
Big Fish Eatery
Miann
The Garden Shed
Giapo
Chinoiserie
Little Sister Cafe
Loretta
Fidel's
Caffe L'affare
Ombra
Burger Liquor
The Crab Shack
Floriditas
Little Penang
The Hangar
Ekim Burgers
Enigma Cafe
Five Boroughs
wagamama
Fisherman's Plate
Maranui Cafe
Olive
Hippopotamus - Museum Hotel
Charley Noble Eatery & Bar
Midnight Espresso
Dragonfly
The Golconda Bowl - hilton
Mc Donald
Daawat Restaurant
Salt Water Cafe
Bugilz
Zomato Gurgaon Office
Arnold's
Simply Asia
Zomato Gurgaon Office new
China 1
Debonairs Pizza
KFC
KFC
Galbi
Bardelli's
Toby's Estate
Caturra Coffee Bar
D'Angelos
Mcdonalds
The Woodlands Eatery
Aprazível
Garota de Ipanema
Confeitaria Colombo
Garota de Ipanema
Braseiro da Gávea
Bibi
Shirley
Filé de Ouro
Leme Light
Pesqueiro Eco Gourmet
Sushi Leblon
Balada Mix
TT Burger
Aconchego Carioca
Cervantes
Amir
Quiosque Chopp Brahma
Talho Capixaba
D.O.C Ristorante
Zazá Bistrô Tropical
Fish Streat
Talaga Sampireun
Talaga Sampireun
Lucky Cat Coffee & Kitchen
Satoo - Hotel Shangri-La
Sushi Masa
Flip Burger
Lemongrass
Talaga Sampireun
3 Wise Monkeys
Fish Streat
Zenbu
Onokabe
Toodz House
Union Deli
MONKS
OJJU
Momo Milk
Skye
Avec Moi Restaurant and Bar
Old Town Italy
The Belgian Triple
Brooklyn Brothers
Life Grand Cafe
Restaurant Mosaic @ The Orient
Kream
Geet Indian Restaurant
El Pistolero
23 On Hazelwood
Harissa Bistro
Culture Club - Bar De Tapas
Spice - The Indian Kitchen
Blos Cafe
Carbon Bistro
Baobab Cafe & Grill
Capital Craft Beer Academy
The Black Bamboo
Crawdaddy's
Parrot's
Hogshead
Loudons Cafe & Bakery
El Cartel
Ting Thai Caravan
The Elephant House
Love Crumbs
The Kitchin
Mimi's Bakehouse
Mother India's Cafe
10 To 10 In Delhi
Hard Rock Cafe
Tuk Tuk Indian Street Food
Chaophraya
Steak
Bentoya
The Witchery & The Secret Garden
The Boozy Cow
La Favorita
Roseleaf Bar Cafe
Civerinos
The Hanging Bat

In [80]:
print(nama_restoran)

['Hauz Khas Social', 'Qubitos - The Terrace Cafe', 'The Hudson Cafe', 'Summer House Cafe', '38 Barracks', 'Spezia Bistro', 'Manhattan Brewery & Bar Exchange', 'The Wine Company', 'Farzi Cafe', 'Indian Grill Room', 'Cafeteria & Co.', 'Farzi Cafe', 'Molecule Air Bar', 'HotMess', 'My Bar Headquarters', 'FLYP@MTV', 'Tamasha', 'The Barbeque Company', 'Saravana Bhavan', 'Odeon Social', 'Spice Kraft', 'Hoppipola', 'Barbeque Nation', 'Peter Cat', 'Barbeque Nation', "What's Up", '6 Ballygunge Place', "TGI Friday's", 'The Irish House', 'Asia Kitchen by Mainland China', 'India Restaurant', 'Nawwarah', "Santa's Fantasea", 'Mumbai Local', 'Sigree Global Grill', 'BarBQ', 'Mocambo', "Gabbar's Bar & Kitchen", 'Ocean Grill', 'Flame & Grill', 'Farzi Cafe', 'The Fusion Kitchen', 'Tea Villa Cafe', 'Mumbai Vibe', '38 Degree East', 'Mirchi And Mime', "R' ADDA", 'The American Joint', "Grandmama's Cafe", 'SpiceKlub', 'Stacks And Racks', 'Tea Villa Cafe', 'Cafe Hydro', 'Tea Villa Cafe', "Joey's Pizza", "Joey's Pizza", 'The Rolling Pin', 'Tea Villa Cafe', '145 Kala Ghoda', 'The English Department Bar & Diner', 'Flechazo', 'Toit', 'Truffles', 'ECHOES Koramangala', 'Big Brewsky', 'Farzi Cafe', 'Koramangala Social', 'Onesta', 'Three Dots & A Dash', "Glen's Bakehouse", 'Onesta', "AB's - Absolute Barbecues", 'Eat Street', 'Hoot', 'Communiti', 'Onesta', 'The Fatty Bao - Asian Gastro Bar', 'Sultans of Spice', 'Bombay Brasserie', 'The Black Pearl', 'Farzi Cafe', 'Le Plaisir', 'Tales & Spirits', 'The Urban Foundry', 'Barbeque Ville', 'The Little Next Door', 'Apache', 'Kargo', 'Mineority By Saby', "Agent Jack's Bar", 'Teddy Boy', 'Sautéed Stories', 'Barbeque Nation', 'Effingut Brewerkz', 'The Sassy Spoon', '18 Degrees Resto Lounge', "Chili's", 'Effingut Brewerkz', 'German Bakery Wunderbar', 'Blue Water', "AB's - Absolute Barbecues", "Chili's", 'Prost Brew Pub', "Chili's", 'United Kitchens of India', 'Mocha Bar', 'Dock Forty Five', "AB's - Absolute Barbecues", "The Fisherman's Wharf", 'The Grand Trunk Road', 'Sahib’s Barbeque by Ohri’s', 'Exotica', 'Saffron Mantra', 'Conçu', "Jonathan's Kitchen - Holiday Inn Express & Suites", 'Olive Bistro', 'Pine & Dine', 'Heart Cup Coffee', 'Coffee Cup', 'Churrolto', 'Coal Barbecues', 'Maplai', 'Haunted', "Chili's", 'Basil With A Twist', 'Pind', 'That Madras Place', 'Palmshore', "AB's - Absolute Barbecues", 'Bombay Brasserie', 'Fusilli Reasons', 'Barbeque Nation', 'Palmshore', 'Paradise', 'Palmshore', "Writer's Cafe", 'Kaidi Kitchen', 'Ciclo Cafe', "Pantry d'or", "L'amandier", 'Vintage Machine', 'Barbeque Nation', 'Spice Caves', 'Royal Sky', 'The Cherry Tree Cafe', 'Grandson of Tunday Kababi', 'Bar Bar', 'Underdoggs Sports Bar & Grill', 'Dastarkhwan', 'L 14 - Renaissance Lucknow Hotel', 'The Chocolate Heaven', 'Colours by Royal Cafe - Royal Inn', 'Cappuccino Blast', 'Percussion', 'Free Spirit', 'Frozen Factory', 'Homeys Cafe', 'The Pebbles Bistro', 'The Urban Terrace', 'Chemistry Café', 'Cafe 17', 'Paragon', 'Tonico Cafe', 'Kashi Art Cafe', 'Cocoa Tree', 'Slice of Spice', 'Grand Hotel Restaurant', "Bloomsbury's Boutique Cafe and Artisan Bakery", 'Mustake Multicuisine Restaurant', 'French Toast', 'ChaiCofi', 'Nawras Seafood Restaurant', 'Aangan - Downtown Multicuisine Restaurant', 'Palaaram', 'Chiyang', 'Ali Baba & 41 Dishes', 'Ifthar', 'Barbeque Nation', 'Dhe Puttu', 'Thakkaaram', 'Blackout', 'The Forresta Kitchen & Bar', 'WTF', 'Tapri Central', 'Meraaki Kitchen', 'Replay', "Mutual's", 'On The House', 'Cafe LazyMojo', "Mamu's Infusion", 'O2- The Plant Cafe', 'Zolocrust - Hotel Clarks Amer', 'Decked Up By Garden Cafe', 'Calzone- Dine & Rooftop Lounge', 'Sky Beach', 'Monarch Restaurant - Holiday Inn Jaipur City Centre', 'Taruveda Bistro', 'Chao Chinese Bistro - Holiday Inn Jaipur City Centre', 'Chokhi Dhani', 'Nibs Cafe', 'Mocha', 'Blue -  Rooftop Cafe Restaurant Bistro', "La Pino'z Pizza", 'Huber & Holly', 'Yanki Sizzlers', 'Brick Kitchen', 'Puffizza', "Nini's Kitchen", '@Mango', "Fozzie's Pizzaiolo", 'Mazzo', '650 - The Global Kitchen', 'Swati Snacks', 'MoMo Café - Courtyard By Marriott', 'The Garden Cafe - The Fern', 'Kabir Restaurant', 'Cafe Alfresco', 'Cryo Lab', 'Patang - The Revolving Restaurant', 'Turquoise Villa', 'OvenFresh', "TGI Friday's", "Chili's", 'The Night Factory', "Uncle Jack's", "Karim's", 'Barbeque Nation', 'Taco Bell', 'Pal Dhaba', 'Brooklyn Central', 'Virgin Courtyard', 'Super Donuts', 'The Shooters Cafe', 'Hops n Grains', "Nik Baker's", 'Burgrill', 'Pirates of Grill', 'Kylin Experience', 'Midnight Chef', 'Mocha', "Britto's Bar & Restaurant", 'Antares', 'Curlies', 'Fat Fish', "Martin's Corner", 'Souza Lobo', 'Ritz Classic', 'Infantaria', 'Burger Factory', 'The Black Sheep Bistro', 'Baba Au Rhum', 'Club Cubana', 'La Plage', "St. Anthony's", "The Fisherman's Wharf", "Fisherman's Cove", 'Calamari', "The Fisherman's Wharf", 'Cafe Al Fresco by Cantina Bodega', 'LPK Waterfront', 'Mocha', 'Just My Bakes', 'KYRO', 'Square - Sayaji Hotel', 'Oye24', 'Cafe Terazza', 'Cafe Palette', 'The Creative Kitchen - Radisson Blu Hotel', 'Waffle House', 'JAL - A Jungle Restaurant', '10 Downing Street', 'Mangosteen Cafe', 'The Yellow Chilli', 'Vidorra', 'Mama Loca', 'Nafees Restaurant', "Cakesmith's Alley", 'Freito', 'Cafe Yolo', 'Hobnob Gourmet Cafébar', 'Al Arabian Express', 'Sadhana Restaurant', 'Barbeque Ville', 'Spice Route', 'The Cafe Katta', 'Barbeque Nation', 'Soma at Sula', 'Little Italy', 'Curry Leaves', '12212', 'RiverDine Restaurant & Bar', 'Veg Aroma', 'Chai Tapri', 'Divtya Budhlya Wada Restaurant', 'Enter The Dragon', 'White X Sky Lounge', 'Eastern Spice', 'House Of Flavours', 'The Bake Studio', 'Hotel Radhakrishna', 'Barbeque Nation', 'Bistro 226', 'Aman Chicken', 'Nik Bakers', 'The Yellow Chilli', 'Bistro Flamme Bois', 'Hot Breads', 'Pirates Of Grill', 'Mocha', 'Hawai Adda', 'Kitchen At 95 - Hyatt Regency', 'The BrewMaster - The Mix Fine Dine', 'Indian Summer', 'Belfrance Luxury Chocolates', 'Basant', 'Basant Restaurant', "Nando's", 'Spice Cube', 'District 6', "Domino's Pizza", 'Barbeque Nation', 'Three Guys', 'The Zouq : Resto-Cafe', 'Brooklyn Blues', 'The Basement Café', 'The Woking Mama', 'Yo! China', 'The Corner Cafe', 'BrewBakes', 'Terra Mayaa Restaurant and Lounge', 'Mocha', 'Confucius', '4 Seasons', 'Café Riverrun', 'Shanghai Salsa', 'Underdoggs Sports Bar & Grill', 'Chung Fa', 'Fat Belly', 'Strawberry Fields', 'Ziya', 'Makhan Fish and Chicken Corner', 'Bharawan Da Dhaba', 'The Kulcha Land', 'Brothers Dhaba', 'Charming Chicken', 'Kanha Sweets', 'Beera Chicken Corner', "Brothers' Amritsari Dhaba", 'La Roma Pizzeria', 'Gurdas Ram Jalebi Wala', "Bade Bhai Ka Brothers' Dhaba", 'Crystal Restaurant', 'Surjit Food Plaza', 'Brijwasi Chat Bhandar', 'Shudh Restaurant', 'The Yellow Chilli', 'Bubby Fish & Chicken Corner', 'Bon Gateau', 'Sakhis Watz Kukin', 'Ahuja Milk Bhandar', 'Upper Crust', 'Mr Brown', 'Liquid', "Anaicha's Food Joint", 'Hucka', 'Verandah', 'UrbanCrave', 'Waterside - The Landmark Hotel', 'Gyan Vaishnav', 'Dunkin Donuts', 'Barbeque Nation', 'Atmosphere Grill Cafe Sheesha', 'Royal Dine - Hotel Royal Cliff', 'Little Chef', 'Dhuaan', 'Chin Mi', 'Urban Crave Express', 'Aromas', 'The Zaffran', 'Tadka', 'The Tamarind Tree', 'Cafe El Chico', 'KFC', 'Hot Stuff', 'Sagar Ratna', 'Bean Here', 'Tandoor Restaurant', 'Eat On', 'Dewsis', 'Friends Forever', 'The BrewMaster', 'Paradise', 'Subway', 'Bikanerwala', 'Pizza Hut', "Aryan Family's Delight", 'Hotel Ravisha Continental', 'Pind Balluchi', 'Moti Mahal Delux', "McDonald's", 'Kream N Krunch', 'Bhoj Restaurant', 'Yalla Yalla', 'Mokoholic Juice Bar', "d' Curry House", 'Mauj Restaurant', 'Indiana Veg Restaurant', 'Downside Up', 'Kailash Restaurant', 'Madhuban Restaurant - Welcome Hotel Rama International', 'Great Sagar Restaurant', "Ashoka's Veg Restaurant", "Domino's Pizza", 'Naivedya', "Kareem's Fine Dining", 'Angeethi Restaurant', 'Hotel Laadli', "Balbeer's Kitchen & Bar", "Kareem's Kabab & Biryani", 'That Baat', '10 Downing Street', 'Bake N Shake', 'Papa Mexicano', 'Da pizzeria', 'Bapu Ki Kutia', 'Kebabsville - Sayaji Hotel', 'Manohar Dairy And Restaurant', 'Sagar Gaire Fast Food', 'Chi Kitchen', 'Maybe There', 'Kafe Kulture', 'Violet Hour', 'The Kasbah', 'Black N White Cafe', 'Manohar Dairy And Restaurant', 'Pizza Hut', 'Bake N Shake', 'Bake N Shake', 'The Urban Socialite', 'Indian Coffee House', 'Prana', 'Moti Mahal Delux Tandoori Trail', 'Kaveri Restaurant And Caterers', 'KFC', 'Aroma - The Royal Retreat', 'Yo China Restaurant', 'The Urban Brava', 'Kaveri Restaurant And Caterers', 'Pizza Hut', "The Kav's", 'Waterfront - Radisson Blu', '7th Heaven', 'Yellow Sapphire', 'Punjab Sweet House', 'The Best', 'Food Belle', 'OMG Cafe', 'Jungli Moon Dance Restaurant', 'Kathi Kabab', 'Hot Lips', 'The Square - Hotel Novotel', 'Flying Spaghetti Monster', 'Barbeque Nation', 'Pizza Hut', 'Kamat Restaurant', 'Alpha Hotel', 'Double Roti', 'Pizza Hut', 'Plot 17', 'Six Degrees', 'Percolator Coffee House', 'My Restaurant', 'Vista - The Park', 'Bake My Wish', 'Kaloreez', 'Sri Sairam Parlour', 'Sea Inn - Raju Gaari Dhaba', 'Tea Trails', 'D Cabana', 'Mekong - Hotel GreenPark', 'Eram Rooftop', 'Central Perk 7', 'Aangan Horizon', 'Adda', 'Tyre Patty', 'JUGAAD JN.', 'Cha cTea', 'The Chicken Dinesty', "Richard's Kitchen & Coffee Bar", 'Silver Streak', 'Chai Break', 'Lal Qila', 'Chill Ummm', "Michael's Kitchen", 'Taste Of China', '99 North Restaurant', 'Brewberrys The Coffee Bar', 'Food Fever', 'Mainland China', 'Mamma Mia - Mayfair Lagoon', 'Batlivala & Khanabhoy', "Tim's Bistro", 'Barbeque Nation', 'Kuchi n Kream', 'Zucca Pizzeria', 'Valarmathi Kongunaatu Samayal', 'Yari', "That's Y Food", 'Burger Ka Baap', 'On The Go', 'The Cascade Restaurant', 'Haribhavanam Hotel', 'Cafe Totaram', '24 Plus Cafe & Restaurant', 'Cream Centre', 'Sree Annapoorna', 'Cream Stone', 'CakeBee', 'Bird On Tree', 'Kites Cafe', 'Machali', 'Kobe Sizzlers', 'Punjab Da Pind', 'Gajalee Sea Food', 'Diesel Cafe', "Sizzler's Ranch", 'Spindrift', 'Barbeque Nation', 'Brio Cafe and Grill', 'Liquid Lounge', "Giri Manja's", 'Maharaja Restaurant', 'Village Restaurant', '#45', 'Froth On Top', 'Sagar Ratna', 'Smoke N Oven', 'Kabab Studio', 'Crave Desserts & Bakes', 'Hao Ming', "Tomato's", 'Meraki', 'Kabir Kitchen', 'Coffee Culture', 'La Quello - Mediterranean Kitchen', 'Barbeque Nation', 'That Place', 'Wok On Fire', 'The Yellow Chilli', 'VarieTea', 'El Amigos Kitchen', 'Little Italy', 'Gazebo Garden Restaurant', '22nd Parallel', 'Freshco - The Health Café', 'Offside Lounge', 'Mandap - Hotel Express Towers', 'Pizza Hut', 'Mr Toasties', 'Kaphi Pibama', 'Barbeque Nation', 'The B.A.W.A', 'The Breakfast Story', 'House of Caffeine', 'Mocha', "Checker's", 'The Zuree Urban Kitchen', 'KFC', 'Moksh The Restro Lounge', 'NESCAFÉ Illusions', 'Cafe Zinea', 'Hide Out The Street Cafe', 'FSB', 'Ashoka Restaurant', 'Mainland China', 'Ten Downing Street Restaurant & Bar', 'Tapri The Chai Books Cafe', 'Eat Street Express', 'Nineties', 'Zaikart', 'Jahanpanah', 'Sheroes Hangout', 'Thaaliwala', 'Pinch Of Spice', "Tea'se Me - Rooftop Tea Boutique", 'Chapter 1 Cafe', 'Pind Balluchi', 'The Latitude - Radisson Blu', 'Pizza Hut', 'Peshawri - ITC Mughal', 'Chokho Jeeman Marwari Jain Bhojanalya', 'Rangrezz Restaurant', 'The Charcoal Chimney', 'Taj Bano - ITC Mughal', 'Time2Eat - Mama Chicken', 'Dasaprakash Restaurant', 'Dawat-e-Nawab - Radisson Blu', 'MoMo Cafe', 'Bon Barbecue', 'G Thal', 'Barbeque Nation', 'Kalsang Friends Corner', 'Jalapenos', 'TBistro', 'Punjab Grill', 'The Great Indian Pub', "Eddie's Patisserie", 'Town Table Restaurant', 'Anandam', 'Kalsang AMA Cafe', 'Doon Darbar', 'Black Pepper Restaurant', 'Dunkin Donuts', 'First Gear Cafe', 'BMG - All Day Dining', 'Cafe Marigold', 'Razzmatazz', 'Tirupati Restaurant', 'Y Cafe & Restaurant', 'The Punjabi Essence Restaurant', 'Empire Restaurant', 'Mezzaluna', 'Jalpaan Dining Saga', 'Pizza Hut', 'Barbeque Nation', 'Cafe Cornucopia', 'Pakva Lounge', 'The Old House', 'The Barge Restaurant', 'Vinayaka Mylari', 'Jungle The Restaurant', 'By The Way', 'Spring - Radisson Blu Plaza', 'Nanking', 'Oyster Bay', 'Hotel RRR Mysore', 'Big Chicken', 'Tandooriwala', 'Green Leaf', 'Purple Haze', 'Baker Street', 'Le Dupleix', 'Villa Shanti', 'Zuka Choco-la', 'Le Cafe', 'Cafe des Arts', 'The Indian Kaffe Express', 'Le Club', '#Dilliwaala6', 'Bay of Buddha -  The Promenade', 'Blueline - The Promenade', 'The Pasta Bar Veneto', 'Tanto Pizzeria', 'Rendezvous Cafe Restaurant', 'Gelateria Montecatini Terme', 'Spice Route', 'The Smoothie Bar', 'Italize', 'Cafe Ole', 'Auroville Bakery', 'Level 5 - Terrace Restro & Cafe', 'Thalaivaa', 'Global Local', 'Falafel Lovers', 'Wok On Fire', 'Leonardo Italian Mediterranean Dining', 'Coffee Culture - The Ristorante Lounge', 'Black Pepper', 'The Food Lab', 'Wok On Fire', 'The Hog Spot', 'The Creamery', 'The Centre Court', 'World Platter', 'Golden Dragon', 'Mysore Cafe', 'The Sizzling Salsa', 'Pizza Hut', 'The Haus', 'Kansar Gujarati Thali', 'Baati Chokha', 'VNS Live Studio', 'Ming Garden', 'Deena Chat Bhandar', 'Pizzeria Vaatika Cafe', 'Kerala Cafe', 'Kashi Chat Bhandar', 'Open Hand Shop & Cafe', '3Cherryz Sky Lounge & Cafe', 'I:ba Cafe & Restaurant', 'Tandoor Villa', 'Blue Lassi', 'Chrystal Bowl Restaurant', 'Flavours Cafe', "Singh's Delight Restaurant", 'Burger King', 'eastWEST - Radisson Hotel', 'Aman Restaurant', 'Dosa Cafe', 'The Great Kabab Factory - Radisson Hotel', 'Swaaddesh', 'Genuine Broaster Chicken', 'The Yellow Chilli', 'Biryani Mahal', 'Pind Balluchi', 'Mainland China', '17 Degrees', 'Red Chilli', 'Pukhtaan-The Royal Taste of India', 'Bansi Vihar', 'Indian Summer Cafe', "Kapil Dev's Eleven", 'Roti Restaurant', "McDonald's", 'Raj Rasoi', 'Sri Basant Vihar', 'Nirvana', 'Spice Court - Hotel Maurya', 'KFC', 'Angeethi', 'Grand Barbeque Buffet Restaurant', 'Farzi Cafe', "AB's Absolute Barbecues", "AB's Absolute Barbecues", 'SpiceKlub', 'Grub Shack', 'The Farm', 'The Cheesecake Factory', 'Tresind - Nassima Royal Hotel', 'Hard Rock Cafe', 'Red Lobster', 'The Coffee Club', 'SALT', 'Barbeque Nation', "Parker's", 'Maharaja Bhog', 'Rasoi Ghar', "Applebee's", 'Carnival By Tresind', 'Din Tai Fung', 'Artistry', 'Artichoke Cafe', 'Makansutra Gluttons Bay', 'Bitters & Love', 'Rhubarb Le Restaurant', 'Sky On 57', 'I Am', 'The Refinery Singapore', 'Super Loco', 'Chye Seng Huat Hardware', "Al'frank Cookies", 'Potato Head Folk', 'Cut By Wolfgang Puck', 'Jaan', 'The Lokal', 'Fratini La Trattoria', 'Restaurant Andre', 'Boufe Boutique Cafe', 'Summer Pavilion', 'Colony', 'Rajasthan Al Malaki', 'Derby', 'Crafted Blends', 'Najmat Lahore Restaurant', 'Saffron', "TGI Friday's", "Applebee's", 'Pizza Hut', 'Nayaab Haandi', 'Aroos Damascus', 'Paper Fig', "Nando's", 'Gazebo', 'Zaroob', 'Al Mukhtar Bakery', 'Vadakkan Pepper', 'Peking Chinese Restaurant', 'Katis Restaurant', 'Kamat', 'Sis Burger', "Famous Dave's Barbecue", 'Tamba', 'Genghis Grill', "Denny's", 'The Cheesecake Factory', 'Bait El Khetyar', 'Cho Gao - Crowne Plaza Abu Dhabi', 'Punjab Grill', 'Via Delhi', 'Olive Garden', 'Indian By Nature', "Applebee's", 'Pizza Di Rocco', "P.F. Chang's", 'Tikka Tonight', 'Sangeetha Vegetarian Restaurant', 'Gazebo', 'Hot Palayok', 'Salt', 'Sofra Istanbul', 'The Sizzle', 'Cricket Club Cafe', 'The Commons', 'Cafe Beverly', 'Carnival Ice Cream', 'Ministry of Crab', "Upali's", "Burger's King", 'CIOCONAT Lounge', 'Elite Indian Restaurant', 'Butter Boutique', 'The Paddington', 'Malay Restaurant', 'Cafe Shaze', 'Simply Strawberries By Jagro', 'Arabian Knights', "Queen's Cafe", 'The Manhattan Fish Market', "T.G.I. Friday's", 'Chinese Dragon Cafe', 'Bayramoğlu Döner', 'Draft Gastro Pub', 'Valonia', "J'adore Chocolatier", 'Karaköy Güllüoğlu', 'Ceviz Ağacı', 'Dem Karaköy', 'Huqqa', 'Baltazar', 'Leman Kültür', 'Virginia Angus', 'Eataly', 'Big Chefs', 'Filizler Köftecisi', 'Emirgan Sütiş', 'Aşşk Kahve', 'MOC İstanbul', 'Namlı Gurme', 'Starbucks', "Walter's Coffee Roastery", 'Çukurağa Sofrası', 'Meşhur Tavacı Recep Usta', 'Masabaşı Kebapçısı', 'Hattena Hatay  Sofrası', 'Düveroğlu', 'Zigana Pide', 'Timboo Cafe', 'Pizza İl Forno', 'Nusr-Et', 'Düveroğlu', 'Turta Home Cafe', 'The Bigos', 'Masabaşı', 'Cafemiz', 'Kebap 49', 'Liva', 'Yıldız Aspava', 'Timboo Cafe', 'Meşhur Özçelik Aspava', 'Gaga Manjero', 'Dishoom', 'Duck & Waffle', 'Bao', 'Roti Chai', 'Yauatcha', 'The Breakfast Club', 'Flat Iron', 'sketch Gallery', 'Restaurant Gordon Ramsay', 'Gymkhana', 'Dishoom', 'Shake Shack', 'Five Guys', 'Hakkasan', 'Nobu', "Jamie's Italian", 'Bone Daddies', 'Roka', 'Bocca Di Lupo', 'Masala Zone', 'Roti & Boti', '7st by Mumbai Spices', 'The Manhattan FISH MARKET', 'Zaffran Dining Experience', 'Gymkhana', 'Indian Coffee House', 'Vine - The St. Regis', 'Mainland China Restaurant', 'Eatopia', 'MRA Bakery Sweets & Restaurant', 'Zaoq', 'Aalishan', 'Ponderosa', 'Coral - InterContinental Doha', 'Sabai Thai - The Westin Doha Hotel & Spa', 'Gokul Gujarati Restaurant', 'Punjab Restaurant', 'Paper Moon', 'Texas Roadhouse', "Applebee's", 'Izakaya Kikufuji', 'The Food Hall by Todd English', 'Ooma', 'Spiral - Sofitel Philippine Plaza Manila', 'NIU by Vikings', 'Din Tai Fung', 'Heat - Edsa Shangri-La', "Mad Mark's Creamery & Good Eats", 'Sambo Kojin', 'Silantro Fil-Mex', 'Silantro Fil-Mex', 'Locavore', 'Balay Dako', 'Buffet 101', 'Sodam Korean Restaurant', 'Vikings', 'Le Petit Souffle', 'Wildflour Cafe + Bakery', 'Hobing Korean Dessert Cafe', "Guevarra's", 'Jarryds', 'tashas', 'Coco Safar', 'Beluga', 'Willoughby & Co.', 'Truth Coffee', "Gibson's Gourmet Burgers & Ribs", 'My Sugar', 'Kloof Street House', 'Rocomamas', 'The Creamery', 'Salushi', "Jerry's Burger Bar", 'Active Sushi', 'La Parada', "The Butcher's Wife", 'Nobu - One&Only', 'Grand Café & Beach', 'Origin Coffee Roasting', 'Jason Bakery', "Jamie's Italian", 'Gemelli Cucina Bar', 'Craft', 'Momo Baohaus', 'The Big Mouth', 'The Wolfpack', 'Marble', 'Urbanologi', 'Licorish Bistro', 'Hudsons', 'Cafe Del Sol Botanico', 'Social on Main', 'Perron', 'Salsa Mexican Grill', 'The Smokehouse and Grill', 'The National', 'Escondido Tapas', 'Cube - Tasting Kitchen', "Remo's Maximilliano", 'The Whippet', 'Coco Bambu', 'Coco Bambu', 'Taypá', 'New Koto', 'Brazilian American Burgers', 'Taco Pep', 'Beirute', 'Pizza à Bessa', 'Sandubas Café', 'Villa Tevere', 'Chez Michou', 'Rovereto', 'Buena Carne', 'Manzuá', 'Sushi Loko', 'Casa do Biscoito Mineiro', 'Outback Steakhouse', 'Maori', 'Gero', 'Café Daniel Briand', 'Templo da Carne - Marcos Bassi', 'Cantina Famiglia Mancini', 'Esquina Mocotó', 'Jiquitaia', 'Red Steak & Burger', 'Super Grill', 'Skye - Hotel Unique', 'Divino Fogão', 'A Figueira Rubaiyat', 'Terraço Itália', 'Meats', 'Kinoshita', 'Sainte Marie Gastronomia', 'Paris 6 Classique', 'Les 3 Brasseurs', 'Paribar', 'Kawa Sushi', 'Veloso', 'Gopala Hari', 'Cantinho da Gula', 'Santos', 'Home Sweet Home', 'Nawaab', 'San Carlo', 'Almost Famous Burgers', 'Archies', "Jamie's Italian", 'Lahore', 'The Grill On The Alley', 'Solita', 'Mughli', 'The French by Simon Rogan - The Midland', "Mr Cooper's House & Garden - The Midland", 'Gaucho', 'Monolos Playhouse Restaurant', 'Zouk Tea Bar & Grill', 'Manchester House', 'Teacup', 'Chaophraya', 'Akbars', 'Tipu Sultan', "Jamie's Italian", 'Chaophraya', "Purnell's", 'Fiesta del Asado', "Pepe's Piri Piri", 'Bank', "Ju Ju's Cafe", 'The Warehouse Cafe', 'Bodega', 'Bar Estilo', 'Istanbul Restaurant', 'Handmade Burger Co.', 'Chennai Dosa', 'Damascena Coffee House', 'Lasan Restaurant', 'The Plough', 'Mughal E Azam', 'San Carlo', 'Jamjar', 'Eight - The Langham Hotel', 'The Kimchi Project', 'Baduzzi', 'De Fontein Belgian Beer Cafe', 'Depot Eatery and Oyster Bar', 'Kiss Kiss', 'Winona Forever', 'Eden Noodles Cafe 四川担担面', 'Frasers', 'PappaRich', 'Federal Delicatessen', 'Orleans', 'Milse', 'Tucks and Bao', 'Big Fish Eatery', 'Miann', 'The Garden Shed', 'Giapo', 'Chinoiserie', 'Little Sister Cafe', 'Loretta', "Fidel's", "Caffe L'affare", 'Ombra', 'Burger Liquor', 'The Crab Shack', 'Floriditas', 'Little Penang', 'The Hangar', 'Ekim Burgers', 'Enigma Cafe', 'Five Boroughs', 'wagamama', "Fisherman's Pl