In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [1785387, 2833687, 3874437, 2167744, 4602367, 2950039, 17348075],
    'Surface Area': [9984670, 640679, 357114, 301336, 377930, 242495, 9525067],
    'HDI': [0.913, 0.888, 0.916, 0.873, 0.891, 0.907,0.915],
    'Continent': ['America','Europe','Europe','Europe','Asia','Europe','America']
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'],
index=['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom', 'United States'])

df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df["Population"]

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [ ]:
df[df["Population"] > 70]

               Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [ ]:
df.loc[df["Population"] > 70, "Population"]

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [ ]:
df.drop("France")

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df.drop(["Canada","Germany","France"])

                Population       GDP  Surface Area    HDI Continent
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df.drop(columns=["Population","GDP"])

                Surface Area    HDI Continent
Canada               9984670  0.913   America
France                640679  0.888    Europe
Germany               357114  0.916    Europe
Italy                 301336  0.873    Europe
Japan                 377930  0.891      Asia
United Kingdom        242495  0.907    Europe
United States        9525067  0.915   America

In [ ]:
df.drop(["Canada","France"], axis='index')

                Population       GDP  Surface Area    HDI Continent
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df.drop(["Population","GDP"], axis='columns')

                Surface Area    HDI Continent
Canada               9984670  0.913   America
France                640679  0.888    Europe
Germany               357114  0.916    Europe
Italy                 301336  0.873    Europe
Japan                 377930  0.891      Asia
United Kingdom        242495  0.907    Europe
United States        9525067  0.915   America

In [ ]:
df.drop(["Population","GDP"], axis=1)

                Surface Area    HDI Continent
Canada               9984670  0.913   America
France                640679  0.888    Europe
Germany               357114  0.916    Europe
Italy                 301336  0.873    Europe
Japan                 377930  0.891      Asia
United Kingdom        242495  0.907    Europe
United States        9525067  0.915   America

In [ ]:
df.drop(["Canada","France"], axis=0)

                Population       GDP  Surface Area    HDI Continent
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df[["Population","GDP"]]

                Population       GDP
Canada              35.467   1785387
France              63.951   2833687
Germany             80.940   3874437
Italy               60.665   2167744
Japan              127.061   4602367
United Kingdom      64.511   2950039
United States      318.523  17348075

In [ ]:
df["Population","GDP"]

KeyError: ignored

In [ ]:
df["Population"]

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [ ]:
# perbedaan [[]] dan []

# kalau [[]] itu mengambil data menjadi dataframe [] mengambil data menjadi series

In [ ]:
df[["Population","GDP"]] / 100

                Population        GDP
Canada             0.35467   17853.87
France             0.63951   28336.87
Germany            0.80940   38744.37
Italy              0.60665   21677.44
Japan              1.27061   46023.67
United Kingdom     0.64511   29500.39
United States      3.18523  173480.75

In [ ]:
df[["Population","GDP"]] * 10

                Population        GDP
Canada              354.67   17853870
France              639.51   28336870
Germany             809.40   38744370
Italy               606.65   21677440
Japan              1270.61   46023670
United Kingdom      645.11   29500390
United States      3185.23  173480750

In [ ]:
crisis = pd.Series([1000000, 0.3], index=['GDP', 'HDI'])
crisis

GDP    1000000.0
HDI          0.3
dtype: float64

In [ ]:
df[['GDP', 'HDI']]

                     GDP    HDI
Canada           1785387  0.913
France           2833687  0.888
Germany          3874437  0.916
Italy            2167744  0.873
Japan            4602367  0.891
United Kingdom   2950039  0.907
United States   17348075  0.915

In [ ]:
df[['GDP', 'HDI']] + crisis

                       GDP    HDI
Canada           2785387.0  1.213
France           3833687.0  1.188
Germany          4874437.0  1.216
Italy            3167744.0  1.173
Japan            5602367.0  1.191
United Kingdom   3950039.0  1.207
United States   18348075.0  1.215

Pandas mengenali kesamaan antara label indeks 'GDP' pada Series crisis dan nama kolom 'GDP' pada DataFrame df, dan juga kesamaan antara label indeks 'HDI' pada Series crisis dan nama kolom 'HDI' pada DataFrame df. Oleh karena itu, Pandas akan secara otomatis melakukan operasi penambahan pada pasangan yang sesuai.

In [ ]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [1785387, 2833687, 3874437, 2167744, 4602367, 2950039, 17348075],
    'Surface Area': [9984670, 640679, 357114, 301336, 377930, 242495, 9525067],
    'HDI': [0.913, 0.888, 0.916, 0.873, 0.891, 0.907,0.915],
    'Continent': ['America','Europe','Europe','Europe','Asia','Europe','America']
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'],
index=['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom', 'United States'])

In [ ]:
langs = pd.Series(
    ['French', 'German', 'Italian'],
    index=['France', 'Germany', 'Italy'],
    name='Language'
)

langs

France      French
Germany     German
Italy      Italian
Name: Language, dtype: object

In [ ]:
df["Language"] = langs

In [ ]:
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

In [ ]:
df = pd.DataFrame({
    'Panjang': [18, 12, 6, 9, 11],
    'Lebar': [3, 2, 2, 4, 5],
}, index=['Persegi I', 'Persegi II', 'Persegi III', 'Persegi IV', 'Persegi V'])

df

             Panjang  Lebar
Persegi I         18      3
Persegi II        12      2
Persegi III        6      2
Persegi IV         9      4
Persegi V         11      5

In [ ]:
df['Luas'] = df['Panjang'] * df['Lebar']

df

             Panjang  Lebar  Luas
Persegi I         18      3    54
Persegi II        12      2    24
Persegi III        6      2    12
Persegi IV         9      4    36
Persegi V         11      5    55

In [ ]:
df["Language"] = "English"

df

             Panjang  Lebar  Luas Language
Persegi I         18      3    54  English
Persegi II        12      2    24  English
Persegi III        6      2    12  English
Persegi IV         9      4    36  English
Persegi V         11      5    55  English

In [ ]:
df

                Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [ ]:
df = df.rename(
    columns={
        "HDI" : "Human resource"
    }
)

df = df.rename(
    index={
        "Canada" : "Indonesia"
    }
)

df

                Population       GDP  Surface Area  Human resource Continent
Indonesia           35.467   1785387       9984670           0.913   America
France              63.951   2833687        640679           0.888    Europe
Germany             80.940   3874437        357114           0.916    Europe
Italy               60.665   2167744        301336           0.873    Europe
Japan              127.061   4602367        377930           0.891      Asia
United Kingdom      64.511   2950039        242495           0.907    Europe
United States      318.523  17348075       9525067           0.915   America

In [ ]:
df.rename(
    columns={
        "GDP" : "Coba"
    }
)

                Population      Coba  Surface Area  Human resource Continent
Indonesia           35.467   1785387       9984670           0.913   America
France              63.951   2833687        640679           0.888    Europe
Germany             80.940   3874437        357114           0.916    Europe
Italy               60.665   2167744        301336           0.873    Europe
Japan              127.061   4602367        377930           0.891      Asia
United Kingdom      64.511   2950039        242495           0.907    Europe
United States      318.523  17348075       9525067           0.915   America

In [ ]:
df

                Population       GDP  Surface Area  Human resource Continent
Indonesia           35.467   1785387       9984670           0.913   America
France              63.951   2833687        640679           0.888    Europe
Germany             80.940   3874437        357114           0.916    Europe
Italy               60.665   2167744        301336           0.873    Europe
Japan              127.061   4602367        377930           0.891      Asia
United Kingdom      64.511   2950039        242495           0.907    Europe
United States      318.523  17348075       9525067           0.915   America

In [3]:
# assignment

import pandas as pd

df = pd.DataFrame({
    "Athlete" : ["Michael phelps","Michael phelps","Michael phelps","Natalie Coughlin","Aleksey Nemov"],
    "Age" : [23,19,27,25,24],
    "Country" : ["United States", "Canada", "United States", "Norway", "China"],
    "Year" : [2008, 2004, 2012,2008,2000],
    "Gold medals" : [8,6,4,1,2]
})

df

            Athlete  Age        Country  Year  Gold medals
0    Michael phelps   23  United States  2008            8
1    Michael phelps   19         Canada  2004            6
2    Michael phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleksey Nemov   24          China  2000            2

In [4]:
# assignment 1

united_states = df[(df["Country"] == "United States")]

united_states[["Athlete"]]

          Athlete
0  Michael phelps
2  Michael phelps

In [5]:
# assignment 2

tahun = df[(df["Year"] == 2008)]

tahun[["Athlete"]]

            Athlete
0    Michael phelps
3  Natalie Coughlin

In [6]:
# assignment 3

hapus = df[(df["Age"] >= 25) & (df["Country"] == "Norway")]

filter = hapus['Athlete']

for key, value in filter.items():
  df = df.drop([key], axis = "index")

df

          Athlete  Age        Country  Year  Gold medals
0  Michael phelps   23  United States  2008            8
1  Michael phelps   19         Canada  2004            6
2  Michael phelps   27  United States  2012            4
4   Aleksey Nemov   24          China  2000            2

In [7]:
# assignment 4

df['Silver Medals'] = [0, 0, 2, 1]

df

          Athlete  Age        Country  Year  Gold medals  Silver Medals
0  Michael phelps   23  United States  2008            8              0
1  Michael phelps   19         Canada  2004            6              0
2  Michael phelps   27  United States  2012            4              2
4   Aleksey Nemov   24          China  2000            2              1

In [8]:
df['Bronze Medals'] = [0, 2, 0, 3]

df

,Athlete,Age,Country,Year,Gold medals,Silver Medals,Bronze Medals
0,Michael phelps,23,United States,2008,8,0,0
1,Michael phelps,19,Canada,2004,6,0,2
2,Michael phelps,27,United States,2012,4,2,0
4,Aleksey Nemov,24,China,2000,2,1,3