In [ ]:
import pandas as pd
population = [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523]
df = pd.DataFrame(population)
df

         0
0   35.467
1   63.951
2   80.940
3   60.665
4  127.061
5   64.511
6  318.523

In [ ]:
import pandas as pd
data = [
    [35.467, 17348075],
    [63.951, 1785387],
    [80.94, 2833687],
    [60.665, 3874437],
    [127.061, 2167744],
    [64.511, 4602367],
    [318.523, 2950039]
]
df = pd.DataFrame(data)
df

         0         1
0   35.467  17348075
1   63.951   1785387
2   80.940   2833687
3   60.665   3874437
4  127.061   2167744
5   64.511   4602367
6  318.523   2950039

In [ ]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
})

df

   Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [ ]:
data = {
    "contoh" : [1,2],
    "coba" : [2,2]
}

data2 = [1,2,3,4]

coba = pd.DataFrame(data)
coba2 = pd.DataFrame(data2, index = ['a','b','c','d'] ,columns = ["contoh"])

coba2

   contoh
a       1
b       2
c       3
d       4

In [ ]:
coba

   contoh  coba
0       1     2
1       2     2

In [ ]:
coba.columns = ['dia', 'aku']

coba

     dia  aku
aku    1    2
dia    2    2

In [ ]:
simpan = coba[["aku"]]
simpan

     aku
aku    2
dia    2

In [ ]:
coba.loc["aku"]

dia    1
aku    2
Name: aku, dtype: int64

In [ ]:
coba.iloc[0]

dia    1
aku    2
Name: aku, dtype: int64

In [ ]:
data = {
    "population" : [100,200,300],
    "GDP" : [121,1211,122]
}

data_frame = pd.DataFrame(data, index = ["coba", "coba2", "coba3"])

data_frame.columns

Index(['population', 'GDP'], dtype='object')

In [ ]:
data_frame

       population   GDP
coba          100   121
coba2         200  1211
coba3         300   122

In [ ]:
data_frame[["population"]]

       population
coba          100
coba2         200
coba3         300

In [ ]:
data_frame.loc["coba":"coba3", "population"]

coba     100
coba2    200
coba3    300
Name: population, dtype: int64

In [ ]:
data_frame.iloc[0]

population    100
GDP           121
Name: coba, dtype: int64

In [ ]:
data_frame.iloc[-2]

population     200
GDP           1211
Name: coba2, dtype: int64

In [ ]:
# assignment

data = {
    "Athlete" : ["michael phelps", "michael phelps", "michael phelps", "natalle", "aleksey"],
    "Age" : [23,19,27,25,24],
    "Country" : ["united states", "canada", "united states", "norway", "china"],
    "Year" : [2008,2004,2012,2008,2000],
    "Gold Medals" : [8,6,4,1,2]
}

frame = pd.DataFrame(data)

frame.loc[0:,"Athlete" : "Gold Medals"]

          Athlete  Age        Country  Year  Gold Medals
0  michael phelps   23  united states  2008            8
1  michael phelps   19         canada  2004            6
2  michael phelps   27  united states  2012            4
3         natalle   25         norway  2008            1
4         aleksey   24          china  2000            2

In [ ]:
frame.loc[0:,"Athlete" : "Country"]

          Athlete  Age        Country
0  michael phelps   23  united states
1  michael phelps   19         canada
2  michael phelps   27  united states
3         natalle   25         norway
4         aleksey   24          china

In [ ]:
frame.loc[0:2]

          Athlete  Age        Country  Year  Gold Medals
0  michael phelps   23  united states  2008            8
1  michael phelps   19         canada  2004            6
2  michael phelps   27  united states  2012            4