In [1]:
import pandas as pd

data = [1500, 1250, 2224, 1302, 4239]
series = pd.Series(data, index=["a", "b", "c", "d", "e"])

series

a    1500
b    1250
c    2224
d    1302
e    4239
dtype: int64

In [3]:
series > 2000

a    False
b    False
c     True
d    False
e     True
dtype: bool

In [4]:
series[series > 2000]

c    2224
e    4239
dtype: int64

In [5]:
series[series > series.mean()]

c    2224
e    4239
dtype: int64

In [7]:
hasil = series[(series > 1400) & (series < 4000)]
print(hasil)

a    1500
c    2224
dtype: int64

In [9]:
contoh = series + 10
contoh

a    1510
b    1260
c    2234
d    1312
e    4249
dtype: int64

In [11]:
data1 = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
data2 = pd.Series([1,2,3,4,5], index = ['f','g','h','i','j'])

total = data1.add(data2, fill_value = 0)
total

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    1.0
g    2.0
h    3.0
i    4.0
j    5.0
dtype: float64

In [15]:
data1 = pd.DataFrame([1,2,3,4,5], index = ['a','b','c','d','e'])
data2 = pd.DataFrame([1,2,3,4,5], index = ['a','b','c','d','e'])

total = data1.add(data2, fill_value = 0)
total

    0
a   2
b   4
c   6
d   8
e  10

In [20]:
data1 = pd.DataFrame([1,2,3,4,5], index = ['a','b','c','d','e'])
data2 = pd.DataFrame([1,2,3,4,5], index = ['a','b','c','d','e'])

total = data1.div(data2, fill_value = 0)
total

     0
a  1.0
b  1.0
c  1.0
d  1.0
e  1.0

In [24]:
tambah = data1.mean()
tambah

0    3.0
dtype: float64

In [29]:
before = data1.dtypes
print(before)
after = data1.astype(str)
print(after.dtypes)

0    int64
dtype: object
0    object
dtype: object

AttributeError: ignored

In [51]:
import pandas as pd

data = [10, 20, 30, 40, 50]
df = pd.DataFrame(data)

# Mengonversi kolom 'Value' dalam DataFrame menjadi list
value_list = df[0].tolist()
print(value_list)

[10, 20, 30, 40, 50]

In [58]:
# df.loc[2] = 10

df.loc[0:, 0] = df.loc[0:, 0].replace(10,30)

df

    0
0  30
1  30
2  30
3  40
4  50