In [2]:
from google.colab import files
import pandas as pd
import numpy as np

uploaded = files.upload()

Saving bali_tourist.csv to bali_tourist (1).csv

In [3]:
data = pd.read_csv("bali_tourist.csv")

data

,year,area,country,January,February,March,April,May,June,July,August,September,October,November,December
0,2019,ASIA PACIFIC,AUSTRALIAN,95536,67474,83002,90265.0,98625,110815,123293,118556,124416,119382,105312,110711
1,2019,ASIA PACIFIC,BHUTAN,60,30,47,38.0,31,31,46,67,43,32,56,60
2,2019,ASIA PACIFIC,BANGLADESH,2262,2094,2489,2264.0,1938,4265,2656,2307,2035,2371,2164,2671
3,2019,ASIA PACIFIC,FIJI,91,73,72,77.0,42,62,2656,80,68,78,89,189
4,2019,ASIA PACIFIC,HONGKONG,1313,1367,764,6.0,1,5,2,1,0,11,0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2018,MIDDLE EAST,TURKEY,899,615,750,960.0,712,909,1306,1630,979,707,514,521
358,2018,MIDDLE EAST,UNITED ARAB EMIRATES,170,132,266,264.0,111,293,375,306,164,151,147,201
359,2018,MIDDLE EAST,YAMAN,98,49,76,55.0,23,62,40,52,67,37,60,85
360,2018,MIDDLE EAST,JORDAN,225,153,236,352.0,150,260,389,448,283,255,218,254
361,2018,OTHER NATIONALITIES,OTHER NATIONALITIES,6952,1704,1771,2484.0,2167,3711,2054,1269,1762,2604,3298,673

In [4]:
data_2018 = data[data['year'] == 2018]
data_2019 = data[data['year'] == 2019]

In [5]:
data_2018

,year,area,country,January,February,March,April,May,June,July,August,September,October,November,December
182,2018,ASIA PACIFIC,AUSTRALIAN,86658,70946,89466,91007.0,101840,104960,114590,104010,110792,105895,87344,103575
183,2018,ASIA PACIFIC,BHUTAN,20,20,22,25.0,13,13,26,21,25,26,28,44
184,2018,ASIA PACIFIC,BANGLADESH,3153,2067,2805,2554.0,1286,3166,1555,2226,1719,2116,1897,3500
185,2018,ASIA PACIFIC,FIJI,48,57,50,44.0,51,42,56,101,67,87,56,129
186,2018,ASIA PACIFIC,HONGKONG,1679,2721,3483,3432.0,4171,4356,4160,3202,3584,3360,2636,2075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2018,MIDDLE EAST,TURKEY,899,615,750,960.0,712,909,1306,1630,979,707,514,521
358,2018,MIDDLE EAST,UNITED ARAB EMIRATES,170,132,266,264.0,111,293,375,306,164,151,147,201
359,2018,MIDDLE EAST,YAMAN,98,49,76,55.0,23,62,40,52,67,37,60,85
360,2018,MIDDLE EAST,JORDAN,225,153,236,352.0,150,260,389,448,283,255,218,254
361,2018,OTHER NATIONALITIES,OTHER NATIONALITIES,6952,1704,1771,2484.0,2167,3711,2054,1269,1762,2604,3298,673

In [6]:
data_2019

,year,area,country,January,February,March,April,May,June,July,August,September,October,November,December
0,2019,ASIA PACIFIC,AUSTRALIAN,95536,67474,83002,90265.0,98625,110815,123293,118556,124416,119382,105312,110711
1,2019,ASIA PACIFIC,BHUTAN,60,30,47,38.0,31,31,46,67,43,32,56,60
2,2019,ASIA PACIFIC,BANGLADESH,2262,2094,2489,2264.0,1938,4265,2656,2307,2035,2371,2164,2671
3,2019,ASIA PACIFIC,FIJI,91,73,72,77.0,42,62,2656,80,68,78,89,189
4,2019,ASIA PACIFIC,HONGKONG,1313,1367,764,6.0,1,5,2,1,0,11,0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,2019,MIDDLE EAST,TURKEY,688,529,629,800.0,638,1299,1069,1016,933,1380,1617,1268
178,2019,MIDDLE EAST,UNITED ARAB EMIRATES,181,141,229,239.0,65,438,322,433,203,147,340,297
179,2019,MIDDLE EAST,YAMAN,77,75,81,58.0,18,93,76,95,79,68,82,94
180,2019,MIDDLE EAST,JORDAN,238,155,254,290.0,97,452,484,564,312,248,322,333
181,2019,OTHER NATIONALITIES,OTHER NATIONALITIES,2927,196,1370,2215.0,139,3649,2230,2648,7262,7502,4997,3119

In [10]:
kolom = ['January','February','March','April','May','June','July','August','September','October','November','December']
total_2018 = data_2018[kolom].sum()
total_2019 = data_2019[kolom].sum()

total_kedatangan_2018 = total_2018.sum()
total_kedatangan_2019 = total_2019.sum()

print("total 2018 =", total_kedatangan_2018)
print("total 2019 =", total_kedatangan_2019)

total 2018 = 6073353.0
total 2019 = 6275045.0

In [14]:
rata_2018 = total_2018.mean()
rata_2019 = total_2019.mean()

print(rata_2018)
print(rata_2019)

506112.75
522920.4166666667

In [20]:
max = total_2018.max()

for key, value in total_2018.items():
  if max == value:
    print(key)

July

In [21]:
min = total_2018.min()

for key, value in total_2018.items():
  if min == value:
    print(key)

January

In [22]:
area_2018 = data_2018[['area', 'country']]

area_2018

                    area               country
182        ASIA PACIFIC             AUSTRALIAN
183        ASIA PACIFIC                 BHUTAN
184        ASIA PACIFIC             BANGLADESH
185        ASIA PACIFIC                   FIJI
186        ASIA PACIFIC               HONGKONG
..                   ...                   ...
357          MIDDLE EAST                TURKEY
358          MIDDLE EAST  UNITED ARAB EMIRATES
359          MIDDLE EAST                 YAMAN
360          MIDDLE EAST                JORDAN
361  OTHER NATIONALITIES   OTHER NATIONALITIES

[180 rows x 2 columns]