In [51]:
import pandas as pd
import pandas as pd
import warnings

df = pd.read_excel("penumpang transjakarta desember 2021.xlsx")
df

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang;;;;;;;,Unnamed: 6
0,2021,12.0,Mikrotrans,JAK.88,TerminalTanjung Priok - Ancol Barat,43967;;;;;;;,NaN
1,2021,12.0,Mikrotrans,JAK.85,Bintara - Cipinang Indah,40103;;;;;;;,NaN
2,2021,12.0,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,59193;;;;;;;,NaN
3,2021,12.0,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,70475;;;;;;;,NaN
4,2021,12.0,Mikrotrans,JAK.77,Tanjung Priok - Jembatan Item,77697;;;;;;;,NaN
...,...,...,...,...,...,...,...
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,pimpinan,NaN,total,karyawan,alamat,jumlah,NaN
128,agung,NaN,1.000.000,bagus,denpasar,1000,NaN
129,wahyu,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df2 = pd.read_csv("penumpang transjakarta november 2021.csv")
df2

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
0,2021,11,Mikrotrans,JAK.88,Terminal Tanjung Priok - Ancol Barat,40135
1,2021,11,Mikrotrans,JAK.85,Bintara - Cipinang Indah,38487
2,2021,11,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,49142
3,2021,11,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,66701
4,2021,11,Mikrotrans,JA.77,Tanjung Priok - Jembatan Item,75248
...,...,...,...,...,...,...
124,2021,11,Angkutan Umum Integrasi,11Q,Kampung Melayu - Pulo Gebang via BKT,11353
125,2021,11,Angkutan Umum Integrasi,11D,Pulo Gebang - Pulo Gadung 2 via PIK,59155
126,2021,11,Angkutan Umum Integrasi,10K,Tanjung Priok - Senen via Taman BMW,34498
127,2021,11,Angkutan Umum Integrasi,GR4,Taman Kota Intan - Museum Bahari,4
128,2021,11,Angkutan Umum Integrasi,GR5,Kota Tua Explorer,3

In [52]:
# Hapus kolom dengan nama "Unnamed" pada data 1

df = df.drop(columns=[col for col in df.columns if 'Unnamed' in col])

df

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang;;;;;;;
0,2021,12.0,Mikrotrans,JAK.88,TerminalTanjung Priok - Ancol Barat,43967;;;;;;;
1,2021,12.0,Mikrotrans,JAK.85,Bintara - Cipinang Indah,40103;;;;;;;
2,2021,12.0,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,59193;;;;;;;
3,2021,12.0,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,70475;;;;;;;
4,2021,12.0,Mikrotrans,JAK.77,Tanjung Priok - Jembatan Item,77697;;;;;;;
...,...,...,...,...,...,...
125,NaN,NaN,NaN,NaN,NaN,NaN
126,NaN,NaN,NaN,NaN,NaN,NaN
127,pimpinan,NaN,total,karyawan,alamat,jumlah
128,agung,NaN,1.000.000,bagus,denpasar,1000
129,wahyu,NaN,NaN,NaN,NaN,NaN

In [53]:
# Menemukan indeks baris "pimpinan"

idx_pimpinan = df[df["tahun"] == "pimpinan"].index[0]

# Menghapus baris pimipnan

df.drop(idx_pimpinan, inplace=True)

# df.drop(df.index[idx_pimpinan:], inplace=True) # Menghapus baris dari indeks "pimpinan" ke bawah

df

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang;;;;;;;
0,2021,12.0,Mikrotrans,JAK.88,TerminalTanjung Priok - Ancol Barat,43967;;;;;;;
1,2021,12.0,Mikrotrans,JAK.85,Bintara - Cipinang Indah,40103;;;;;;;
2,2021,12.0,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,59193;;;;;;;
3,2021,12.0,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,70475;;;;;;;
4,2021,12.0,Mikrotrans,JAK.77,Tanjung Priok - Jembatan Item,77697;;;;;;;
...,...,...,...,...,...,...
124,==============================================...,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN
126,NaN,NaN,NaN,NaN,NaN,NaN
128,agung,NaN,1.000.000,bagus,denpasar,1000
129,wahyu,NaN,NaN,NaN,NaN,NaN

In [54]:
# Membersihkan data dengan menghapus karakter ';;;;' pada penamaan kolom 'jumlah_penumpang'

df.columns = df.columns.str.replace(';', '')

# tampilkan data

df

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
0,2021,12.0,Mikrotrans,JAK.88,TerminalTanjung Priok - Ancol Barat,43967;;;;;;;
1,2021,12.0,Mikrotrans,JAK.85,Bintara - Cipinang Indah,40103;;;;;;;
2,2021,12.0,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,59193;;;;;;;
3,2021,12.0,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,70475;;;;;;;
4,2021,12.0,Mikrotrans,JAK.77,Tanjung Priok - Jembatan Item,77697;;;;;;;
...,...,...,...,...,...,...
124,==============================================...,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN
126,NaN,NaN,NaN,NaN,NaN,NaN
128,agung,NaN,1.000.000,bagus,denpasar,1000
129,wahyu,NaN,NaN,NaN,NaN,NaN

In [55]:
# Membersihkan data dengan menghapus baris yang kosong

df = df.dropna()

df

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
0,2021,12.0,Mikrotrans,JAK.88,TerminalTanjung Priok - Ancol Barat,43967;;;;;;;
1,2021,12.0,Mikrotrans,JAK.85,Bintara - Cipinang Indah,40103;;;;;;;
2,2021,12.0,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,59193;;;;;;;
3,2021,12.0,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,70475;;;;;;;
4,2021,12.0,Mikrotrans,JAK.77,Tanjung Priok - Jembatan Item,77697;;;;;;;
...,...,...,...,...,...,...
119,2021,12.0,Angkutan Umum Integrasi,1B,Stasiun Palmerah - Tosari,0;;;;;;;
120,2021,12.0,Angkutan Umum Integrasi,1A,PIK - Balai Kota,0;;;;;;;
121,2021,12.0,Angkutan Umum Integrasi,12B,Pluit - Senen,0;;;;;;;
122,2021,12.0,Angkutan Umum Integrasi,11Q,Kampung Melayu - Pulo Gebang via BKT,0;;;;;;;
123,2021,12.0,Angkutan Umum Integrasi,11D,Pulo Gebang - Pulo Gadung 2 via PIK,0;;;;;;;

In [56]:
# Menggunakan apply untuk mengubah setiap kolom menjadi string dan menghilangkan tanda ;
df = df.apply(lambda x: x.astype(str).apply(lambda y: y.replace(';', '')))

# Tampilkan data
df

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
0,2021,12.0,Mikrotrans,JAK.88,TerminalTanjung Priok - Ancol Barat,43967
1,2021,12.0,Mikrotrans,JAK.85,Bintara - Cipinang Indah,40103
2,2021,12.0,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,59193
3,2021,12.0,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,70475
4,2021,12.0,Mikrotrans,JAK.77,Tanjung Priok - Jembatan Item,77697
...,...,...,...,...,...,...
119,2021,12.0,Angkutan Umum Integrasi,1B,Stasiun Palmerah - Tosari,0
120,2021,12.0,Angkutan Umum Integrasi,1A,PIK - Balai Kota,0
121,2021,12.0,Angkutan Umum Integrasi,12B,Pluit - Senen,0
122,2021,12.0,Angkutan Umum Integrasi,11Q,Kampung Melayu - Pulo Gebang via BKT,0
123,2021,12.0,Angkutan Umum Integrasi,11D,Pulo Gebang - Pulo Gadung 2 via PIK,0

In [57]:
# Mengubah kolom 'jumlah_penumpang' menjadi float dengan mengubah yang tidak bisa menjadi NaN

df['jumlah_penumpang'] = pd.to_numeric(df['jumlah_penumpang'], errors='coerce')

# tampilkan data

df

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
0,2021,12.0,Mikrotrans,JAK.88,TerminalTanjung Priok - Ancol Barat,43967.0
1,2021,12.0,Mikrotrans,JAK.85,Bintara - Cipinang Indah,40103.0
2,2021,12.0,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,59193.0
3,2021,12.0,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,70475.0
4,2021,12.0,Mikrotrans,JAK.77,Tanjung Priok - Jembatan Item,77697.0
...,...,...,...,...,...,...
119,2021,12.0,Angkutan Umum Integrasi,1B,Stasiun Palmerah - Tosari,0.0
120,2021,12.0,Angkutan Umum Integrasi,1A,PIK - Balai Kota,0.0
121,2021,12.0,Angkutan Umum Integrasi,12B,Pluit - Senen,0.0
122,2021,12.0,Angkutan Umum Integrasi,11Q,Kampung Melayu - Pulo Gebang via BKT,0.0
123,2021,12.0,Angkutan Umum Integrasi,11D,Pulo Gebang - Pulo Gadung 2 via PIK,0.0

In [58]:
# hapus data jumlah_penumpang yang berisi NaN

df = df.dropna()

df

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
0,2021,12.0,Mikrotrans,JAK.88,TerminalTanjung Priok - Ancol Barat,43967.0
1,2021,12.0,Mikrotrans,JAK.85,Bintara - Cipinang Indah,40103.0
2,2021,12.0,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,59193.0
3,2021,12.0,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,70475.0
4,2021,12.0,Mikrotrans,JAK.77,Tanjung Priok - Jembatan Item,77697.0
...,...,...,...,...,...,...
119,2021,12.0,Angkutan Umum Integrasi,1B,Stasiun Palmerah - Tosari,0.0
120,2021,12.0,Angkutan Umum Integrasi,1A,PIK - Balai Kota,0.0
121,2021,12.0,Angkutan Umum Integrasi,12B,Pluit - Senen,0.0
122,2021,12.0,Angkutan Umum Integrasi,11Q,Kampung Melayu - Pulo Gebang via BKT,0.0
123,2021,12.0,Angkutan Umum Integrasi,11D,Pulo Gebang - Pulo Gadung 2 via PIK,0.0

In [59]:
import dataframe_image as dfi

dfi.export(df, "data_bersih.png", max_rows=-1)

In [63]:
#gabungkan data desember dan data november menggunakan concat

#ignore_index=True digunakan untuk mengatur ulang indeks setelah penggabungan, sehingga indeks tidak berulang.

df = pd.concat([df, df2], ignore_index=True)

df

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
0,2021,12.0,Mikrotrans,JAK.88,TerminalTanjung Priok - Ancol Barat,43967.0
1,2021,12.0,Mikrotrans,JAK.85,Bintara - Cipinang Indah,40103.0
2,2021,12.0,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,59193.0
3,2021,12.0,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,70475.0
4,2021,12.0,Mikrotrans,JAK.77,Tanjung Priok - Jembatan Item,77697.0
...,...,...,...,...,...,...
494,2021,11,Angkutan Umum Integrasi,11Q,Kampung Melayu - Pulo Gebang via BKT,11353.0
495,2021,11,Angkutan Umum Integrasi,11D,Pulo Gebang - Pulo Gadung 2 via PIK,59155.0
496,2021,11,Angkutan Umum Integrasi,10K,Tanjung Priok - Senen via Taman BMW,34498.0
497,2021,11,Angkutan Umum Integrasi,GR4,Taman Kota Intan - Museum Bahari,4.0
498,2021,11,Angkutan Umum Integrasi,GR5,Kota Tua Explorer,3.0

In [65]:
dfi.export(df, "data_final.png", max_rows=-1)

In [66]:
# final ubah data yang sudah dibersihkan dalam bentuk excel

df.to_excel('data_final.xlsx', index=False)