In [52]:
import pandas as pd 

covid = pd.read_csv("covid.csv", header=None) # header membuat kolom menjadi row yang pertama
covid = covid.drop(0) # hapus row index 0
covid.columns = ["Tanggal", "ODP", "PDP", "Kasus Positif", "Kasus Sembuh", "Kasus Meninggal"] # ubah kolom
covid

      Tanggal  ODP  PDP Kasus Positif Kasus Sembuh Kasus Meninggal
1   3/26/2020  204   89            17            0               4
2   3/27/2020  207   99            17            0               4
3   3/29/2020  256  119            28            0               4
4   3/30/2020  262  123            31            0               6
5   3/31/2020  308  134            34            2               6
6    4/1/2020  336  139            38            2               6
7    4/2/2020  371  156            40            2              10
8    4/5/2020  416  170            42            2              10
9    4/6/2020  450  184            43            2              11
10   4/8/2020  525  196            44            2              13
11  4/11/2020  600  230            47            2              15
12  4/12/2020  606  231            49            2              16
13  4/13/2020  630  239            50            3              16
14  4/14/2020  629  245            44            9              16

In [53]:
covid = covid.rename(columns={
    "Kasus Positif" : "Positif", 
    "Kasus Sembuh" : "Sembuh", 
    "Kasus Meninggal" : "Meninggal"})

covid

      Tanggal  ODP  PDP Positif Sembuh Meninggal
1   3/26/2020  204   89      17      0         4
2   3/27/2020  207   99      17      0         4
3   3/29/2020  256  119      28      0         4
4   3/30/2020  262  123      31      0         6
5   3/31/2020  308  134      34      2         6
6    4/1/2020  336  139      38      2         6
7    4/2/2020  371  156      40      2        10
8    4/5/2020  416  170      42      2        10
9    4/6/2020  450  184      43      2        11
10   4/8/2020  525  196      44      2        13
11  4/11/2020  600  230      47      2        15
12  4/12/2020  606  231      49      2        16
13  4/13/2020  630  239      50      3        16
14  4/14/2020  629  245      44      9        16

In [54]:
covid["Positif"] = covid["Positif"].replace({
    "17" : "100", 
    "28" : "1000"})

covid

      Tanggal  ODP  PDP Positif Sembuh Meninggal
1   3/26/2020  204   89     100      0         4
2   3/27/2020  207   99     100      0         4
3   3/29/2020  256  119    1000      0         4
4   3/30/2020  262  123      31      0         6
5   3/31/2020  308  134      34      2         6
6    4/1/2020  336  139      38      2         6
7    4/2/2020  371  156      40      2        10
8    4/5/2020  416  170      42      2        10
9    4/6/2020  450  184      43      2        11
10   4/8/2020  525  196      44      2        13
11  4/11/2020  600  230      47      2        15
12  4/12/2020  606  231      49      2        16
13  4/13/2020  630  239      50      3        16
14  4/14/2020  629  245      44      9        16

In [55]:
covid.shape

(14, 6)

In [56]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 1 to 14
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Tanggal    14 non-null     object
 1   ODP        14 non-null     object
 2   PDP        14 non-null     object
 3   Positif    14 non-null     object
 4   Sembuh     14 non-null     object
 5   Meninggal  14 non-null     object
dtypes: object(6)
memory usage: 804.0+ bytes

In [57]:
covid.head(7)

     Tanggal  ODP  PDP Positif Sembuh Meninggal
1  3/26/2020  204   89     100      0         4
2  3/27/2020  207   99     100      0         4
3  3/29/2020  256  119    1000      0         4
4  3/30/2020  262  123      31      0         6
5  3/31/2020  308  134      34      2         6
6   4/1/2020  336  139      38      2         6
7   4/2/2020  371  156      40      2        10

In [58]:
covid.tail(7)

      Tanggal  ODP  PDP Positif Sembuh Meninggal
8    4/5/2020  416  170      42      2        10
9    4/6/2020  450  184      43      2        11
10   4/8/2020  525  196      44      2        13
11  4/11/2020  600  230      47      2        15
12  4/12/2020  606  231      49      2        16
13  4/13/2020  630  239      50      3        16
14  4/14/2020  629  245      44      9        16

DATA CLEANING

In [59]:
import numpy as np

data = pd.DataFrame({
    "I" : [100, 90, np.nan, 95],
    "II" : [30, 45, 56, np.nan],
    "III" : [np.nan, 40, 80, 98]
})

data

       I    II   III
0  100.0  30.0   NaN
1   90.0  45.0  40.0
2    NaN  56.0  80.0
3   95.0   NaN  98.0

In [60]:
data.isnull().sum()

I      1
II     1
III    1
dtype: int64

In [66]:
data = data.fillna(data.mean())
data

       I         II        III
0  100.0  30.000000  72.666667
1   90.0  45.000000  40.000000
2   95.0  56.000000  80.000000
3   95.0  43.666667  98.000000

In [62]:
data = pd.DataFrame({
    "I" : [100, 90, np.nan, 95],
    "II" : [30, 45, 56, np.nan],
    "III" : [np.nan, 40, 80, 98]
})

data

       I    II   III
0  100.0  30.0   NaN
1   90.0  45.0  40.0
2    NaN  56.0  80.0
3   95.0   NaN  98.0

In [63]:
data.dropna() # default axis = 0

      I    II   III
1  90.0  45.0  40.0

In [64]:
data.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [70]:
data

       I         II        III
0  100.0  30.000000  72.666667
1   90.0  45.000000  40.000000
2   95.0  56.000000  80.000000
3   95.0  43.666667  98.000000

In [69]:
data.sum(axis = 0)

I      380.000000
II     174.666667
III    290.666667
dtype: float64

In [71]:
data.sum(axis = 1)

0    202.666667
1    175.000000
2    231.000000
3    236.666667
dtype: float64

In [74]:
gender = pd.DataFrame({
    "Sex" : ["M", "F", "F", "M"],
    "Age" : [29, 30, 24, 70]
})

gender

  Sex  Age
0   M   29
1   F   30
2   F   24
3   M   70

In [75]:
gender["Sex"].unique()

array(['M', 'F'], dtype=object)

In [76]:
gender["Sex"].value_counts()

Sex
M    2
F    2
Name: count, dtype: int64