Hello world

In [1]:
print("hello world")

hello world

PANDAS

- Data series ( data yang tidak memiliki kolom )
- Data dataframe ( data yang memiliki kolom )

Deklarasi series

In [2]:
import pandas as pd 

# data series 

data = [10,20,30,40]

series1 = pd.Series(data)
series2 = pd.Series([100,200,300,400])
series3 = pd.Series([80,90,70,60], index = ["satu", "dua", "tiga", "empat"])
series4 = pd.Series({"data1" : 40, 
                     "data2" : 50, 
                     "data3" : 60})

print(series1)
print(series2)
print(series3)
print(series4)

0    10
1    20
2    30
3    40
dtype: int64
0    100
1    200
2    300
3    400
dtype: int64
satu     80
dua      90
tiga     70
empat    60
dtype: int64
data1    40
data2    50
data3    60
dtype: int64

Mengakses series

In [3]:
print(series2)
print(series2[0])
print(series2[0 : 3]) # (start : batas) // slicing

0    100
1    200
2    300
3    400
dtype: int64
100
0    100
1    200
2    300
dtype: int64

In [4]:
print(series3)
print(series3["satu"])
print(series3["satu" : "dua"]) # slicing 
print(series3.loc["satu" : "dua"]) # loc -- batasnya ikut
print(series3.iloc[0 : 3]) # iloc -- batasnya tidak ikut

satu     80
dua      90
tiga     70
empat    60
dtype: int64
80
satu    80
dua     90
dtype: int64
satu    80
dua     90
dtype: int64
satu    80
dua     90
tiga    70
dtype: int64

Conditional series

In [5]:
data = pd.Series([1500, 1250, 2000, 3000, 4000])
print(data)
print(data > 1500)
print(data[data > 1500])
print(data[(data > 1500) & (data < 4000)])

0    1500
1    1250
2    2000
3    3000
4    4000
dtype: int64
0    False
1    False
2     True
3     True
4     True
dtype: bool
2    2000
3    3000
4    4000
dtype: int64
2    2000
3    3000
dtype: int64

In [6]:
hasil = data[data > 1500]
hasil = hasil + 100
hasil

2    2100
3    3100
4    4100
dtype: int64

In [7]:
rata = data.mean()
total = data.sum()
print(rata)
print(total)
print(data[data > rata])

2350.0
11750
3    3000
4    4000
dtype: int64

In [8]:
data1 = pd.Series([100,200,300,400])
print(data1)

data1 = data1.astype(float) # astype mengganti tipe data
print(data1)

0    100
1    200
2    300
3    400
dtype: int64
0    100.0
1    200.0
2    300.0
3    400.0
dtype: float64

Mengubah series

In [9]:
data3 = pd.Series([200,300,400])
print(data3)
data3[0] = 1000
print(data3)

0    200
1    300
2    400
dtype: int64
0    1000
1     300
2     400
dtype: int64

In [10]:
data3[data3 < 1000] = 600
print(data3)

0    1000
1     600
2     600
dtype: int64

Dataframe

In [11]:
data = [
    [10, 20],
    [30, 40],
    [50, 60]
]

df = pd.DataFrame(data)
df.columns = ["kolom 1", "kolom 2"]
df.index = ["satu", "dua", "tiga"]
df

      kolom 1  kolom 2
satu       10       20
dua        30       40
tiga       50       60

In [12]:
data = {
    "kolom 1" : [10, 20, 30, 100, 200],
    "kolom 2" : [20, 30, 90, 300, 400],
    "kolom 3" : [20, 20, 30, 20, 20],
    "kolom 4" : [20, 20, 30, 20, 20]
}

df = pd.DataFrame(data)
df

   kolom 1  kolom 2  kolom 3  kolom 4
0       10       20       20       20
1       20       30       20       20
2       30       90       30       30
3      100      300       20       20
4      200      400       20       20

In [13]:
df["kolom 1"]

0     10
1     20
2     30
3    100
4    200
Name: kolom 1, dtype: int64

In [14]:
df[["kolom 1", "kolom 2"]]

   kolom 1  kolom 2
0       10       20
1       20       30
2       30       90
3      100      300
4      200      400

In [15]:
df.index = ["satu", "dua", "tiga", "empat", "lima"]
df

       kolom 1  kolom 2  kolom 3  kolom 4
satu        10       20       20       20
dua         20       30       20       20
tiga        30       90       30       30
empat      100      300       20       20
lima       200      400       20       20

In [16]:
print(df.loc["satu"])
print(df.loc["satu" : "tiga"])
print(df.loc["satu" : "tiga", "kolom 1" : "kolom 2"]) # [row(start : batas), kolom(start : batas)]

kolom 1    10
kolom 2    20
kolom 3    20
kolom 4    20
Name: satu, dtype: int64
      kolom 1  kolom 2  kolom 3  kolom 4
satu       10       20       20       20
dua        20       30       20       20
tiga       30       90       30       30
      kolom 1  kolom 2
satu       10       20
dua        20       30
tiga       30       90

In [17]:
print(df.iloc[0])
print(df.iloc[0 : 3])
print(df.iloc[0 : 3, 0 : 2])

kolom 1    10
kolom 2    20
kolom 3    20
kolom 4    20
Name: satu, dtype: int64
      kolom 1  kolom 2  kolom 3  kolom 4
satu       10       20       20       20
dua        20       30       20       20
tiga       30       90       30       30
      kolom 1  kolom 2
satu       10       20
dua        20       30
tiga       30       90

In [18]:
df

       kolom 1  kolom 2  kolom 3  kolom 4
satu        10       20       20       20
dua         20       30       20       20
tiga        30       90       30       30
empat      100      300       20       20
lima       200      400       20       20

In [19]:
df["kolom 1"] > 30

satu     False
dua      False
tiga     False
empat     True
lima      True
Name: kolom 1, dtype: bool

In [20]:
df[df["kolom 1"] > 30]

       kolom 1  kolom 2  kolom 3  kolom 4
empat      100      300       20       20
lima       200      400       20       20

In [21]:
df.loc[df["kolom 1"] > 30, "kolom 1" : "kolom 2"]

       kolom 1  kolom 2
empat      100      300
lima       200      400

In [22]:
df

       kolom 1  kolom 2  kolom 3  kolom 4
satu        10       20       20       20
dua         20       30       20       20
tiga        30       90       30       30
empat      100      300       20       20
lima       200      400       20       20

In [23]:
df = df.drop(["empat", "lima"])
df

      kolom 1  kolom 2  kolom 3  kolom 4
satu       10       20       20       20
dua        20       30       20       20
tiga       30       90       30       30

In [24]:
df = df.drop(columns=["kolom 3", "kolom 4"])
df

      kolom 1  kolom 2
satu       10       20
dua        20       30
tiga       30       90

In [25]:
df["tambah 1"] = [20, 20, 20]
df["tambah 2"] = df["kolom 1"] + df["kolom 2"]
df

      kolom 1  kolom 2  tambah 1  tambah 2
satu       10       20        20        30
dua        20       30        20        50
tiga       30       90        20       120

In [27]:
data_atlet = {
    "Athlete" : ["Michael Phelps", "Michael Phelps", "Michael Pelps", "Natalie Coughlin", "Aleksey Nemov"],
    "Age" : [23, 19, 27, 25, 24],
    "Country" : ["United States", "Canada", "United States", "Norway", "China"],
    "Year" : [2008, 2004, 2012, 2008, 2000],
    "Gold Medals" : [8, 6, 4, 1, 2]
}

df = pd.DataFrame(data_atlet)
df[["Athlete", "Age", "Country", "Year", "Gold Medals"]]

            Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2     Michael Pelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleksey Nemov   24          China  2000            2

In [33]:
norway = df.loc[(df["Age"] == 25) & (df["Country"] == "Norway")]
norway

            Athlete  Age Country  Year  Gold Medals
3  Natalie Coughlin   25  Norway  2008            1

In [34]:
df = df.drop(norway.index)
df

          Athlete  Age        Country  Year  Gold Medals
0  Michael Phelps   23  United States  2008            8
1  Michael Phelps   19         Canada  2004            6
2   Michael Pelps   27  United States  2012            4
4   Aleksey Nemov   24          China  2000            2