In [56]:
import pandas as pd 

data = {
    "GDP" : [100,200,300,400],
    "Population" : [1000,2000,3000,4000],
    "HDI" : [10,20,30,40],
    "Surface" : [20,30,40,50]
}

df = pd.DataFrame(data)
df

   GDP  Population  HDI  Surface
0  100        1000   10       20
1  200        2000   20       30
2  300        3000   30       40
3  400        4000   40       50

In [57]:
df[df["Population"] > 2000]

   GDP  Population  HDI  Surface
2  300        3000   30       40
3  400        4000   40       50

In [58]:
df.loc[df["Population"] > 2000]

   GDP  Population  HDI  Surface
2  300        3000   30       40
3  400        4000   40       50

In [59]:
df.loc[(df["Population"] > 1000) & (df["Population"] < 4000)]

   GDP  Population  HDI  Surface
1  200        2000   20       30
2  300        3000   30       40

In [60]:
df.loc[df["Population"] > 2000, ["Population", "HDI"]]

   Population  HDI
2        3000   30
3        4000   40

In [61]:
df.index = ["satu", "dua", "tiga", "empat"]
df

       GDP  Population  HDI  Surface
satu   100        1000   10       20
dua    200        2000   20       30
tiga   300        3000   30       40
empat  400        4000   40       50

In [62]:
df = df.drop(["satu", "dua"])
df

       GDP  Population  HDI  Surface
tiga   300        3000   30       40
empat  400        4000   40       50

In [63]:
df = df.drop(columns=["GDP", "Population"])
df

       HDI  Surface
tiga    30       40
empat   40       50

In [64]:
df

       HDI  Surface
tiga    30       40
empat   40       50

In [65]:
print(df.sum(axis = 0))
print(df.sum(axis = 1))

HDI        70
Surface    90
dtype: int64
tiga     70
empat    90
dtype: int64

In [66]:
data = {
    "GDP" : [100,200,300,400],
    "Population" : [1000,2000,3000,4000],
    "HDI" : [10,20,30,40],
    "Surface" : [20,30,40,50]
}

df = pd.DataFrame(data)
df

   GDP  Population  HDI  Surface
0  100        1000   10       20
1  200        2000   20       30
2  300        3000   30       40
3  400        4000   40       50

In [67]:
tambah = [30,90,40,60]

df["Index"] = tambah
df

   GDP  Population  HDI  Surface  Index
0  100        1000   10       20     30
1  200        2000   20       30     90
2  300        3000   30       40     40
3  400        4000   40       50     60

In [68]:
df["Total"] = df["HDI"] * df["Surface"]
df

   GDP  Population  HDI  Surface  Index  Total
0  100        1000   10       20     30    200
1  200        2000   20       30     90    600
2  300        3000   30       40     40   1200
3  400        4000   40       50     60   2000

In [69]:
df = df.rename(
    columns={
        "Population" : "Populasi",
        "Index" : "Harga"
    }
)

df

   GDP  Populasi  HDI  Surface  Harga  Total
0  100      1000   10       20     30    200
1  200      2000   20       30     90    600
2  300      3000   30       40     40   1200
3  400      4000   40       50     60   2000

In [74]:
df["GDP"] = df["GDP"].replace(400, 1000)
df["HDI"] = df["HDI"].replace([10,20], [100,200])
df

    GDP  Populasi  HDI  Surface  Harga  Total
0   100      1000  100       20     30    200
1   200      2000  200       30     90    600
2   300      3000   30       40     40   1200
3  1000      4000   40       50     60   2000

Assignment

In [75]:
data1 = {
    "Atlete" : ["Michael Phelps","Michael Phelps","Michael Phelps","Natalie Coughlin", "Alesksey Nemov"],
    "Age" : [23, 19, 27, 25, 24],
    "Country" : ["United States", "Canada", "United States", "Norway", "China"],
    "Year" : [2008,2004,2012,2008,2000],
    "Gold Medals" :[ 8,6,4,1,2]
}

df = pd.DataFrame(data1)
df

             Atlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4    Alesksey Nemov   24          China  2000            2

In [79]:
da = df.loc[(df["Year"] >= 25) & (df["Country"] == "Norway")]
df = df.drop(da.index) # ([3])
df

           Atlete  Age        Country  Year  Gold Medals
0  Michael Phelps   23  United States  2008            8
1  Michael Phelps   19         Canada  2004            6
2  Michael Phelps   27  United States  2012            4
4  Alesksey Nemov   24          China  2000            2