In [43]:
import pandas as pd

data = {
    "satu" : "dua",
    "tiga" : "empat"
}

series = pd.Series(data)
series

satu      dua
tiga    empat
dtype: object

In [44]:
data1 = [1,2,3,4]
data2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
data3 = {
    "populasi" : [10,20,30,40],
    "surface" : [90,80,70,60],
    "hdi" : [11,22,33,44]
}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

print(df1)
print(df2)
print(df3)

   0
0  1
1  2
2  3
3  4
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
   populasi  surface  hdi
0        10       90   11
1        20       80   22
2        30       70   33
3        40       60   44

In [51]:
df3.index = ["satu", "dua", "tiga", "empat"]
df3

       populasi  surface  hdi
satu         10       90   11
dua          20       80   22
tiga         30       70   33
empat        40       60   44

In [48]:
df3.index

Index(['satu', 'dua', 'tiga', 'empat'], dtype='object')

In [52]:
df3

       populasi  surface  hdi
satu         10       90   11
dua          20       80   22
tiga         30       70   33
empat        40       60   44

In [54]:
df3.loc["satu" : "tiga", "populasi" : "surface"]

      populasi  surface
satu        10       90
dua         20       80
tiga        30       70

In [56]:
df3.iloc[0:3, 0:2]

      populasi  surface
satu        10       90
dua         20       80
tiga        30       70

In [59]:
df3["populasi"]

satu     10
dua      20
tiga     30
empat    40
Name: populasi, dtype: int64

In [61]:
df3[["populasi", "surface"]]

       populasi  surface
satu         10       90
dua          20       80
tiga         30       70
empat        40       60