In [1]:
import pandas as pd 
import numpy as np 

dict = {
    "I" : [100, 90, np.nan, 95],
    "II" : [30,45,56, np.nan],
    "III" : [np.nan, 40, 80, 98]
}

df = pd.DataFrame(dict)
df

       I    II   III
0  100.0  30.0   NaN
1   90.0  45.0  40.0
2    NaN  56.0  80.0
3   95.0   NaN  98.0

In [4]:
df.isnull().sum()

I      1
II     1
III    1
dtype: int64

In [7]:
df.fillna(0)

       I    II   III
0  100.0  30.0   0.0
1   90.0  45.0  40.0
2    0.0  56.0  80.0
3   95.0   0.0  98.0

In [6]:
df.fillna(df.mean())

       I         II        III
0  100.0  30.000000  72.666667
1   90.0  45.000000  40.000000
2   95.0  56.000000  80.000000
3   95.0  43.666667  98.000000

In [9]:
df = df.fillna(0)
df

       I    II   III
0  100.0  30.0   0.0
1   90.0  45.0  40.0
2    0.0  56.0  80.0
3   95.0   0.0  98.0

In [14]:
df = df.replace(0, 10)
df

       I    II   III
0  100.0  30.0  10.0
1   90.0  45.0  40.0
2   10.0  56.0  80.0
3   95.0  10.0  98.0

In [15]:
df["I"] = df["I"].replace(10, 1000)
df

        I    II   III
0   100.0  30.0  10.0
1    90.0  45.0  40.0
2  1000.0  56.0  80.0
3    95.0  10.0  98.0

In [16]:
df["II"] = df["II"].replace(56, np.nan)
df

        I    II   III
0   100.0  30.0  10.0
1    90.0  45.0  40.0
2  1000.0   NaN  80.0
3    95.0  10.0  98.0

In [21]:
print(df.dropna(axis = 0))
print(df.dropna(axis = 1))

       I    II   III
0  100.0  30.0  10.0
1   90.0  45.0  40.0
3   95.0  10.0  98.0
        I   III
0   100.0  10.0
1    90.0  40.0
2  1000.0  80.0
3    95.0  98.0

In [22]:
df["I"].unique()

array([ 100.,   90., 1000.,   95.])

In [23]:
df["I"].value_counts()

I
100.0     1
90.0      1
1000.0    1
95.0      1
Name: count, dtype: int64

In [24]:
data = pd.read_csv("employee.csv")

data.head()

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711

In [26]:
data.columns

Index(['name', 'age', 'income', 'gender', 'department', 'grade',
       'performance_score'],
      dtype='object')

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               9 non-null      object
 1   age                7 non-null      float64
 2   income             7 non-null      float64
 3   gender             7 non-null      object
 4   department         9 non-null      object
 5   grade              9 non-null      object
 6   performance_score  9 non-null      int64
dtypes: float64(2), int64(1), object(4)
memory usage: 636.0+ bytes

In [29]:
data[["name", "department"]]

            name  department
0    Allen Smith  Operations
1        S Kumar     Finance
2    Jack Morgan     Finance
3      Ying Chin       Sales
4  Dheeraj Patel  Operations
5  Satyam Sharma       Sales
6   James Authur  Operations
7     Josh Wills     Finance
8       Leo Duck       Sales

In [30]:
data.filter(["name", "department"], axis = 1)

            name  department
0    Allen Smith  Operations
1        S Kumar     Finance
2    Jack Morgan     Finance
3      Ying Chin       Sales
4  Dheeraj Patel  Operations
5  Satyam Sharma       Sales
6   James Authur  Operations
7     Josh Wills     Finance
8       Leo Duck       Sales

In [32]:
data.filter([0,1,2], axis = 0)

          name   age   income gender  department grade  performance_score
0  Allen Smith  45.0      NaN    NaN  Operations    G3                723
1      S Kumar   NaN  16000.0      F     Finance    G0                520
2  Jack Morgan  32.0  35000.0      M     Finance    G2                674

In [37]:
data.loc[0:2, ["name", "department"]]

          name  department
0  Allen Smith  Operations
1      S Kumar     Finance
2  Jack Morgan     Finance

In [39]:
data[data.department == "Sales"]

            name   age   income gender department grade  performance_score
3      Ying Chin  45.0  65000.0      F      Sales    G3                556
5  Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649
8       Leo Duck  23.0  98000.0      M      Sales    G4                709

In [47]:
data[(data["department"] == "Sales") | (data["department"] == "Finance")]

            name   age   income gender department grade  performance_score
1        S Kumar   NaN  16000.0      F    Finance    G0                520
2    Jack Morgan  32.0  35000.0      M    Finance    G2                674
3      Ying Chin  45.0  65000.0      F      Sales    G3                556
5  Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649
7     Josh Wills  54.0  52000.0      F    Finance    G3                901
8       Leo Duck  23.0  98000.0      M      Sales    G4                709

In [49]:
data[data.department.isin(["Sales", "Finance"])]

            name   age   income gender department grade  performance_score
1        S Kumar   NaN  16000.0      F    Finance    G0                520
2    Jack Morgan  32.0  35000.0      M    Finance    G2                674
3      Ying Chin  45.0  65000.0      F      Sales    G3                556
5  Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649
7     Josh Wills  54.0  52000.0      F    Finance    G3                901
8       Leo Duck  23.0  98000.0      M      Sales    G4                709

In [50]:
data = data.dropna()
data["age"] = data["age"].fillna(data.age.mean())
data["income"] = data["income"].fillna(data.income.median())
data

/var/folders/q2/2h4p204s56d3vhv_jx5hmc6m0000gn/T/ipykernel_18112/252007202.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["age"] = data["age"].fillna(data.age.mean())
/var/folders/q2/2h4p204s56d3vhv_jx5hmc6m0000gn/T/ipykernel_18112/252007202.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["income"] = data["income"].fillna(data.income.median())

            name   age   income gender  department grade  performance_score
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [53]:
upper_limit = data.performance_score.mean() + 3 * data.performance_score.std()
lower_limit = data.performance_score.mean() - 3 * data.performance_score.std()
new = data[(data.performance_score > lower_limit) & (data.performance_score < upper_limit)]
new

            name   age   income gender  department grade  performance_score
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

Assignment

In [59]:
ginjal = pd.read_csv("penyakit_ginjal_kronik-1 (1).csv")
ginjal_copy = ginjal.copy()
ginjal_copy.isnull().sum()

id                   0
umur                 9
tekanandarah        12
gravitas            47
albumin             46
sugar               49
seldarahmerah      152
pussel              65
gds                 44
ureum               19
kreatinin           17
natrium             87
kalium              88
hemoglobin          52
MCV                 70
seldarahputih      105
seldarahmerah.1    130
hipertensi           2
diabetes             2
cad                  2
nafsumakan           1
edema                1
anemia               1
klasifikasi          0
dtype: int64

In [60]:
ginjal_copy = ginjal_copy.dropna()
ginjal_copy = ginjal_copy.replace("yes", "iya")
ginjal_copy

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,iya,Tidak,Tidak,buruk,iya,iya,ckd
9,9,53.0,90.0,1.020,2.0,0.0,Normal,Normal,70.0,107.0,...,29,12100,3.7,iya,iya,Tidak,buruk,Tidak,iya,ckd
11,11,63.0,70.0,1.010,3.0,0.0,Normal,Normal,380.0,60.0,...,32,4500,3.8,iya,iya,Tidak,buruk,iya,Tidak,ckd
14,14,68.0,80.0,1.010,3.0,2.0,Tidak Normal,Normal,157.0,90.0,...,16,11000,2.6,iya,iya,iya,buruk,iya,Tidak,ckd
20,20,61.0,80.0,1.015,2.0,0.0,Normal,Normal,173.0,148.0,...,24,9200,3.2,iya,iya,iya,buruk,iya,iya,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd

In [63]:
print(len(ginjal))
print(len(ginjal_copy))

400
159