In [1]:
import pandas as pd 

covid = pd.read_csv("covid.csv")
covid

   Unnamed: 0  ODP  PDP  POSITIF  SEMBUH  MENINGGAL
0   3/26/2020  204   89       17       0          4
1   3/27/2020  207   99       17       0          4
2   3/29/2020  256  119       28       0          4
3   3/30/2020  262  123       31       0          6
4   3/31/2020  308  134       34       2          6
5    4/1/2020  336  139       38       2          6
6    4/2/2020  371  156       40       2         10
7    4/5/2020  416  170       42       2         10
8    4/6/2020  450  184       43       2         11
9    4/8/2020  525  196       44       2         13
10  4/11/2020  600  230       47       2         15
11  4/12/2020  606  231       49       2         16
12  4/13/2020  630  239       50       3         16
13  4/14/2020  629  245       44       9         16

In [2]:
covid = covid.rename(
    columns={
        "Unnamed: 0" : "DATE"
    }
)

covid

         DATE  ODP  PDP  POSITIF  SEMBUH  MENINGGAL
0   3/26/2020  204   89       17       0          4
1   3/27/2020  207   99       17       0          4
2   3/29/2020  256  119       28       0          4
3   3/30/2020  262  123       31       0          6
4   3/31/2020  308  134       34       2          6
5    4/1/2020  336  139       38       2          6
6    4/2/2020  371  156       40       2         10
7    4/5/2020  416  170       42       2         10
8    4/6/2020  450  184       43       2         11
9    4/8/2020  525  196       44       2         13
10  4/11/2020  600  230       47       2         15
11  4/12/2020  606  231       49       2         16
12  4/13/2020  630  239       50       3         16
13  4/14/2020  629  245       44       9         16

In [3]:
covid = pd.read_csv("covid.csv", header=None)
covid = covid.drop(0)
covid.columns = ["DATE", "ODP", "PDP", "POSITIF", "SEMBUH", "MENINGGAL"]
covid

         DATE  ODP  PDP POSITIF SEMBUH MENINGGAL
1   3/26/2020  204   89      17      0         4
2   3/27/2020  207   99      17      0         4
3   3/29/2020  256  119      28      0         4
4   3/30/2020  262  123      31      0         6
5   3/31/2020  308  134      34      2         6
6    4/1/2020  336  139      38      2         6
7    4/2/2020  371  156      40      2        10
8    4/5/2020  416  170      42      2        10
9    4/6/2020  450  184      43      2        11
10   4/8/2020  525  196      44      2        13
11  4/11/2020  600  230      47      2        15
12  4/12/2020  606  231      49      2        16
13  4/13/2020  630  239      50      3        16
14  4/14/2020  629  245      44      9        16

In [4]:
covid.shape

(14, 6)

In [5]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 1 to 14
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DATE       14 non-null     object
 1   ODP        14 non-null     object
 2   PDP        14 non-null     object
 3   POSITIF    14 non-null     object
 4   SEMBUH     14 non-null     object
 5   MENINGGAL  14 non-null     object
dtypes: object(6)
memory usage: 804.0+ bytes

In [6]:
covid["DATE"]

1     3/26/2020
2     3/27/2020
3     3/29/2020
4     3/30/2020
5     3/31/2020
6      4/1/2020
7      4/2/2020
8      4/5/2020
9      4/6/2020
10     4/8/2020
11    4/11/2020
12    4/12/2020
13    4/13/2020
14    4/14/2020
Name: DATE, dtype: object

In [7]:
covid["DATE"] = pd.to_datetime(covid["DATE"])
covid["DATE"]

1    2020-03-26
2    2020-03-27
3    2020-03-29
4    2020-03-30
5    2020-03-31
6    2020-04-01
7    2020-04-02
8    2020-04-05
9    2020-04-06
10   2020-04-08
11   2020-04-11
12   2020-04-12
13   2020-04-13
14   2020-04-14
Name: DATE, dtype: datetime64[ns]

In [8]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 1 to 14
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DATE       14 non-null     datetime64[ns]
 1   ODP        14 non-null     object
 2   PDP        14 non-null     object
 3   POSITIF    14 non-null     object
 4   SEMBUH     14 non-null     object
 5   MENINGGAL  14 non-null     object
dtypes: datetime64[ns](1), object(5)
memory usage: 804.0+ bytes

In [9]:
covid.head(2)

        DATE  ODP PDP POSITIF SEMBUH MENINGGAL
1 2020-03-26  204  89      17      0         4
2 2020-03-27  207  99      17      0         4

In [10]:
covid.tail(2)

         DATE  ODP  PDP POSITIF SEMBUH MENINGGAL
13 2020-04-13  630  239      50      3        16
14 2020-04-14  629  245      44      9        16

In [11]:
test = {
    "Durasi" : {
        "0" : 60,
        "1" : 60
    },
    "Pulse" : {
        "0" : 110,
        "1" : 117
    }
}

df = pd.DataFrame(test)
df

   Durasi  Pulse
0      60    110
1      60    117

In [12]:
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

json = pd.read_json("https://raw.githubusercontent.com/mediatechid/bootcamp-data-analyst/main/zomato_resto_file1.json")
json

,results_found,restaurants,results_shown,results_start,message,code,status
0,17151.0,"[{'restaurant': {'has_online_delivery': 1, 'ph...",20.0,1.0,NaN,NaN,NaN
1,4748.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
2,13786.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
3,10224.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
4,7039.0,"[{'restaurant': {'has_online_delivery': 0, 'ph...",20.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...
474,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
475,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
476,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
477,NaN,NaN,NaN,NaN,API limit exceeded,440.0,
478,NaN,NaN,NaN,NaN,API limit exceeded,440.0,

In [13]:
data = []

for i in json["restaurants"]:
    if isinstance(i , list):
        for lapisan1 in i :
            for lapisan2 in lapisan1.values():
                for key,value in lapisan2.items():
                    if key == "name":
                        data.append(value)

df = pd.DataFrame(data, columns=["Restaurant"])
df.to_excel("restoran.xlsx")

STATISTIK

In [14]:
stat = pd.read_csv("penyakit_jantung.csv")
thalach = stat["thalach"]
thalach.head()

0    150
1    187
2    172
3    178
4    163
Name: thalach, dtype: int64

In [15]:
import numpy as np
from scipy import stats 

print(thalach.mean())
print(thalach.median())
print(stats.mode(thalach))
print(np.var(thalach))
print(np.std(thalach))
print(stats.skew(thalach))

149.64686468646866
153.0
ModeResult(mode=162, count=11)
522.9148994107331
22.86733258188924
-0.5347455419075503

In [16]:
data = thalach.sort_values()

q1 = np.percentile(data, 25)
q2 = np.percentile(data, 50)
q3 = np.percentile(data, 75)

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

df_clean = data[(data >= lower) & (data <= upper)]
df_clean

243     88
297     90
262     95
233     96
136     96
      ...
62     190
125    192
103    194
248    195
72     202
Name: thalach, Length: 302, dtype: int64

In [17]:
data

272     71
243     88
297     90
262     95
233     96
      ...
62     190
125    192
103    194
248    195
72     202
Name: thalach, Length: 303, dtype: int64

Assignment

In [21]:
data = pd.read_csv("Data-Penindakan-Pelanggaran-Lalu-Lintas (1).csv")
data.head()

,bulan,wilayah,bap_tilang,stop_operasi,bap_polisi,stop_operasi_polisi,penderekan,ocp_roda_dua,ocp_roda_empat,angkut_motor
0,Januari,Bidang Dalops,44,139,0,0,73,0,0,0
1,Januari,Sudinhub Jakarta Pusat,47,2,52,0,184,237,15,97
2,Januari,Sudinhub Jakarta Utara,166,27,0,0,174,0,0,0
3,Januari,Sudinhub Jakarta Selatan,44,1,0,0,61,42,75,0
4,Januari,Sudinhub Jakarta Barat,184,70,0,0,202,10,5,0

In [22]:
# data numerik

numerik = data.loc[0:, "bap_tilang":]
numerik.head()

,bap_tilang,stop_operasi,bap_polisi,stop_operasi_polisi,penderekan,ocp_roda_dua,ocp_roda_empat,angkut_motor
0,44,139,0,0,73,0,0,0
1,47,2,52,0,184,237,15,97
2,166,27,0,0,174,0,0,0
3,44,1,0,0,61,42,75,0
4,184,70,0,0,202,10,5,0

In [23]:
# data kategori

kategori = data.loc[0:, "bulan": "wilayah"]
kategori.head()

     bulan                   wilayah
0  Januari             Bidang Dalops
1  Januari    Sudinhub Jakarta Pusat
2  Januari    Sudinhub Jakarta Utara
3  Januari  Sudinhub Jakarta Selatan
4  Januari    Sudinhub Jakarta Barat

In [32]:
# no 3 

print(np.mean(numerik, axis = 0))

bap_tilang             170.333333
stop_operasi            62.690476
bap_polisi               5.761905
stop_operasi_polisi      0.000000
penderekan             160.285714
ocp_roda_dua           103.428571
ocp_roda_empat          13.809524
angkut_motor            26.000000
dtype: float64

In [30]:
print(np.median(numerik, axis = 0))

[164.   46.5   0.    0.  157.    5.    1.    0. ]

In [36]:
# no 4

print(np.percentile(numerik, 25, axis = 0))
print(np.percentile(numerik, 50, axis = 0))
print(np.percentile(numerik, 75, axis = 0))

[69.   20.25  0.    0.   98.    0.    0.    0.  ]
[164.   46.5   0.    0.  157.    5.    1.    0. ]
[246.5  105.5    0.     0.   205.25 156.5    7.5    0.  ]

In [42]:
# no 5

group = data.groupby("bulan")["bap_tilang"].mean()
group

bulan
April       237.500000
Februari    161.666667
Januari     112.666667
Juli         90.500000
Juni        214.166667
Maret       247.166667
Mei         128.666667
Name: bap_tilang, dtype: float64

In [47]:
jumlah_april = len(data.loc[data["bulan"] == "April"])
total_april = data.loc[data["bulan"] == "April", "bap_tilang"].sum()
rata = total_april / jumlah_april
print(rata)

237.5