In [76]:
import pandas as pd 

df = pd.read_csv("death.csv")
df

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,Bencana Alam,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,Bencana Non Alam dan Penyakit,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,Bencana Non Alam dan Penyakit,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,Bencana Non Alam dan Penyakit,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,Bencana Non Alam dan Penyakit,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
675,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2016,1,0,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...
676,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2017,1,0,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...
677,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2019,1,0,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...
678,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2020,1,0,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...
679,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2021,1,0,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...

In [77]:
df.isnull().sum()

Cause              0
Type               0
Year               0
Data Redundancy    0
Total Deaths       0
Source             0
Page at Source     2
Source URL         3
dtype: int64

In [78]:
df.dropna(inplace=True)
df.isnull().sum()

Cause              0
Type               0
Year               0
Data Redundancy    0
Total Deaths       0
Source             0
Page at Source     0
Source URL         0
dtype: int64

In [79]:
df.duplicated().sum()

0

In [80]:
df.drop_duplicates(inplace=True)

In [81]:
q1 = df["Total Deaths"].quantile(0.25)
q3 = df["Total Deaths"].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr 
upper_bound = q3 + 1.5 * iqr

print(f"q1 = {q1}")
print(f"q3 = {q3}")
print(f"lower bound = {lower_bound}")
print(f"upper bound = {upper_bound}")

outlier = df[(df["Total Deaths"] < lower_bound) | (df["Total Deaths"] > upper_bound)]
outlier

q1 = 4.0
q3 = 291.0
lower bound = -426.5
upper bound = 721.5

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
8,AIDS,Bencana Non Alam dan Penyakit,2007,1,788,Profil Kesehatan Indonesia Tahun 2011,148,https://pusdatin.kemkes.go.id/download.php?fil...
11,AIDS,Bencana Non Alam dan Penyakit,2010,1,979,Profil Kesehatan Indonesia Tahun 2011,148,https://pusdatin.kemkes.go.id/download.php?fil...
135,Cedera intrakranial,Bencana Non Alam dan Penyakit,2004,1,2554,Profil Kesehatan Indonesia Tahun 2004,20,https://pusdatin.kemkes.go.id/download.php?fil...
136,Cedera intrakranial,Bencana Non Alam dan Penyakit,2005,1,3021,Profil Kesehatan Indonesia Tahun 2005,21,https://pusdatin.kemkes.go.id/download.php?fil...
137,Cedera intrakranial,Bencana Non Alam dan Penyakit,2006,1,2519,Profil Kesehatan Indonesia Tahun 2007,26,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
670,Tuberkulosis,Bencana Non Alam dan Penyakit,2019,1,11993,Profil Kesehatan Indonesia Tahun 2019,Lampiran 52,https://pusdatin.kemkes.go.id/download.php?fil...
671,Tuberkulosis,Bencana Non Alam dan Penyakit,2020,1,13174,Profil Kesehatan Indonesia Tahun 2020,Lampiran 52,https://pusdatin.kemkes.go.id/download.php?fil...
672,Tuberkulosis,Bencana Non Alam dan Penyakit,2021,1,14148,Profil Kesehatan Indonesia Tahun 2021,Lampiran 52,https://www.kemkes.go.id/downloads/resources/d...
673,Tuberkulosis paru,Bencana Non Alam dan Penyakit,2004,1,3852,Profil Kesehatan Indonesia Tahun 2004,20,https://pusdatin.kemkes.go.id/download.php?fil...
674,Tuberkulosis paru lainnya,Bencana Non Alam dan Penyakit,2005,1,2024,Profil Kesehatan Indonesia Tahun 2005,21,https://pusdatin.kemkes.go.id/download.php?fil...

In [82]:
df_clean = df[(df["Total Deaths"] >= lower_bound) & (df["Total Deaths"] <= upper_bound)]
df_clean.to_csv("death_clean.csv", index=False)

Encoding

In [83]:
df_clean

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,Bencana Alam,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,Bencana Non Alam dan Penyakit,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,Bencana Non Alam dan Penyakit,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,Bencana Non Alam dan Penyakit,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,Bencana Non Alam dan Penyakit,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
675,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2016,1,0,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...
676,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2017,1,0,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...
677,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2019,1,0,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...
678,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2020,1,0,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...
679,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2021,1,0,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...

In [84]:
# One hot encoding

df_hot = pd.get_dummies(df_clean.copy(), columns=["Cause", "Type"])
df_hot

,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL,Cause_AIDS,Cause_Abrasi Air Laut,Cause_Aksi Teror dan Sabotase,Cause_Angin Puting Beliung,...,Cause_Rubella,Cause_Tanah Longsor,Cause_Tersambar Petir,Cause_Tetanus,Cause_Tetanus Neonatorium,Cause_Tsunami,Cause_Wabah Penyakit (Epidemi),Type_Bencana Alam,Type_Bencana Non Alam dan Penyakit,Type_Bencana Sosial
0,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
1,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675,2016,1,0,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
676,2017,1,0,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
677,2019,1,0,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
678,2020,1,0,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
679,2021,1,0,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False

In [85]:
# label encoding

from sklearn.preprocessing import LabelEncoder

Label_encoder = LabelEncoder()
df_label = df_clean.copy() 
df_label["Type"] = Label_encoder.fit_transform(df_label["Type"])
df_label

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,0,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,1,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,1,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,1,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,1,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
675,Wabah Penyakit (Epidemi),1,2016,1,0,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...
676,Wabah Penyakit (Epidemi),1,2017,1,0,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...
677,Wabah Penyakit (Epidemi),1,2019,1,0,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...
678,Wabah Penyakit (Epidemi),1,2020,1,0,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...
679,Wabah Penyakit (Epidemi),1,2021,1,0,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...

Data transform

In [86]:
# normalisasi 

from sklearn.preprocessing import MinMaxScaler 

scaler = MinMaxScaler()
df_normal = df_clean.copy()
df_normal[["Total Deaths"]] = scaler.fit_transform(df_normal[["Total Deaths"]])
df_normal

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,Bencana Alam,2012,1,0.000000,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,Bencana Non Alam dan Penyakit,2000,1,0.066104,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,Bencana Non Alam dan Penyakit,2001,1,0.139241,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,Bencana Non Alam dan Penyakit,2002,1,0.140647,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,Bencana Non Alam dan Penyakit,2003,1,0.367089,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
675,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2016,1,0.000000,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...
676,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2017,1,0.000000,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...
677,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2019,1,0.000000,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...
678,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2020,1,0.000000,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...
679,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2021,1,0.000000,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...

Splitting data

In [87]:
x = df_clean[["Cause", "Type"]] # fitur
y = df_clean[["Total Deaths"]] # target

In [88]:
from sklearn.model_selection import train_test_split

scale = MinMaxScaler()

x_encoded = pd.get_dummies(x)
y_norm = scale.fit_transform(y).ravel()

x_train, x_test, y_train, y_test = train_test_split(x_encoded, y_norm, test_size=0.2)
print(f"x_train = {len(x_train)}, x_test = {len(x_test)}")
print(f"y_train = {len(y_train)}, y_test = {len(y_test)}")

x_train = 440, x_test = 110
y_train = 440, y_test = 110

Assignment

In [89]:
df = pd.read_csv("Mall_Customers.csv")
df_clean = df.copy()
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [90]:
df_clean.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [91]:
df_clean.duplicated().sum()

0

In [92]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [93]:
q1 = df_clean["Spending Score (1-100)"].quantile(0.25)
q3 = df_clean["Spending Score (1-100)"].quantile(0.75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr 
upper_bound = q3 + 1.5 * iqr

print(f"q1 = {q1}")
print(f"q3 = {q3}")
print(f"lower bound = {lower_bound}")
print(f"upper bound = {upper_bound}")

df_clean = df[(df["Spending Score (1-100)"] >= lower_bound) & (df["Spending Score (1-100)"] <= upper_bound)]
df_clean

q1 = 34.75
q3 = 73.0
lower bound = -22.625
upper bound = 130.375

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [94]:
df_clean = pd.get_dummies(df_clean, columns=["Gender"])
df_clean

,CustomerID,Age,Annual Income (k$),Spending Score (1-100),Gender_Female,Gender_Male
0,1,19,15,39,False,True
1,2,21,15,81,False,True
2,3,20,16,6,True,False
3,4,23,16,77,True,False
4,5,31,17,40,True,False
...,...,...,...,...,...,...
195,196,35,120,79,True,False
196,197,45,126,28,True,False
197,198,32,126,74,False,True
198,199,32,137,18,False,True
199,200,30,137,83,False,True

In [95]:
scale_norm = MinMaxScaler()
df_clean[["Annual Income (k$)", "Spending Score (1-100)"]] = scale_norm.fit_transform(df_clean[["Annual Income (k$)", "Spending Score (1-100)"]])
df_clean

,CustomerID,Age,Annual Income (k$),Spending Score (1-100),Gender_Female,Gender_Male
0,1,19,0.000000,0.387755,False,True
1,2,21,0.000000,0.816327,False,True
2,3,20,0.008197,0.051020,True,False
3,4,23,0.008197,0.775510,True,False
4,5,31,0.016393,0.397959,True,False
...,...,...,...,...,...,...
195,196,35,0.860656,0.795918,True,False
196,197,45,0.909836,0.275510,True,False
197,198,32,0.909836,0.744898,False,True
198,199,32,1.000000,0.173469,False,True
199,200,30,1.000000,0.836735,False,True

In [98]:
x = df_clean[["Annual Income (k$)", "Gender_Female", "Gender_Male"]]
y = df_clean["Spending Score (1-100)"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print(f"x_train = {len(x_train)}, x_test = {len(x_test)}")
print(f"y_train = {len(y_train)}, y_test = {len(y_test)}")

x_train = 160, x_test = 40
y_train = 160, y_test = 40

Contoh 2

In [99]:
df = pd.read_csv("Mall_Customers.csv")
df_clean = df.copy()
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [101]:
x = df_clean[["Annual Income (k$)", "Gender"]]
y = df_clean[["Spending Score (1-100)"]]

x_encode = pd.get_dummies(x, columns=["Gender"])

scale_baru = MinMaxScaler()
y_norm = scale_baru.fit_transform(y).ravel()

x_train, x_test, y_train, y_test = train_test_split(x_encode, y_norm, test_size=0.2)
print(f"x_train = {len(x_train)}, x_test = {len(x_test)}")
print(f"y_train = {len(y_train)}, y_test = {len(y_test)}")

x_train = 160, x_test = 40
y_train = 160, y_test = 40