In [1]:
from bs4 import BeautifulSoup

In [2]:
html_doc = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 id = "title"><b>Title 1</b></h1>
    <h1 id = "title"><b>Title 2</b></h1>
    <p class="nama1">Agik</p>
    <p class="nama2">Anang</p>
    <p class="nama3">Wahyu</p>
</body>
</html>
"""

In [ ]:
soup = BeautifulSoup(html_doc, "html")
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>Document</title>
</head>
<body>
<h1 id="title"><b>Title 1</b></h1>
<h1 id="title"><b>Title 2</b></h1>
<p class="nama1">Agik</p>
<p class="nama2">Anang</p>
<p class="nama3">Wahyu</p>
</body>
</html>

In [4]:
data_find = soup.find("p").text
data_find

'Agik'

In [5]:
data_find = soup.find("h1", id = "title").text
data_find

'Title 1'

In [6]:
data_find = soup.find("p", class_ = "nama2").text
data_find

'Anang'

In [8]:
data_find = soup.find_all("p")
print(data_find)

for i in data_find:
    print(i.text)

[<p class="nama1">Agik</p>, <p class="nama2">Anang</p>, <p class="nama3">Wahyu</p>]
Agik
Anang
Wahyu

In [ ]:
data_find = soup.select("h1#title")
data_find

In [10]:
data_find = soup.select("p.nama2")
data_find

In [19]:
import requests 

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"
header = {
    "User-Agent": "testing"
}
data = requests.get(url, headers=header)
print(data.text)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard" lang="en" dir="ltr">
<head>
<meta charset="UTF-8">
<title>List of largest companies by revenue - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"b29215a8-bd85-40b8-9456-9a672a0b9aeb","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_by_revenue","wgTitle":"List of largest companies by revenue","wgCurRevisionId":1347314870,"wgRevisionId":1347314870,"wgArticleId":997455,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Lists of companies by revenue","Lists of largest companies"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_by_revenue","wgRelevantArticleId":997455,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":30000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q900297","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]}};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wp25EasterEggs.styles":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession","ext.testKitchen","ext.wp25EasterEggs"];</script>
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});</script>
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cext.wp25EasterEggs.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022">
<script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022"></script>
<meta name="ResourceLoaderDynamicStyles" content="">
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022">
<meta name="generator" content="MediaWiki 1.46.0-wmf.22">
<meta name="referrer" content="origin">
<meta name="referrer" content="origin-when-cross-origin">
<meta name="robots" content="max-image-preview:standard">
<meta name="format-detection" content="telephone=no">
<meta property="og:image" content="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Amazon_Sydney_logo.jpg/1280px-Amazon_Sydney_logo.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="675">
<meta name="viewport" content="width=1120">
<meta property="og:title" content="List of largest companies by revenue - Wikipedia">
<meta property="og:type" content="website">
<link rel="preconnect" href="//upload.wikimedia.org">
<link rel="alternate" type="application/x-wiki" title="Edit this page" href="/w/index.php?title=List_of_largest_companies_by_revenue&amp;action=edit">
<link rel="apple-touch-icon" href="/static/apple-touch/wikipedia.png">
<link rel="icon" href="/static/favicon/wikipedia.ico">
<link rel="search" type="application/opensearchdescription+xml" href="/w/rest.php/v1/search" title="Wikipedia (en)">
<link rel="EditURI" type="application/rsd+xml" href="//en.wikipedia.org/w/api.php?action=rsd">
<link rel="canonical" href="https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue">
<link rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">
<link rel="alternate" type="application/atom+xml" title="Wikipedia Atom feed" href="/w/index.php?title=Special:RecentChanges&amp;feed=atom">
<link rel="dns-prefetch" href="//meta.wikimedia.org" />
<link rel="dns-prefetch" href="auth.wikimedia.org">
</head>
<body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_by_revenue rootpage-List_of_largest_companies_by_revenue skin-vector-2022 action-view">
<div id="mw-aria-live-region" class="mw-aria-live-region" aria-live="polite"></div><a class="mw-jump-link" href="#bodyContent">Jump to content</a>
<div class="vector-header-container">
	<header class="vector-header mw-header no-font-mode-scale">
		<div class="vector-header-start">
			<nav class="vector-main-menu-landmark" aria-label="Site">

<div id="vector-main-menu-dropdown" class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right"  title="Main menu" >
	<input type="checkbox" id="vector-main-menu-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-main-menu-dropdown" class="vector-dropdown-checkbox "  aria-label="Main menu"  >
	<label id="vector-main-menu-dropdown-label" for="vector-main-menu-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu"></span>

<span class="vector-dropdown-label-text">Main menu</span>
	</label>
	<div class="vector-dropdown-content">


				<div id="vector-main-menu-unpinned-container" class="vector-unpinned-container">

<div id="vector-main-menu" class="vector-main-menu vector-pinnable-element">
	<div
	class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned"
	data-feature-name="main-menu-pinned"
	data-pinnable-element-id="vector-main-menu"
	data-pinned-container-id="vector-main-menu-pinned-container"
	data-unpinned-container-id="vector-main-menu-unpinned-container"
>
	<div class="vector-pinnable-header-label">Main menu</div>
	<button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">move to sidebar</button>
	<button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">hide</button>
</div>


<div id="p-navigation" class="vector-menu mw-portlet mw-portlet-navigation"  >
	<div class="vector-menu-heading">
		Navigation
	</div>
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">

			<li id="n-mainpage-description" class="mw-list-item"><a href="/wiki/Main_Page" title="Visit the main page [z]" accesskey="z"><span>Main page</span></a></li><li id="n-contents" class="mw-list-item"><a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a></li><li id="n-currentevents" class="mw-list-item"><a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a></li><li id="n-randompage" class="mw-list-item"><a href="/wiki/Special:Random" title="Visit a randomly selected article [x]" accesskey="x"><span>Random article</span></a></li><li id="n-aboutsite" class="mw-list-item"><a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a></li><li id="n-contactpage" class="mw-list-item"><a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a></li>
		</ul>

	</div>
</div>


<div id="p-interaction" class="vector-menu mw-portlet mw-portlet-interaction"  >
	<div class="vector-menu-heading">
		Contribute
	</div>
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">

			<li id="n-help" class="mw-list-item"><a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a></li><li id="n-introduction" class="mw-list-item"><a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a></li><li id="n-portal" class="mw-list-item"><a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a></li><li id="n-recentchanges" class="mw-list-item"><a href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]" accesskey="r"><span>Recent changes</span></a></li><li id="n-upload" class="mw-list-item"><a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a></li><li id="n-specialpages" class="mw-list-item"><a href="/wiki/Special:SpecialPages" title="A list of all special pages [q]" accesskey="q"><span>Special pages</span></a></li>
		</ul>

	</div>
</div>

</div>

				</div>

	</div>
</div>

		</nav>

<a href="/wiki/Main_Page" class="mw-logo">
	<img class="mw-logo-icon" src="/static/images/icons/enwiki-25.svg" alt="" aria-hidden="true" height="50" width="50">
	<span class="mw-logo-container skin-invert">
		<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;">
		<img class="mw-logo-tagline" alt="The Free Encyclopedia" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" width="140" height="11" style="width: 8.75em; height: 0.6875em;">
	</span>
</a>

		</div>
		<div class="vector-header-end">

<div id="p-search" role="search" class="vector-search-box-vue  vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box">
	<a href="/wiki/Special:Search" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" title="Search Wikipedia [f]" accesskey="f"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>

<span>Search</span>
	</a>
	<div class="vector-typeahead-search-container">
		<div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
			<form action="/w/index.php" id="searchform" class="cdx-search-input cdx-search-input--has-end-button">
				<div id="simpleSearch" class="cdx-search-input__input-wrapper"  data-search-loc="header-moved">
					<div class="cdx-text-input cdx-text-input--has-start-icon">
						<input
							class="cdx-text-input__input mw-searchInput" autocomplete="off"
							 type="search" name="search" placeholder="Search Wikipedia" aria-label="Search Wikipedia" autocapitalize="none" spellcheck="false" title="Search Wikipedia [f]" accesskey="f" id="searchInput"
							>
						<span class="cdx-text-input__icon cdx-text-input__start-icon"></span>
					</div>
					<input type="hidden" name="title" value="Special:Search">
				</div>
				<button class="cdx-button cdx-search-input__end-button">Search</button>
			</form>
		</div>
	</div>
</div>

			<nav class="vector-user-links vector-user-links-wide" aria-label="Personal tools">
	<div class="vector-user-links-main">

<div id="p-vector-user-menu-preferences" class="vector-menu mw-portlet emptyPortlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


		</ul>

	</div>
</div>


<div id="p-vector-user-menu-userpage" class="vector-menu mw-portlet emptyPortlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


		</ul>

	</div>
</div>

	<nav class="vector-appearance-landmark" aria-label="Appearance">

<div id="vector-appearance-dropdown" class="vector-dropdown "  title="Change the appearance of the page&#039;s font size, width, and color" >
	<input type="checkbox" id="vector-appearance-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-appearance-dropdown" class="vector-dropdown-checkbox "  aria-label="Appearance"  >
	<label id="vector-appearance-dropdown-label" for="vector-appearance-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance"></span>

<span class="vector-dropdown-label-text">Appearance</span>
	</label>
	<div class="vector-dropdown-content">


			<div id="vector-appearance-unpinned-container" class="vector-unpinned-container">

			</div>

	</div>
</div>

	</nav>

<div id="p-vector-user-menu-notifications" class="vector-menu mw-portlet emptyPortlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">


		</ul>

	</div>
</div>


<div id="p-vector-user-menu-overflow" class="vector-menu mw-portlet"  >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">
			<li id="pt-sitesupport-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw-interface  href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en" class=""><span>Donate</span></a>
</li>
<li id="pt-createaccount-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw-interface  href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory" class=""><span>Create account</span></a>
</li>
<li id="pt-login-2" class="user-links-collapsible-item mw-list-item user-links-collapsible-item"><a data-mw-interface  href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+by+revenue" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o" class=""><span>Log in</span></a>
</li>


		</ul>

	</div>
</div>

	</div>

<div id="vector-user-links-dropdown" class="vector-dropdown vector-user-menu vector-button-flush-right vector-user-menu-logged-out user-links-collapsible-item"  title="Log in and more options" >
	<input type="checkbox" id="vector-user-links-dropdown-checkbox" role="button" aria-haspopup="true" data-event-name="ui.dropdown-vector-user-links-dropdown" class="vector-dropdown-checkbox "  aria-label="Personal tools"  >
	<label id="vector-user-links-dropdown-label" for="vector-user-links-dropdown-checkbox" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only " aria-hidden="true"  ><span class="vector-icon mw-ui-icon-ellipsis mw-ui-icon-wikimedia-ellipsis"></span>

<span class="vector-dropdown-label-text">Personal tools</span>
	</label>
	<div class="vector-dropdown-content">



<div id="p-personal" class="vector-menu mw-portlet mw-portlet-personal user-links-collapsible-item"  title="User menu" >
	<div class="vector-menu-content">

		<ul class="vector-menu-content-list">

			<li id="pt-sitesupport" class="user-links-collapsible-item mw-list-item"><a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span class="vector-icon mw-ui-icon-heart mw-ui-icon-wikimedia-heart"></span> <span>Donate</span></a></li><li id="pt-createaccount" class="user-links-collapsible-item mw-list-item"><a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a></li><li id="pt-login" class="user-links-collapsible-item mw-list-item"><a href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+by+revenue" title="You&#039;re encouraged to log in; however, it&#039;s not mandatory. [o]" accesskey="o"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a></li>

In [22]:
scrap = BeautifulSoup(data.text, "html")
print(scrap.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of largest companies by revenue - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"b29215a8-bd85-40b8-9456-9a672a0b9aeb","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_by_revenue","wgTitle":"List of largest companies by revenue","wgCurRevisionId":1347314870,"wgRevisionId":1347314870,"wgArticleId":997455,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Lists of companies by revenue","Lists of largest companies"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_by_revenue","wgRelevantArticleId":997455,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":30000,"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgWikibaseItemId":"Q900297","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]}};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","jquery.makeCollapsible.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready","ext.wp25EasterEggs.styles":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","mediawiki.page.media","site","mediawiki.page.ready","jquery.tablesorter","jquery.makeCollapsible","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession","ext.testKitchen","ext.wp25EasterEggs"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cext.wp25EasterEggs.styles%7Cjquery.makeCollapsible.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.46.0-wmf.22" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Amazon_Sydney_logo.jpg/1280px-Amazon_Sydney_logo.jpg" property="og:image"/>
  <meta content="1200" property="og:image:width"/>
  <meta content="675" property="og:image:height"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="List of largest companies by revenue - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="//upload.wikimedia.org" rel="preconnect"/>
  <link href="/w/index.php?title=List_of_largest_companies_by_revenue&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch"/>
  <link href="auth.wikimedia.org" rel="dns-prefetch"/>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_by_revenue rootpage-List_of_largest_companies_by_revenue skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-sitesupport-2">
           <a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-createaccount-2">
           <a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory">
            <span>
             Create account
            </span>
           </a>
          </li>
          <li class="user-links-collapsible-item mw-list-item user-links-collapsible-item" id="pt-login-2">

In [34]:
table = scrap.find("table", class_ = "wikitable sortable sticky-header-multi sort-under")
title = table.find("tr") 
title_th = title.find_all("th")
tmp_title = [i.text.strip() for i in title_th]
tmp_title.remove("State-owned")
tmp_title.remove("Ref.")
title_finish = [i.replace("[note 1]", "") for i in tmp_title]
print(title_finish)

['Ranks', 'Name', 'Industry', 'Revenue', 'Profit', 'Employees', 'Headquarters']

In [45]:
import pandas as pd 

data = pd.DataFrame(columns = title_finish)
tr_row = table.find_all("tr")[2:]

for i in tr_row:
    rank = i.find_all("th")
    row = rank + i.find_all("td")
    row_data = [z.text.strip() for z in row if z.text.strip() != ""]
    print(row_data)

['1', 'Amazon', 'Retail Information technology', '$716,924', '$79,975', '1,576,000', 'United States', '[5]']
['2', 'Walmart', 'Retail', '$713,163', '$21,893', '2,100,000', '[6]']
['3', 'State Grid Corporation of China', 'Electricity', '$545,948', '$9,204', '1,361,423', 'China', '[7]']
['4', 'Saudi Aramco', 'Oil and gas', '$480,446', '$106,246', '73,311', 'Saudi Arabia', '[8]']
['5', 'China National Petroleum Corporation', '$476,000', '$25,250', '1,026,301', 'China', '[9]']
['6', 'China Petrochemical Corporation', '$429,700', '$9,393', '513,434', '[10]']
['7', 'Apple', 'Information technology', '$416,000', '$112,000', '166,000', 'United States', '[11]']
['8', 'Alphabet', 'Information technology', '$402,872', '$132,170', '190,820', '[12]']
['9', 'UnitedHealth Group', 'Healthcare', '$400,278', '$14,405', '400,000', '[13]']
['10', 'Berkshire Hathaway', 'Financials', '$371,433', '$88,995', '392,400', '[14]']
['11', 'CVS Health', 'Healthcare', '$357,776', '$8,344', '259,500', '[15]']
['12', 'Volkswagen Group', 'Automotive', '$348,408', '$17,945', '684,025', 'Germany', '[16]']
['13', 'ExxonMobil', 'Oil and gas', '$344,582', '$36,010', '61,500', 'United States', '[17]']
['14', 'Vitol', 'Commodities', '$331,000', '$13,000', '1,560', 'Switzerland', '[18][19]']
['15', 'Shell', 'Oil and gas', '$323,183', '$19,359', '103,000', 'United Kingdom', '[20]']
['16', 'China State Construction Engineering', 'Construction', '$320,431', '$4,272', '382,894', 'China', '[21]']
['17', 'Toyota', 'Automotive', '$312,018', '$34,214', '380,793', 'Japan', '[22]']
['18', 'McKesson', 'Healthcare', '$308,951', '$3,002', '48,000', 'United States', '[23]']
['19', 'Microsoft', 'Information technology', '$281,700', '$101,800', '228,000', '[24]']
['20', 'Cencora', 'Healthcare', '$262,173', '$1,745', '44,000', '[25]']
['21', 'Trafigura', 'Commodities', '$244,280', '$7,393', '12,479', 'Singapore', '[26]']
['22', 'Costco', 'Retail', '$242,290', '$6,292', '316,000', 'United States', '[27]']
['23', 'JPMorgan Chase', 'Financials', '$239,425', '$49,552', '309,926', '[28]']
['24', 'Industrial and Commercial Bank of China', '$222,484', '$51,417', '419,252', 'China', '[29]']
['25', 'TotalEnergies', 'Oil and gas', '$218,945', '$21,384', '102,579', 'France', '[30]']
['26', 'Glencore', 'Commodities', '$217,829', '$4,280', '83,426', 'Switzerland', '[31]']
['27', 'Nvidia', 'Semiconductors', '$215,938', '$120,067', '36,000', 'United States', '[32]']
['28', 'BP', 'Oil and gas', '$213,032', '$15,239', '79,400', 'United Kingdom', '[33]']
['29', 'Cardinal Health', 'Healthcare', '$205,012', '$261', '47,520', 'United States', '[34]']
['30', 'Stellantis', 'Automotive', '$204,908', '$20,103', '258,275', 'Netherlands', '[35]']
['31', 'Chevron', 'Oil and gas', '$200,949', '$21,369', '45,600', 'United States', '[36]']
['32', 'China Construction Bank', 'Financials', '$199,826', '$46,990', '376,871', 'China', '[37]']
['33', 'Samsung Electronics', 'Electronics', '$198,257', '$11,082', '267,860', 'South Korea', '[38]']
['34', 'Foxconn', '$197,876', '$4,563', '621,393', 'Taiwan', '[39]']
['35', 'Cigna', 'Healthcare', '$195,265', '$5,164', '71,413', 'United States', '[40]']
['36', 'Agricultural Bank of China', 'Financials', '$192,398', '$38,049', '451,003', 'China', '[41]']
['37', 'Schwarz Gruppe', 'Retail', '$180,576', '$16,988', '595,000', 'Germany', '[42]']
['38', 'China Railway Engineering Corporation', 'Construction', '$178,563', '$2,152', '314,149', 'China', '[43]']
['39', 'Cargill', 'Conglomerate', '$177,000', '$17,641', '160,000', 'United States', '[44]']
['40', 'Ford Motor Company', 'Automotive', '$176,191', '$4,347', '177,000', '[45]']
['41', 'Bank of China', 'Financials', '$172,328', '$32,758', '306,931', 'China', '[46]']
['42', 'Bank of America', '$171,912', '$26,515', '212,985', 'United States', '[47]']
['43', 'General Motors', 'Automotive', '$171,842', '$10,127', '163,000', '[48]']
['44', 'Elevance Health', 'Healthcare', '$171,340', '$5,987', '104,900', '[49]']
['45', 'BMW Group', 'Automotive', '$168,103', '$12,205', '154,950', 'Germany', '[50]']
['46', 'Mercedes-Benz Group', 'Automotive', '$165,638', '$15,417', '166,056', 'Germany', '[51]']
['47', 'Meta Platforms', 'Social media', '$164,500', '$62,360', '78,450', 'United States', '[52]']
['48', 'China Railway Construction Corporation', 'Construction', '$160,847', '$1,701', '336,433', 'China', '[53]']
['49', 'Baowu', 'Steel', '$157,216', '$2,494', '258,697', '[54]']
['50', 'Citigroup', 'Financials', '$156,820', '$9,228', '237,925', 'United States', '[55]']

In [55]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"
headers = {"User-Agent": "testing"}

response = requests.get(url, headers=headers)
tabel_web = pd.read_html(response.text)
df = tabel_web[0] 
df.columns = df.columns.droplevel(1)
df.columns = [col.replace("[note 1]", "").strip() for col in df.columns]
df = df.drop(columns=['State-owned', 'Ref.'])
df

/var/folders/q2/2h4p204s56d3vhv_jx5hmc6m0000gn/T/ipykernel_19322/3981052747.py:8: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tabel_web = pd.read_html(response.text)

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters
0,1,Amazon,Retail Information technology,"$716,924","$79,975",1576000,United States
1,2,Walmart,Retail,"$713,163","$21,893",2100000,United States
2,3,State Grid Corporation of China,Electricity,"$545,948","$9,204",1361423,China
3,4,Saudi Aramco,Oil and gas,"$480,446","$106,246",73311,Saudi Arabia
4,5,China National Petroleum Corporation,Oil and gas,"$476,000","$25,250",1026301,China
5,6,China Petrochemical Corporation,Oil and gas,"$429,700","$9,393",513434,China
6,7,Apple,Information technology,"$416,000","$112,000",166000,United States
7,8,Alphabet,Information technology,"$402,872","$132,170",190820,United States
8,9,UnitedHealth Group,Healthcare,"$400,278","$14,405",400000,United States
9,10,Berkshire Hathaway,Financials,"$371,433","$88,995",392400,United States
10,11,CVS Health,Healthcare,"$357,776","$8,344",259500,United States
11,12,Volkswagen Group,Automotive,"$348,408","$17,945",684025,Germany
12,13,ExxonMobil,Oil and gas,"$344,582","$36,010",61500,United States
13,14,Vitol,Commodities,"$331,000","$13,000",1560,Switzerland
14,15,Shell,Oil and gas,"$323,183","$19,359",103000,United Kingdom
15,16,China State Construction Engineering,Construction,"$320,431","$4,272",382894,China
16,17,Toyota,Automotive,"$312,018","$34,214",380793,Japan
17,18,McKesson,Healthcare,"$308,951","$3,002",48000,United States
18,19,Microsoft,Information technology,"$281,700","$101,800",228000,United States
19,20,Cencora,Healthcare,"$262,173","$1,745",44000,United States
20,21,Trafigura,Commodities,"$244,280","$7,393",12479,Singapore
21,22,Costco,Retail,"$242,290","$6,292",316000,United States
22,23,JPMorgan Chase,Financials,"$239,425","$49,552",309926,United States
23,24,Industrial and Commercial Bank of China,Financials,"$222,484","$51,417",419252,China
24,25,TotalEnergies,Oil and gas,"$218,945","$21,384",102579,France
25,26,Glencore,Commodities,"$217,829","$4,280",83426,Switzerland
26,27,Nvidia,Semiconductors,"$215,938","$120,067",36000,United States
27,28,BP,Oil and gas,"$213,032","$15,239",79400,United Kingdom
28,29,Cardinal Health,Healthcare,"$205,012",$261,47520,United States
29,30,Stellantis,Automotive,"$204,908","$20,103",258275,Netherlands
30,31,Chevron,Oil and gas,"$200,949","$21,369",45600,United States
31,32,China Construction Bank,Financials,"$199,826","$46,990",376871,China
32,33,Samsung Electronics,Electronics,"$198,257","$11,082",267860,South Korea
33,34,Foxconn,Electronics,"$197,876","$4,563",621393,Taiwan
34,35,Cigna,Healthcare,"$195,265","$5,164",71413,United States
35,36,Agricultural Bank of China,Financials,"$192,398","$38,049",451003,China
36,37,Schwarz Gruppe,Retail,"$180,576","$16,988",595000,Germany
37,38,China Railway Engineering Corporation,Construction,"$178,563","$2,152",314149,China
38,39,Cargill,Conglomerate,"$177,000","$17,641",160000,United States
39,40,Ford Motor Company,Automotive,"$176,191","$4,347",177000,United States
40,41,Bank of China,Financials,"$172,328","$32,758",306931,China
41,42,Bank of America,Financials,"$171,912","$26,515",212985,United States
42,43,General Motors,Automotive,"$171,842","$10,127",163000,United States
43,44,Elevance Health,Healthcare,"$171,340","$5,987",104900,United States
44,45,BMW Group,Automotive,"$168,103","$12,205",154950,Germany
45,46,Mercedes-Benz Group,Automotive,"$165,638","$15,417",166056,Germany
46,47,Meta Platforms,Social media,"$164,500","$62,360",78450,United States
47,48,China Railway Construction Corporation,Construction,"$160,847","$1,701",336433,China
48,49,Baowu,Steel,"$157,216","$2,494",258697,China
49,50,Citigroup,Financials,"$156,820","$9,228",237925,United States

In [57]:
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"
headers = {"User-Agent": "MyScraper/1.0 (your_email@example.com)"}

response = requests.get(url, headers=headers)
html_data = StringIO(response.text)
tabel_web = pd.read_html(html_data)
df = tabel_web[0]
df.columns = df.columns.droplevel(1)
df.columns = [col.replace("[note 1]", "").strip() for col in df.columns]
df = df.drop(columns=['State-owned', 'Ref.'])
df

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters
0,1,Amazon,Retail Information technology,"$716,924","$79,975",1576000,United States
1,2,Walmart,Retail,"$713,163","$21,893",2100000,United States
2,3,State Grid Corporation of China,Electricity,"$545,948","$9,204",1361423,China
3,4,Saudi Aramco,Oil and gas,"$480,446","$106,246",73311,Saudi Arabia
4,5,China National Petroleum Corporation,Oil and gas,"$476,000","$25,250",1026301,China
5,6,China Petrochemical Corporation,Oil and gas,"$429,700","$9,393",513434,China
6,7,Apple,Information technology,"$416,000","$112,000",166000,United States
7,8,Alphabet,Information technology,"$402,872","$132,170",190820,United States
8,9,UnitedHealth Group,Healthcare,"$400,278","$14,405",400000,United States
9,10,Berkshire Hathaway,Financials,"$371,433","$88,995",392400,United States
10,11,CVS Health,Healthcare,"$357,776","$8,344",259500,United States
11,12,Volkswagen Group,Automotive,"$348,408","$17,945",684025,Germany
12,13,ExxonMobil,Oil and gas,"$344,582","$36,010",61500,United States
13,14,Vitol,Commodities,"$331,000","$13,000",1560,Switzerland
14,15,Shell,Oil and gas,"$323,183","$19,359",103000,United Kingdom
15,16,China State Construction Engineering,Construction,"$320,431","$4,272",382894,China
16,17,Toyota,Automotive,"$312,018","$34,214",380793,Japan
17,18,McKesson,Healthcare,"$308,951","$3,002",48000,United States
18,19,Microsoft,Information technology,"$281,700","$101,800",228000,United States
19,20,Cencora,Healthcare,"$262,173","$1,745",44000,United States
20,21,Trafigura,Commodities,"$244,280","$7,393",12479,Singapore
21,22,Costco,Retail,"$242,290","$6,292",316000,United States
22,23,JPMorgan Chase,Financials,"$239,425","$49,552",309926,United States
23,24,Industrial and Commercial Bank of China,Financials,"$222,484","$51,417",419252,China
24,25,TotalEnergies,Oil and gas,"$218,945","$21,384",102579,France
25,26,Glencore,Commodities,"$217,829","$4,280",83426,Switzerland
26,27,Nvidia,Semiconductors,"$215,938","$120,067",36000,United States
27,28,BP,Oil and gas,"$213,032","$15,239",79400,United Kingdom
28,29,Cardinal Health,Healthcare,"$205,012",$261,47520,United States
29,30,Stellantis,Automotive,"$204,908","$20,103",258275,Netherlands
30,31,Chevron,Oil and gas,"$200,949","$21,369",45600,United States
31,32,China Construction Bank,Financials,"$199,826","$46,990",376871,China
32,33,Samsung Electronics,Electronics,"$198,257","$11,082",267860,South Korea
33,34,Foxconn,Electronics,"$197,876","$4,563",621393,Taiwan
34,35,Cigna,Healthcare,"$195,265","$5,164",71413,United States
35,36,Agricultural Bank of China,Financials,"$192,398","$38,049",451003,China
36,37,Schwarz Gruppe,Retail,"$180,576","$16,988",595000,Germany
37,38,China Railway Engineering Corporation,Construction,"$178,563","$2,152",314149,China
38,39,Cargill,Conglomerate,"$177,000","$17,641",160000,United States
39,40,Ford Motor Company,Automotive,"$176,191","$4,347",177000,United States
40,41,Bank of China,Financials,"$172,328","$32,758",306931,China
41,42,Bank of America,Financials,"$171,912","$26,515",212985,United States
42,43,General Motors,Automotive,"$171,842","$10,127",163000,United States
43,44,Elevance Health,Healthcare,"$171,340","$5,987",104900,United States
44,45,BMW Group,Automotive,"$168,103","$12,205",154950,Germany
45,46,Mercedes-Benz Group,Automotive,"$165,638","$15,417",166056,Germany
46,47,Meta Platforms,Social media,"$164,500","$62,360",78450,United States
47,48,China Railway Construction Corporation,Construction,"$160,847","$1,701",336433,China
48,49,Baowu,Steel,"$157,216","$2,494",258697,China
49,50,Citigroup,Financials,"$156,820","$9,228",237925,United States