Data Tabular

In [18]:
import pandas as pd
from autogluon.tabular import TabularPredictor

data_tabular = pd.DataFrame({
    'pendapatan_bulanan': [5000, 7000, 4500, 8000, 12000, 4000, 6500, 9000, 5500, 11000, 7200, 8100],
    'skor_kredit': [600, 750, 580, 800, 850, 550, 700, 820, 620, 830, 710, 790],
    'pekerjaan': ['Kontrak', 'Tetap', 'Kontrak', 'Tetap', 'Tetap', 
                  'Kontrak', 'Tetap', 'Tetap', 'Kontrak', 'Tetap', 
                  'Kontrak', 'Tetap'],
    'status_pinjaman': ['Ditolak', 'Disetujui', 'Ditolak', 'Disetujui', 
                        'Disetujui', 'Ditolak', 'Disetujui', 'Disetujui', 
                        'Ditolak', 'Disetujui', 'Ditolak', 'Disetujui'] # Target
})

data_tabular.head()

   pendapatan_bulanan  skor_kredit pekerjaan status_pinjaman
0                5000          600   Kontrak         Ditolak
1                7000          750     Tetap       Disetujui
2                4500          580   Kontrak         Ditolak
3                8000          800     Tetap       Disetujui
4               12000          850     Tetap       Disetujui

In [19]:
from sklearn.metrics import mean_absolute_percentage_error

nama_kolom_target = 'status_pinjaman'

# Pemisahan Data: 9 baris untuk pelatihan, 3 baris untuk pengujian
train_data = data_tabular.iloc[:-3].copy()
test_data = data_tabular.iloc[-3:].copy()

print("--- Memulai Pelatihan Fase Evaluasi ---")
predictor_eval = TabularPredictor(
    label=nama_kolom_target, 
    eval_metric='accuracy'
).fit(
    train_data=train_data, 
    time_limit=60, 
    presets='medium_quality'
)

hasil_benchmark = predictor_eval.leaderboard(test_data, silent=True)
print("\n--- TABEL BENCHMARKING (EVALUASI SKOR MODEL) ---")
print(hasil_benchmark[['model', 'score_test', 'score_val']])

No path specified. Models will be saved in: "AutogluonModels/ag-20260518_093035"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.7
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.2.0: Tue Nov 18 21:03:25 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T8122
CPU Count:          8
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       2.00 GB / 8.00 GB (25.1%)
Disk Space Avail:   6.59 GB / 228.27 GB (2.9%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'

--- Memulai Pelatihan Fase Evaluasi ---

Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Applications/MAMP/htdocs/local/kodingakademi/Python/python 4/ai engineer/AutogluonModels/ag-20260518_093035"
Train Data Rows:    9
Train Data Columns: 3
Label Column:       status_pinjaman
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['Ditolak', 'Disetujui']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Warning: Updated label_count_threshold from 10 to 4 to avoid cutting too many classes.
Selected class <--> label mapping:  class 1 = Ditolak, class 0 = Disetujui
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Ditolak) vs negative (Disetujui) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2081.78 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 2 | ['pendapatan_bulanan', 'skor_kredit']
		('object', []) : 1 | ['pekerjaan']
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 2 | ['pendapatan_bulanan', 'skor_kredit']
		('int', ['bool']) : 1 | ['pekerjaan']
	0.0s = Fit runtime
	3 features in original data used to generate 3 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 7, Val Rows: 2
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 59.98s of the 59.97s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.0/2.0 GB
	0.5	 = Validation score   (accuracy)
	0.22s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 59.76s of the 59.75s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.0/2.1 GB
	0.5	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 59.62s of the 59.62s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 59.44s of the 59.44s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 59.26s of the 59.26s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 59.16s of the 59.16s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 58.98s of the 58.98s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 58.80s of the 58.80s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.0/2.2 GB
No improvement since epoch 0: early stopping
	0.5	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 58.64s of the 58.64s of remaining time.
	Fitting with cpus=8, gpus=0
	0.5	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 58.56s of the 58.56s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.0/2.1 GB
	1.0	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 58.46s of the 58.46s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.1/2.1 GB
	1.0	 = Validation score   (accuracy)
	0.17s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.98s of the 58.29s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/2.1 GB
	Ensemble Weights: {'LightGBMLarge': 1.0}
	1.0	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.77s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4183.8 rows/s (2 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (2 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Applications/MAMP/htdocs/local/kodingakademi/Python/python 4/ai engineer/AutogluonModels/ag-20260518_093035")

--- TABEL BENCHMARKING (EVALUASI SKOR MODEL) ---
                  model  score_test  score_val
0              CatBoost    1.000000        1.0
1         LightGBMLarge    0.666667        1.0
2              LightGBM    0.666667        0.5
3            LightGBMXT    0.666667        0.5
4   WeightedEnsemble_L2    0.666667        1.0
5        NeuralNetTorch    0.666667        1.0
6               XGBoost    0.666667        0.5
7      RandomForestGini    0.666667        1.0
8        ExtraTreesEntr    0.666667        1.0
9        ExtraTreesGini    0.666667        1.0
10     RandomForestEntr    0.666667        1.0
11      NeuralNetFastAI    0.333333        0.5

In [ ]:
# Pelatihan ulang menggunakan SELURUH data (12 baris) agar model memiliki wawasan maksimal
print("\n--- Memulai Pelatihan Penuh (Full Data) ---")
predictor_final = TabularPredictor(
    label=nama_kolom_target, 
    eval_metric='accuracy'
).fit(
    train_data=data_tabular, # Menggunakan DataFrame utuh
    time_limit=60, 
    presets='medium_quality'
)

# Pembuatan Data Baru (Data masa depan yang belum memiliki status pinjaman)
data_baru = pd.DataFrame({
    'pendapatan_bulanan': [15000, 3000],
    'skor_kredit': [880, 500],
    'pekerjaan': ['Tetap', 'Kontrak']
})

# Prediksi menggunakan model final
prediksi_final = predictor_final.predict(data_baru)
data_baru['prediksi_status'] = prediksi_final

print("\n--- HASIL PREDIKSI DATA BARU ---")
print(data_baru)

No path specified. Models will be saved in: "AutogluonModels/ag-20260518_093037"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.7
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.2.0: Tue Nov 18 21:03:25 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T8122
CPU Count:          8
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       2.13 GB / 8.00 GB (26.7%)
Disk Space Avail:   6.59 GB / 228.27 GB (2.9%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Presets specified: ['medium_quality']
Using hyperparameters preset: hyperparameters='default'

--- Memulai Pelatihan Penuh (Full Data) ---

Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Applications/MAMP/htdocs/local/kodingakademi/Python/python 4/ai engineer/AutogluonModels/ag-20260518_093037"
Train Data Rows:    12
Train Data Columns: 3
Label Column:       status_pinjaman
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['Ditolak', 'Disetujui']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Warning: Updated label_count_threshold from 10 to 5 to avoid cutting too many classes.
Selected class <--> label mapping:  class 1 = Ditolak, class 0 = Disetujui
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Ditolak) vs negative (Disetujui) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2101.41 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 2 | ['pendapatan_bulanan', 'skor_kredit']
		('object', []) : 1 | ['pekerjaan']
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 2 | ['pendapatan_bulanan', 'skor_kredit']
		('int', ['bool']) : 1 | ['pekerjaan']
	0.0s = Fit runtime
	3 features in original data used to generate 3 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 9, Val Rows: 3
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 59.98s of the 59.98s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.0/2.0 GB
	0.6667	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 59.84s of the 59.84s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.0/2.0 GB
	0.6667	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 59.70s of the 59.70s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 59.53s of the 59.53s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 59.35s of the 59.35s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 59.29s of the 59.28s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 59.10s of the 59.10s of remaining time.
	Fitting with cpus=8, gpus=0
	1.0	 = Validation score   (accuracy)
	0.17s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 58.91s of the 58.90s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.0/1.9 GB
No improvement since epoch 0: early stopping
	0.6667	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 58.82s of the 58.82s of remaining time.
	Fitting with cpus=8, gpus=0
	0.6667	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 58.75s of the 58.74s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.0/1.9 GB
	1.0	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 58.68s of the 58.68s of remaining time.
	Fitting with cpus=8, gpus=0, mem=0.1/1.9 GB
	1.0	 = Validation score   (accuracy)
	0.17s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.98s of the 58.51s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/1.9 GB
	Ensemble Weights: {'LightGBMLarge': 1.0}
	1.0	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.53s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4950.0 rows/s (3 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (3 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Applications/MAMP/htdocs/local/kodingakademi/Python/python 4/ai engineer/AutogluonModels/ag-20260518_093037")

--- HASIL PREDIKSI DATA BARU ---
   pendapatan_bulanan  skor_kredit pekerjaan prediksi_status
0               15000          880     Tetap       Disetujui
1                3000          500   Kontrak         Ditolak

Data Time Series

In [21]:
import numpy as np
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
import warnings
warnings.filterwarnings('ignore')

periode_hari = 30
df_mentah = pd.DataFrame({
    'id_toko': ['Cabang_A'] * periode_hari,
    'tanggal': pd.date_range(start='2026-01-01', periods=periode_hari, freq='D'),
    'penjualan': np.random.randint(100, 500, size=periode_hari)
})

df_mentah.head()

    id_toko    tanggal  penjualan
0  Cabang_A 2026-01-01        348
1  Cabang_A 2026-01-02        280
2  Cabang_A 2026-01-03        423
3  Cabang_A 2026-01-04        417
4  Cabang_A 2026-01-05        370

In [22]:
ts_full = TimeSeriesDataFrame.from_data_frame(
    df_mentah,
    id_column="id_toko",
    timestamp_column="tanggal"
)
ts_full.head()

                     penjualan
item_id  timestamp
Cabang_A 2026-01-01        348
         2026-01-02        280
         2026-01-03        423
         2026-01-04        417
         2026-01-05        370

In [23]:
pred_length = 5 

# Memotong 5 hari terakhir untuk keperluan Evaluasi (Train: 25 hari pertama)
ts_train = ts_full.slice_by_timestep(None, -pred_length)
ts_test = ts_full # AutoGluon secara otomatis akan menguji performa pada bagian akhir data ini

print("--- Memulai Pelatihan Time Series (Fase Evaluasi) ---")
ts_predictor_eval = TimeSeriesPredictor(
    prediction_length=pred_length,
    target="penjualan",
    eval_metric="MAE"
).fit(
    ts_train,
    presets="fast_training",
    time_limit=60
)

# Mendapatkan skor akurasi model
ts_benchmark = ts_predictor_eval.leaderboard(ts_test, silent=True)
print("\n--- TABEL BENCHMARKING TIME SERIES ---")
print(ts_benchmark[['model', 'score_test', 'score_val']])

No path specified. Models will be saved in: "AutogluonModels/ag-20260518_093039"
Beginning AutoGluon training... Time limit = 60s
AutoGluon will save models to '/Applications/MAMP/htdocs/local/kodingakademi/Python/python 4/ai engineer/AutogluonModels/ag-20260518_093039'
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.7
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.2.0: Tue Nov 18 21:03:25 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T8122
CPU Count:          8
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       1.93 GB / 8.00 GB (24.1%)
Disk Space Avail:   6.58 GB / 228.27 GB (2.9%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Setting presets to: fast_training

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': MAE,
 'hyperparameters': 'very_light',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 5,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'penjualan',
 'time_limit': 60,
 'verbosity': 2}

Inferred time series frequency: 'D'
Provided train_data has 25 rows, 1 time series. Median time series length is 25 (min=25, max=25).

Provided data contains following columns:
	target: 'penjualan'

AutoGluon will gauge predictive performance using evaluation metric: 'MAE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-05-18 17:30:39
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model Naive. Training for up to 8.6s of the 60.0s of remaining time.

--- Memulai Pelatihan Time Series (Fase Evaluasi) ---

	-158.0000     = Validation score (-MAE)
	0.00    s     = Training runtime
	2.57    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive. Training for up to 9.6s of the 57.4s of remaining time.
	-124.4000     = Validation score (-MAE)
	0.00    s     = Training runtime
	0.98    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular. Training for up to 11.3s of the 56.4s of remaining time.
	-185.3000     = Validation score (-MAE)
	0.28    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 14.0s of the 56.1s of remaining time.
	-120.3200     = Validation score (-MAE)
	0.21    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 18.6s of the 55.9s of remaining time.
	-117.0388     = Validation score (-MAE)
	0.00    s     = Training runtime
	1.13    s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 27.4s of the 54.8s of remaining time.
	-106.3766     = Validation score (-MAE)
	0.00    s     = Training runtime
	1.63    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble. Training for up to 53.1s.
	Ensemble weights: {'ETS': 0.26, 'SeasonalNaive': 0.35, 'Theta': 0.38}
	-95.8928      = Validation score (-MAE)
	0.06    s     = Training runtime
	3.75    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 6.94 s
Best model: WeightedEnsemble
Best model score: -95.8928
Additional data provided, testing on additional data. Resulting leaderboard will be sorted according to test score (`score_test`).

--- TABEL BENCHMARKING TIME SERIES ---
              model  score_test   score_val
0     DirectTabular  -56.989410 -120.320001
1               ETS  -66.192211 -117.038782
2             Theta  -88.245267 -106.376602
3  WeightedEnsemble -105.292674  -95.892822
4             Naive -117.400000 -158.000000
5     SeasonalNaive -199.000000 -124.400000
6  RecursiveTabular -207.998071 -185.300000

In [24]:
# Pelatihan diulang menggunakan 100% data historis (30 hari utuh)
print("\n--- Memulai Pelatihan Time Series (Full Data) ---")
ts_predictor_final = TimeSeriesPredictor(
    prediction_length=pred_length,
    target="penjualan",
    eval_metric="MAE"
).fit(
    ts_full, # Menggunakan data historis lengkap
    presets="fast_training",
    time_limit=60
)

# Melakukan peramalan (Forecasting) murni 5 hari ke masa depan
hasil_forecast = ts_predictor_final.predict(ts_full)

print("\n--- HASIL FORECASTING MASA DEPAN (5 Hari Kedepan) ---")
print(hasil_forecast[['mean', '0.1', '0.9']])

No path specified. Models will be saved in: "AutogluonModels/ag-20260518_093457"
Beginning AutoGluon training... Time limit = 60s
AutoGluon will save models to '/Applications/MAMP/htdocs/local/kodingakademi/Python/python 4/ai engineer/AutogluonModels/ag-20260518_093457'
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.7
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.2.0: Tue Nov 18 21:03:25 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T8122
CPU Count:          8
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       1.48 GB / 8.00 GB (18.5%)
Disk Space Avail:   6.59 GB / 228.27 GB (2.9%)
	WARNING: Available disk space is low and there is a risk that AutoGluon will run out of disk during fit, causing an exception.
	We recommend a minimum available disk space of 10 GB, and large datasets may require more.
===================================================
Setting presets to: fast_training

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': MAE,
 'hyperparameters': 'very_light',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 5,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'penjualan',
 'time_limit': 60,
 'verbosity': 2}

Inferred time series frequency: 'D'
Provided train_data has 30 rows, 1 time series. Median time series length is 30 (min=30, max=30).

Provided data contains following columns:
	target: 'penjualan'

AutoGluon will gauge predictive performance using evaluation metric: 'MAE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-05-18 17:34:57
Models that will be trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model Naive. Training for up to 8.6s of the 60.0s of remaining time.

--- Memulai Pelatihan Time Series (Full Data) ---

	-117.4000     = Validation score (-MAE)
	0.01    s     = Training runtime
	1.74    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive. Training for up to 9.7s of the 58.2s of remaining time.
	-199.0000     = Validation score (-MAE)
	0.01    s     = Training runtime
	0.97    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular. Training for up to 11.4s of the 57.2s of remaining time.
	-213.4154     = Validation score (-MAE)
	0.30    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 14.2s of the 56.8s of remaining time.
	-66.9400      = Validation score (-MAE)
	0.16    s     = Training runtime
	0.01    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 18.9s of the 56.7s of remaining time.
	-66.1922      = Validation score (-MAE)
	0.00    s     = Training runtime
	1.27    s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 27.7s of the 55.4s of remaining time.
	-88.2453      = Validation score (-MAE)
	0.01    s     = Training runtime
	2.37    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble. Training for up to 53.0s.
	Ensemble weights: {'DirectTabular': 0.25, 'ETS': 0.49, 'Naive': 0.26}
	-52.8008      = Validation score (-MAE)
	0.07    s     = Training runtime
	3.02    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 7.05 s
Best model: WeightedEnsemble
Best model score: -52.8008
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

--- HASIL FORECASTING MASA DEPAN (5 Hari Kedepan) ---
                           mean         0.1         0.9
item_id  timestamp
Cabang_A 2026-01-31  335.706938  173.507708  497.906167
         2026-02-01  335.706938  136.670305  534.743570
         2026-02-02  335.706938  108.403971  563.009904
         2026-02-03  335.706938   84.574349  586.839526
         2026-02-04  335.706938   63.580031  607.833844

In [ ]:
hasil_forecast = ts_predictor_final.predict(ts_full, model='DirectTabular')
print(hasil_forecast[['mean', '0.1', '0.9']])

                           mean         0.1         0.9
item_id  timestamp
Cabang_A 2026-01-31  316.931976  158.508103  475.355849
         2026-02-01  316.931976   92.886787  540.977166
         2026-02-02  316.931976   42.533779  591.330173
         2026-02-03  316.931976    0.084230  633.779722
         2026-02-04  316.931976  -37.314573  671.178526