In [11]:
import pandas as pd 

data1 = pd.read_csv('tangsel_covid19.csv')
data1

   Unnamed: 0  ODP  PDP  POSITIF  SEMBUH  MENINGGAL
0   3/26/2020  204   89       17       0          4
1   3/27/2020  207   99       17       0          4
2   3/29/2020  256  119       28       0          4
3   3/30/2020  262  123       31       0          6
4   3/31/2020  308  134       34       2          6
5    4/1/2020  336  139       38       2          6
6    4/2/2020  371  156       40       2         10
7    4/5/2020  416  170       42       2         10
8    4/6/2020  450  184       43       2         11
9    4/8/2020  525  196       44       2         13
10  4/11/2020  600  230       47       2         15
11  4/12/2020  606  231       49       2         16
12  4/13/2020  630  239       50       3         16
13  4/14/2020  629  245       44       9         16

In [12]:
data2 = pd.read_csv('tangsel_covid19.csv', header=None)
data2

            0    1    2        3       4          5
0         NaN  ODP  PDP  POSITIF  SEMBUH  MENINGGAL
1   3/26/2020  204   89       17       0          4
2   3/27/2020  207   99       17       0          4
3   3/29/2020  256  119       28       0          4
4   3/30/2020  262  123       31       0          6
5   3/31/2020  308  134       34       2          6
6    4/1/2020  336  139       38       2          6
7    4/2/2020  371  156       40       2         10
8    4/5/2020  416  170       42       2         10
9    4/6/2020  450  184       43       2         11
10   4/8/2020  525  196       44       2         13
11  4/11/2020  600  230       47       2         15
12  4/12/2020  606  231       49       2         16
13  4/13/2020  630  239       50       3         16
14  4/14/2020  629  245       44       9         16

In [13]:
data1.columns = ['Tanggal', 'ODP', 'PDP', 'Kasus Positif', 'Kasus Sembuh','Kasus Meninggal']
data1

      Tanggal  ODP  PDP  Kasus Positif  Kasus Sembuh  Kasus Meninggal
0   3/26/2020  204   89             17             0                4
1   3/27/2020  207   99             17             0                4
2   3/29/2020  256  119             28             0                4
3   3/30/2020  262  123             31             0                6
4   3/31/2020  308  134             34             2                6
5    4/1/2020  336  139             38             2                6
6    4/2/2020  371  156             40             2               10
7    4/5/2020  416  170             42             2               10
8    4/6/2020  450  184             43             2               11
9    4/8/2020  525  196             44             2               13
10  4/11/2020  600  230             47             2               15
11  4/12/2020  606  231             49             2               16
12  4/13/2020  630  239             50             3               16
13  4/14/2020  629  245             44             9               16

In [21]:
print(data1.shape)
print(data1.info())
print(data1.head())
print(data1.tail())
print(data1.tail(3))

(14, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Tanggal          14 non-null     object
 1   ODP              14 non-null     int64
 2   PDP              14 non-null     int64
 3   Kasus Positif    14 non-null     int64
 4   Kasus Sembuh     14 non-null     int64
 5   Kasus Meninggal  14 non-null     int64
dtypes: int64(5), object(1)
memory usage: 804.0+ bytes
None
     Tanggal  ODP  PDP  Kasus Positif  Kasus Sembuh  Kasus Meninggal
0  3/26/2020  204   89             17             0                4
1  3/27/2020  207   99             17             0                4
2  3/29/2020  256  119             28             0                4
3  3/30/2020  262  123             31             0                6
4  3/31/2020  308  134             34             2                6
      Tanggal  ODP  PDP  Kasus Positif  Kasus Sembuh  Kasus Meninggal
9    4/8/2020  525  196             44             2               13
10  4/11/2020  600  230             47             2               15
11  4/12/2020  606  231             49             2               16
12  4/13/2020  630  239             50             3               16
13  4/14/2020  629  245             44             9               16
      Tanggal  ODP  PDP  Kasus Positif  Kasus Sembuh  Kasus Meninggal
11  4/12/2020  606  231             49             2               16
12  4/13/2020  630  239             50             3               16
13  4/14/2020  629  245             44             9               16