DATAFRAME CONDITIONAL

In [46]:
import pandas as pd 

df = pd.DataFrame({
    "population" : [10,22,33,44],
    "gdp" : [11,99,22,33],
    "surface area": [88,66,77,44],
    "hdi" : [11,22,33,44],
    "continent" : [19,18,17,12]
}, columns=["population","gdp","surface area","hdi","continent"], 
                  index = ["canada", "france", "germany", "italy"])

df

         population  gdp  surface area  hdi  continent
canada           10   11            88   11         19
france           22   99            66   22         18
germany          33   22            77   33         17
italy            44   33            44   44         12

In [47]:
# kondisional dataframe

print("logic 1 : ")
print(df["population"] > 30)
print("logic 2 : ")
print(df.loc[df["population"] > 30])
print("logic 3 : ")
print(df.loc[df["population"] > 30, "population"])

logic 1 :
canada     False
france     False
germany     True
italy       True
Name: population, dtype: bool
logic 2 :
         population  gdp  surface area  hdi  continent
germany          33   22            77   33         17
italy            44   33            44   44         12
logic 3 :
germany    33
italy      44
Name: population, dtype: int64

In [48]:
# filter kondisi dataframe

logic = df[df["population"] > 20]
print(logic)

         population  gdp  surface area  hdi  continent
france           22   99            66   22         18
germany          33   22            77   33         17
italy            44   33            44   44         12

In [49]:
# filter multi kondisi dataframe

logic2 = df[(df["population"] > 40) & (df["surface area"] > 10)]
print(logic2)

       population  gdp  surface area  hdi  continent
italy          44   33            44   44         12

In [50]:
# delete index / line data dataframe 

print("del col : ")
print(df.drop(columns="continent"))
print(df.drop(["population", "gdp"], axis="columns"))
print(df.drop(["population", "gdp"], axis=1))
print(df.drop(["germany", "italy"], axis=0))

del col :
         population  gdp  surface area  hdi
canada           10   11            88   11
france           22   99            66   22
germany          33   22            77   33
italy            44   33            44   44
         surface area  hdi  continent
canada             88   11         19
france             66   22         18
germany            77   33         17
italy              44   44         12
         surface area  hdi  continent
canada             88   11         19
france             66   22         18
germany            77   33         17
italy              44   44         12
        population  gdp  surface area  hdi  continent
canada          10   11            88   11         19
france          22   99            66   22         18

In [51]:
# broadcasting dataframe 

print(df["population"] + 2)

canada     12
france     24
germany    35
italy      46
Name: population, dtype: int64

In [52]:
# biner operation dataframe

series = pd.Series([10,50], index=['gdp', 'hdi'])
df[["gdp", "hdi"]] + series

         gdp  hdi
canada    21   61
france   109   72
germany   32   83
italy     43   94

MODIFICATION DATAFRAME

In [54]:
# add data column with series

series = pd.Series([11,89,22,25], index = ["canada", "france", "germany", "italy"])
df["new1"] = series
df

         population  gdp  surface area  hdi  continent  new1
canada           10   11            88   11         19    11
france           22   99            66   22         18    89
germany          33   22            77   33         17    22
italy            44   33            44   44         12    25

In [55]:
# add data column with operation

df["new2"] = df["population"] * df["gdp"]
df

         population  gdp  surface area  hdi  continent  new1  new2
canada           10   11            88   11         19    11   110
france           22   99            66   22         18    89  2178
germany          33   22            77   33         17    22   726
italy            44   33            44   44         12    25  1452

In [56]:
# change column name 

df = df.rename(columns={"new1" : "ganti1"})
df

         population  gdp  surface area  hdi  continent  ganti1  new2
canada           10   11            88   11         19      11   110
france           22   99            66   22         18      89  2178
germany          33   22            77   33         17      22   726
italy            44   33            44   44         12      25  1452

In [57]:
# change index name

df = df.rename(index={"germany" : "indonesia"})
df

           population  gdp  surface area  hdi  continent  ganti1  new2
canada             10   11            88   11         19      11   110
france             22   99            66   22         18      89  2178
indonesia          33   22            77   33         17      22   726
italy              44   33            44   44         12      25  1452

In [ ]:
# change column and index name

df = df.rename(
    columns={
        "new2" : "ganti2"
    },
    index={
        "italy" : "kalimantan"
    }
)

df

,population,gdp,surface area,hdi,continent,ganti1,ganti2,new3
canada,10,11,88,11,19,100,11,110
france,22,99,66,22,18,100,89,2178
indonesia,33,22,77,33,17,100,22,726
kalimantan,44,33,44,44,12,100,25,1452