DATA DATAFRAME

In [2]:
import pandas as pd 

data = [10,4,19,20,40]
df = pd.DataFrame(data)
df

    0
0  10
1   4
2  19
3  20
4  40

In [3]:
# dataframe with list 2 dimension

data = [
    [10,9,22],
    [20,11,23]
]

df = pd.DataFrame(data)
df

    0   1   2
0  10   9  22
1  20  11  23

In [4]:
# dataframe with key and value

df = pd.DataFrame({
    "population" : [10,22,33,44],
    "gdp" : [11,99,22,33],
    "surface area": [88,66,77,44],
    "hdi" : [11,22,33,44],
    "continent" : [19,18,17,12]
}, columns=["population","gdp","surface area","hdi","continent"])

df

   population  gdp  surface area  hdi  continent
0          10   11            88   11         19
1          22   99            66   22         18
2          33   22            77   33         17
3          44   33            44   44         12

In [5]:
# set index dataframe

df.index = ["canada", "france", "germany", "italy"]
df

         population  gdp  surface area  hdi  continent
canada           10   11            88   11         19
france           22   99            66   22         18
germany          33   22            77   33         17
italy            44   33            44   44         12

In [6]:
# check dataframe columns name

df.columns

Index(['population', 'gdp', 'surface area', 'hdi', 'continent'], dtype='object')

In [7]:
# select column data

df[["population", "gdp"]]

         population  gdp
canada           10   11
france           22   99
germany          33   22
italy            44   33

In [8]:
# select line data

print("with loc : ")
print(df.loc["canada"])
print("with iloc : ")
print(df.iloc[0])

with loc :
population      10
gdp             11
surface area    88
hdi             11
continent       19
Name: canada, dtype: int64
with iloc :
population      10
gdp             11
surface area    88
hdi             11
continent       19
Name: canada, dtype: int64

In [9]:
# slicing line data

print("with loc : ")
print(df.loc["canada" : "germany"])
print("with iloc : ")
print(df.iloc[0 : 3])

with loc :
         population  gdp  surface area  hdi  continent
canada           10   11            88   11         19
france           22   99            66   22         18
germany          33   22            77   33         17
with iloc :
         population  gdp  surface area  hdi  continent
canada           10   11            88   11         19
france           22   99            66   22         18
germany          33   22            77   33         17

In [10]:
# slicing line and column data

print("with loc : ")
print(df.loc["canada" : "germany", "population" : "hdi"])
print("with iloc : ")
print(df.iloc[0 : 3, 0 : 4])

with loc :
         population  gdp  surface area  hdi
canada           10   11            88   11
france           22   99            66   22
germany          33   22            77   33
with iloc :
         population  gdp  surface area  hdi
canada           10   11            88   11
france           22   99            66   22
germany          33   22            77   33