DATA CLEANING WITH PANDAS

CHECK DATA NAN

In [93]:
import pandas as pd
import numpy as np

dict = {  
    'I':[100, 90, np.nan, 95],
    'II': [30, 45, 56, np.nan],
    'III':[np.nan, 40, 80, 98]
}
df = pd.DataFrame(dict)
df

       I    II   III
0  100.0  30.0   NaN
1   90.0  45.0  40.0
2    NaN  56.0  80.0
3   95.0   NaN  98.0

In [94]:
df.isnull()

       I     II    III
0  False  False   True
1  False  False  False
2   True  False  False
3  False   True  False

In [95]:
df.isnull().sum()

I      1
II     1
III    1
dtype: int64

In [96]:
df.notnull()

       I     II    III
0   True   True  False
1   True   True   True
2  False   True   True
3   True  False   True

FILL DATA NAN

In [97]:
dict = {  
    'I':[100, 90, np.nan, 95],
    'II': [30, 45, 56, np.nan],
    'III':[np.nan, 40, 80, 98]
}
df = pd.DataFrame(dict)
df

       I    II   III
0  100.0  30.0   NaN
1   90.0  45.0  40.0
2    NaN  56.0  80.0
3   95.0   NaN  98.0

In [98]:
df = df.fillna(1)
df

       I    II   III
0  100.0  30.0   1.0
1   90.0  45.0  40.0
2    1.0  56.0  80.0
3   95.0   1.0  98.0

In [99]:
df = df.fillna(df.mean())
df

       I    II   III
0  100.0  30.0   1.0
1   90.0  45.0  40.0
2    1.0  56.0  80.0
3   95.0   1.0  98.0

DELETE DATA NAN

In [100]:
dict = {  
    'I':[100, 90, np.nan, 95],
    'II': [30, 45, 56, np.nan],
    'III':[np.nan, 40, 80, 98]
}
df = pd.DataFrame(dict)
df

       I    II   III
0  100.0  30.0   NaN
1   90.0  45.0  40.0
2    NaN  56.0  80.0
3   95.0   NaN  98.0

In [101]:
df.dropna(axis=0)

      I    II   III
1  90.0  45.0  40.0

In [102]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

REPLACE VALUE NOT NAN

In [103]:
df = pd.DataFrame({
    'Sex': ['M', 'F', 'F', 'D', '?'],
    'Age': [29, 30, 24, 290, 25],
})
df

  Sex  Age
0   M   29
1   F   30
2   F   24
3   D  290
4   ?   25

In [104]:
df["Sex"].unique()

array(['M', 'F', 'D', '?'], dtype=object)

In [105]:
df["Sex"].value_counts()

Sex
F    2
M    1
D    1
?    1
Name: count, dtype: int64

In [106]:
df["Sex"].replace('D', 'F')

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

In [107]:
# assignment

data = pd.read_csv("penyakit_ginjal_kronik-1.csv")
data

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
0,0,48.0,80.0,1.020,1.0,0.0,NaN,Tidak Normal,121.0,36.0,...,44,7800,5.2,yes,yes,Tidak,baik,Tidak,Tidak,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,Tidak Normal,NaN,18.0,...,38,6000,NaN,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
2,2,62.0,80.0,1.010,2.0,3.0,Tidak Normal,Tidak Normal,423.0,53.0,...,31,7500,NaN,Tidak,yes,Tidak,buruk,Tidak,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,yes,Tidak,Tidak,buruk,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,Tidak Normal,Tidak Normal,106.0,26.0,...,35,7300,4.6,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd

In [118]:
data[data.isnull().any(axis=1)]

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
0,0,48.0,80.0,1.020,1.0,0.0,NaN,Tidak Normal,121.0,36.0,...,44,7800,5.2,yes,yes,Tidak,baik,Tidak,Tidak,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,Tidak Normal,NaN,18.0,...,38,6000,NaN,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
2,2,62.0,80.0,1.010,2.0,3.0,Tidak Normal,Tidak Normal,423.0,53.0,...,31,7500,NaN,Tidak,yes,Tidak,buruk,Tidak,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,Tidak Normal,Tidak Normal,106.0,26.0,...,35,7300,4.6,Tidak,Tidak,Tidak,baik,Tidak,Tidak,ckd
5,5,60.0,90.0,1.015,3.0,0.0,NaN,NaN,74.0,25.0,...,39,7800,4.4,yes,yes,Tidak,baik,yes,Tidak,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,350,65.0,70.0,1.025,0.0,0.0,NaN,NaN,85.0,20.0,...,43,9600,4.5,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
363,363,67.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,99.0,40.0,...,44,5900,5.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
365,365,24.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,93.0,46.0,...,NaN,10700,6.3,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
378,378,71.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,NaN,NaN,...,42,7700,5.5,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
381,381,71.0,70.0,1.025,0.0,0.0,NaN,NaN,79.0,47.0,...,40,5800,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd

In [108]:
backup = data.dropna()
backup

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,yes,Tidak,Tidak,buruk,yes,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,Normal,Normal,70.0,107.0,...,29,12100,3.7,yes,yes,Tidak,buruk,Tidak,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,Normal,Normal,380.0,60.0,...,32,4500,3.8,yes,yes,Tidak,buruk,yes,Tidak,ckd
14,14,68.0,80.0,1.010,3.0,2.0,Tidak Normal,Normal,157.0,90.0,...,16,11000,2.6,yes,yes,yes,buruk,yes,Tidak,ckd
20,20,61.0,80.0,1.015,2.0,0.0,Normal,Normal,173.0,148.0,...,24,9200,3.2,yes,yes,yes,buruk,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd

In [109]:
backup.columns

Index(['id', 'umur', 'tekanandarah', 'gravitas', 'albumin', 'sugar',
       'seldarahmerah', 'pussel', 'gds', 'ureum', 'kreatinin', 'natrium',
       'kalium', 'hemoglobin', 'MCV', 'seldarahputih', 'seldarahmerah.1',
       'hipertensi', 'diabetes', 'cad', 'nafsumakan', 'edema', 'anemia',
       'klasifikasi'],
      dtype='object')

In [112]:
backup[["hipertensi", "diabetes"]] = backup[["hipertensi", "diabetes"]].replace("yes", "iya")
backup

C:\Users\agung\AppData\Local\Temp\ipykernel_239536\3053007554.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  backup[["hipertensi", "diabetes"]] = backup[["hipertensi", "diabetes"]].replace("yes", "iya")

,id,umur,tekanandarah,gravitas,albumin,sugar,seldarahmerah,pussel,gds,ureum,...,MCV,seldarahputih,seldarahmerah.1,hipertensi,diabetes,cad,nafsumakan,edema,anemia,klasifikasi
3,3,48.0,70.0,1.005,4.0,0.0,Tidak Normal,Normal,117.0,56.0,...,32,6700,3.9,iya,Tidak,Tidak,buruk,yes,yes,ckd
9,9,53.0,90.0,1.020,2.0,0.0,Normal,Normal,70.0,107.0,...,29,12100,3.7,iya,iya,Tidak,buruk,Tidak,yes,ckd
11,11,63.0,70.0,1.010,3.0,0.0,Normal,Normal,380.0,60.0,...,32,4500,3.8,iya,iya,Tidak,buruk,yes,Tidak,ckd
14,14,68.0,80.0,1.010,3.0,2.0,Tidak Normal,Normal,157.0,90.0,...,16,11000,2.6,iya,iya,yes,buruk,yes,Tidak,ckd
20,20,61.0,80.0,1.015,2.0,0.0,Normal,Normal,173.0,148.0,...,24,9200,3.2,iya,iya,yes,buruk,yes,yes,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,140.0,49.0,...,47,6700,4.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
396,396,42.0,70.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,75.0,31.0,...,54,7800,6.2,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
397,397,12.0,80.0,1.020,0.0,0.0,Tidak Normal,Tidak Normal,100.0,26.0,...,49,6600,5.4,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
398,398,17.0,60.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,114.0,50.0,...,51,7200,5.9,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd
399,399,58.0,80.0,1.025,0.0,0.0,Tidak Normal,Tidak Normal,131.0,18.0,...,53,6800,6.1,Tidak,Tidak,Tidak,baik,Tidak,Tidak,Tidaktckd