DATA SERIES

LIST

In [3]:
import pandas as pd

data = ["satu", "dua", "tiga", "empat"]
series = pd.Series(data)
series

0     satu
1      dua
2     tiga
3    empat
dtype: object

DICTIONARY

In [4]:
data_dict = {
    "nama" : "wahyu", 
    "alamat" : "denpasar"
}
series = pd.Series(data_dict)
series

nama         wahyu
alamat    denpasar
dtype: object

In [5]:
series = pd.Series([1,2,3,4], index = ["satu", "dua", "tiga", "empat"])
series

satu     1
dua      2
tiga     3
empat    4
dtype: int64

INDEXING

In [11]:
data = ["satu", "dua", "tiga", "empat"]
series = pd.Series(data)

print(series[1])
print(series[0])
print(series)

dua
satu
0     satu
1      dua
2     tiga
3    empat
dtype: object

In [13]:
print(series[1:3]) # [awal, batas]
print(series[1:])

1     dua
2    tiga
dtype: object
1      dua
2     tiga
3    empat
dtype: object

SLICING (LOC & ILOC)

In [17]:
# LOC (mengakses value dengan indeks ditentukan)
# ILOC (mengakses value dengan indeks yang sebenarnya)

data = ["senin", "selasa", "rabu", "kamis"]
series = pd.Series(data, index = ["satu", "dua", "tiga", "empat"])
print(series.loc["satu" : "tiga"])
print(series.iloc[0:3])

satu     senin
dua     selasa
tiga      rabu
dtype: object
satu     senin
dua     selasa
tiga      rabu
dtype: object

CONDITIONAL STATEMENT

In [38]:
data = [1500, 1250, 2224, 1302, 4000]
series = pd.Series(data)
print(series)
print(series > 1500)
print(series[series > 1500])
print(series[(series > 1500) & (series < 4000)])

0    1500
1    1250
2    2224
3    1302
4    4000
dtype: int64
0    False
1    False
2     True
3    False
4     True
dtype: bool
2    2224
4    4000
dtype: int64
2    2224
dtype: int64

In [24]:
kondisi = series[(series > 1500) & (series < 4000)]
print(kondisi)

2    2224
dtype: int64

KONVERSI

In [33]:
print(series)
series = series.astype(str)
print(series)

0    1500
1    1250
2    2224
3    1302
4    4000
dtype: int64
0    1500
1    1250
2    2224
3    1302
4    4000
dtype: object

CHANGING DATA SERIES

In [39]:
print(series)

0    1500
1    1250
2    2224
3    1302
4    4000
dtype: int64

In [40]:
series[2] = 10000
print(series)

0     1500
1     1250
2    10000
3     1302
4     4000
dtype: int64

DATAFRAME

LIST

In [47]:
data = [
    [10,20],
    [40,50],
    [60,70]
]

df = pd.DataFrame(data, columns=["angka1", "angka2"], index = ["satu", "dua", "tiga"])
df

      angka1  angka2
satu      10      20
dua       40      50
tiga      60      70

DICTIONARY

In [48]:
data = {
    "populasi" : [10,20,30],
    "negara" : ["amerika", "indonesia", "german"]
}

df = pd.DataFrame(data)
df

   populasi     negara
0        10    amerika
1        20  indonesia
2        30     german

AKSES DATAFRAME

In [51]:
# kurung siku 1 = output series
# kurung siku 2 = output dataframe

print(df["populasi"])
print(df[["populasi", "negara"]])

0    10
1    20
2    30
Name: populasi, dtype: int64
   populasi     negara
0        10    amerika
1        20  indonesia
2        30     german

INDEXING DATAFRAME

In [53]:
df.index = ["satu", "dua", "tiga"]
df

      populasi     negara
satu        10    amerika
dua         20  indonesia
tiga        30     german

In [62]:
print(df.loc["satu":"dua", "populasi":"negara"]) # [baris, kolom]
print(df.iloc[0:2, 0:2]) # [baris, kolom]

      populasi     negara
satu        10    amerika
dua         20  indonesia
      populasi     negara
satu        10    amerika
dua         20  indonesia

In [64]:
print(df.columns)
print(df.index)

Index(['populasi', 'negara'], dtype='object')
Index(['satu', 'dua', 'tiga'], dtype='object')

ASSIGNMENT 1

In [41]:
import pandas as pd

# No 1

data = [408, 943, 902, 117, 389, 435, 793, 356, 651, 993, 786, 157]

series = pd.Series(data)

series.index = ["januari", "februari", "maret", "april", "mei", "juni", "juli", "agustus", "september", "oktober", "november", "desember"]

print(f"rata - rata = {series.mean()}")
print(f"jumlah = {series.sum()}")

rata - rata = 577.5
jumlah = 6930

In [36]:
df = pd.DataFrame(data)
df.index = ["januari", "februari", "maret", "april", "mei", "juni", "juli", "agustus", "september", "oktober", "november", "desember"]
df.columns = ["angka"]
df

           angka
januari      408
februari     943
maret        902
april        117
mei          389
juni         435
juli         793
agustus      356
september    651
oktober      993
november     786
desember     157

In [38]:
mean = df["angka"].mean()
df[df["angka"] > mean]

           angka
februari     943
maret        902
juli         793
september    651
oktober      993
november     786

In [39]:
df[df["angka"] > mean] = mean

/var/folders/q2/2h4p204s56d3vhv_jx5hmc6m0000gn/T/ipykernel_2322/1429299572.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '577.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[df["angka"] > mean] = mean

In [40]:
df

           angka
januari    408.0
februari   577.5
maret      577.5
april      117.0
mei        389.0
juni       435.0
juli       577.5
agustus    356.0
september  577.5
oktober    577.5
november   577.5
desember   157.0

In [14]:
# No 2

series.mean()

np.float64(577.5)

In [15]:
# No 3

series[series > series.mean()] = series.mean()

print(series)

januari      408.0
februari     577.5
maret        577.5
april        117.0
mei          389.0
juni         435.0
juli         577.5
agustus      356.0
september    577.5
oktober      577.5
november     577.5
desember     157.0
dtype: float64

/var/folders/q2/2h4p204s56d3vhv_jx5hmc6m0000gn/T/ipykernel_2322/3469486922.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '577.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  series[series > series.mean()] = series.mean()

ASSIGNMENT 2

In [6]:
data = {
    "Athlete": ["Michael Phelps","Michael Phelps","Michael Phelps","Natalie Coughlin","Aleskey Nemov"],
    "Age": [23,19,27,25,24],
    "Country": ["United States","Canada","United States","Norway","China"],
    "Year": [2008,2004,2012,2008,2000],
    "Gold Medals": [8,6,4,1,2]
}

df = pd.DataFrame(data)
df

            Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleskey Nemov   24          China  2000            2

In [12]:
df.iloc[0:3, 0:]

          Athlete  Age        Country  Year  Gold Medals
0  Michael Phelps   23  United States  2008            8
1  Michael Phelps   19         Canada  2004            6
2  Michael Phelps   27  United States  2012            4