DATAFRAME CONDITIONAL

In [21]:
import pandas as pd

data = {
    "Athlete": ["Michael Phelps","Michael Phelps","Michael Phelps","Natalie Coughlin","Aleskey Nemov"],
    "Age": [23,19,27,25,24],
    "Country": ["United States","Canada","United States","Norway","China"],
    "Year": [2008,2004,2012,2008,2000],
    "Gold Medals": [8,6,4,1,2]
}

df = pd.DataFrame(data)
df

            Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleskey Nemov   24          China  2000            2

In [22]:
df[(df["Age"] <= 25) & (df["Country"] == "Canada")]

          Athlete  Age Country  Year  Gold Medals
1  Michael Phelps   19  Canada  2004            6

In [23]:
df.drop(columns = ["Gold Medals"], inplace=True)

In [24]:
df

            Athlete  Age        Country  Year
0    Michael Phelps   23  United States  2008
1    Michael Phelps   19         Canada  2004
2    Michael Phelps   27  United States  2012
3  Natalie Coughlin   25         Norway  2008
4     Aleskey Nemov   24          China  2000

In [25]:
df["Hari"] = ["senin", "selasa", "rabu", "kamis", "jumat"]
df

            Athlete  Age        Country  Year    Hari
0    Michael Phelps   23  United States  2008   senin
1    Michael Phelps   19         Canada  2004  selasa
2    Michael Phelps   27  United States  2012    rabu
3  Natalie Coughlin   25         Norway  2008   kamis
4     Aleskey Nemov   24          China  2000   jumat

In [26]:
df.rename(
    columns={
        "Country" : "Negara",
        "Athlete" : "Atlit"
    }, inplace=True
)

df

              Atlit  Age         Negara  Year    Hari
0    Michael Phelps   23  United States  2008   senin
1    Michael Phelps   19         Canada  2004  selasa
2    Michael Phelps   27  United States  2012    rabu
3  Natalie Coughlin   25         Norway  2008   kamis
4     Aleskey Nemov   24          China  2000   jumat

In [28]:
df["Negara"].replace({"United States" : "America", "China" : "Indo"}, inplace=True)
df

              Atlit  Age   Negara  Year    Hari
0    Michael Phelps   23  America  2008   senin
1    Michael Phelps   19   Canada  2004  selasa
2    Michael Phelps   27  America  2012    rabu
3  Natalie Coughlin   25   Norway  2008   kamis
4     Aleskey Nemov   24     Indo  2000   jumat

DATA CLEANING

In [35]:
import pandas as pd

data = {
    "Athlete": ["Michael Phelps","Michael Phelps","Michael Phelps","Natalie Coughlin","Aleskey Nemov"],
    "Age": [23,19,27,25,24],
    "Country": ["United States","Canada","United States","Norway","China"],
    "Year": [2008,2004,2012,2008,2000],
    "Gold Medals": [8,6,4,1,2]
}

df = pd.DataFrame(data)
df

            Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleskey Nemov   24          China  2000            2

In [36]:
df.isnull().sum()

Athlete        0
Age            0
Country        0
Year           0
Gold Medals    0
dtype: int64

In [40]:
df.fillna(0)

            Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleskey Nemov   24          China  2000            2

In [41]:
df.dropna()

            Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleskey Nemov   24          China  2000            2

In [43]:
df["Year"].unique()

array([2008, 2004, 2012, 2000])

In [44]:
df.drop_duplicates()

            Athlete  Age        Country  Year  Gold Medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19         Canada  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25         Norway  2008            1
4     Aleskey Nemov   24          China  2000            2

READ DATA EXTERNAL

In [46]:
df = pd.read_csv("data/death_clean.csv")
df

,Cause,Type,Year,Data Redundancy,Total Deaths,Source,Page at Source,Source URL
0,Abrasi Air Laut,Bencana Alam,2012,1,0,Profil Kesehatan Indonesia Tahun 2012,Lampiran 3.38,https://pusdatin.kemkes.go.id/download.php?fil...
1,AIDS,Bencana Non Alam dan Penyakit,2000,1,47,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
2,AIDS,Bencana Non Alam dan Penyakit,2001,1,99,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
3,AIDS,Bencana Non Alam dan Penyakit,2002,1,100,Profil Kesehatan Indonesia Tahun 2004,78,https://pusdatin.kemkes.go.id/download.php?fil...
4,AIDS,Bencana Non Alam dan Penyakit,2003,1,261,Profil Kesehatan Indonesia Tahun 2010,115,https://pusdatin.kemkes.go.id/download.php?fil...
...,...,...,...,...,...,...,...,...
545,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2016,1,0,Profil Kesehatan Indonesia Tahun 2016,Lampiran 6.37,https://pusdatin.kemkes.go.id/download.php?fil...
546,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2017,1,0,Profil Kesehatan Indonesia Tahun 2017,Lampiran 6.43,https://pusdatin.kemkes.go.id/download.php?fil...
547,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2019,1,0,Profil Kesehatan Indonesia Tahun 2019,Lampiran 63.c,https://pusdatin.kemkes.go.id/download.php?fil...
548,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2020,1,0,Profil Kesehatan Indonesia Tahun 2020,191,https://pusdatin.kemkes.go.id/download.php?fil...
549,Wabah Penyakit (Epidemi),Bencana Non Alam dan Penyakit,2021,1,0,Profil Kesehatan Indonesia Tahun 2021,253,https://www.kemkes.go.id/downloads/resources/d...

In [ ]:
# data cleaning = whittaker henderson
# prediksi = arima