In [6]:
import pandas as pd 
import numpy as np

DATA SERIES

In [4]:
data = np.array([1,2,3,4])
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
dtype: int32

DATA DATAFRAME

In [7]:
data = np.array([1,2,3,4])
df = pd.DataFrame(data)
df

   0
0  1
1  2
2  3
3  4

ASSIGNMENT

In [9]:
data = np.array(["APPLE", "ORANGE", "BANANA", "GRAPE", "MANGO"])
series = pd.Series(data)
df = pd.DataFrame(data)

series

0     APPLE
1    ORANGE
2    BANANA
3     GRAPE
4     MANGO
dtype: object

In [12]:
df

        0
0   APPLE
1  ORANGE
2  BANANA
3   GRAPE
4   MANGO

CREATING, INDEXING & SELECTING SERIES

In [15]:
data = np.array(["scratch", "roblox", "unity"])
series1 = pd.Series(data, index = ["satu", "dua", "tiga"])
series2 = pd.Series(data, index = [101, 102, 103])
print(series1)
print(series2)

satu    scratch
dua      roblox
tiga      unity
dtype: object
101    scratch
102     roblox
103      unity
dtype: object

In [16]:
data = ["scratch", "roblox", "unity"]
series = pd.Series(data)
series

0    scratch
1     roblox
2      unity
dtype: object

In [17]:
data = {
    "satu" : "koding",
    "dua" : "akademi"
}

series = pd.Series(data)
series

satu     koding
dua     akademi
dtype: object

In [18]:
series = pd.Series(99, index = [1,2,3,4])
series

1    99
2    99
3    99
4    99
dtype: int64

In [21]:
data = ["scratch", "roblox", "unity"]
series = pd.Series(data)

print(series[0])
print(series[1])
print(series[1:])

scratch
roblox
1    roblox
2     unity
dtype: object

In [25]:
data = ["scratch", "roblox", "unity"]
series = pd.Series(data, index = ["satu", "dua", "tiga"])

print(series["satu"])
print(series["dua":])
print(series)

scratch
dua     roblox
tiga     unity
dtype: object
satu    scratch
dua      roblox
tiga      unity
dtype: object

LOC

In [29]:
data = ["scratch", "roblox", "unity"]
series = pd.Series(data, index = ["satu", "dua", "tiga"])

print(series.loc["satu"])
print(series.loc["satu":"tiga"])

scratch
satu    scratch
dua      roblox
tiga      unity
dtype: object

ILOC

In [30]:
data = ["scratch", "roblox", "unity"]
series = pd.Series(data, index = ["satu", "dua", "tiga"])

print(series.iloc[0])
print(series.iloc[0:3])

scratch
satu    scratch
dua      roblox
tiga      unity
dtype: object

LOC :

- Menggunakan index yang dibuat
- slicing awal dan batas menggunakan index sebenernya

ILOC :

- Menggunakan index default (dimulai dari 0)
- slicing awal dan batas menggunakan default slicing

In [33]:
for i in series:
    print(i)

scratch
roblox
unity

ASSIGNMENT

In [34]:
# NO 1

data = ["Januari", "Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"]
series = pd.Series(data, index = [1,2,3,4,5,6,7,8,9,10,11,12])
series

1       Januari
2      Februari
3         Maret
4         April
5           Mei
6          Juni
7          Juli
8       Agustus
9     September
10      Oktober
11     November
12     Desember
dtype: object

In [36]:
# NO 2

print(series.loc[1:])

1       Januari
2      Februari
3         Maret
4         April
5           Mei
6          Juni
7          Juli
8       Agustus
9     September
10      Oktober
11     November
12     Desember
dtype: object

In [38]:
print(series.iloc[0:])

1       Januari
2      Februari
3         Maret
4         April
5           Mei
6          Juni
7          Juli
8       Agustus
9     September
10      Oktober
11     November
12     Desember
dtype: object

In [39]:
for i in series:
    print(i)

Januari
Februari
Maret
April
Mei
Juni
Juli
Agustus
September
Oktober
November
Desember

CONDITIONAL & OPERATION SERIES

In [41]:
data = np.array([1000,1500,2000,3000])
series = pd.Series(data, index = ["a", "b", "c", "d"])
series

a    1000
b    1500
c    2000
d    3000
dtype: int32

In [42]:
series > 1500

a    False
b    False
c     True
d     True
dtype: bool

In [44]:
series[series > 1500]

c    2000
d    3000
dtype: int32

In [47]:
rata = series.mean()
print(rata)

series[series > series.mean()]

1875.0

c    2000
d    3000
dtype: int32

In [48]:
series[(series > 1000) & (series < 3000)]

b    1500
c    2000
dtype: int32

In [50]:
series + 5000

a    6000
b    6500
c    7000
d    8000
dtype: int32

In [54]:
data1 = np.array([1000,1500,2000,3000])
series1 = pd.Series(data1, index = ["a", "b", "c", "d"])

data2 = np.array([200,200,200,200])
series2 = pd.Series(data2, index = ["a", "b", "c", "d"])

print(series1 + series2)
print(series1.add(series2))

a    1200
b    1700
c    2200
d    3200
dtype: int32
a    1200
b    1700
c    2200
d    3200
dtype: int32

In [59]:
data1 = np.array([1000,1500,2000,3000])
series1 = pd.Series(data1, index = ["a", "b", "c", "d"])

data1_type = series1.dtypes
data1_newtype = series1.astype(str)
print(data1_type)
print(data1_newtype.dtypes)

int32
object

object = string

In [61]:
data1 = np.array([1000,1500,2000,3000])
series1 = pd.Series(data1, index = ["a", "b", "c", "d"])

print(series1.loc["a"])
series1.loc["a"] = 5000
print(series1.loc["a"])

1000
5000

In [70]:
data1 = np.array([1000,1500,2000,3000])
series1 = pd.Series(data1, index = ["a", "b", "c", "d"])

series2 = series[series > 1500]

In [69]:
series2

c    2000
d    3000
dtype: int32

In [74]:
series1 = series1 + 1000

In [75]:
series1

a    2000
b    2500
c    3000
d    4000
dtype: int32

ASSIGNMENT

In [92]:
# NO 1

data = [408,943,902,117,389,435,793,356,651,993,786,157]
series = pd.Series(data, index = ["Januari", "Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"])
series

Januari      408
Februari     943
Maret        902
April        117
Mei          389
Juni         435
Juli         793
Agustus      356
September    651
Oktober      993
November     786
Desember     157
dtype: int64

In [77]:
# NO 2

rata = series.mean()
rata

577.5

In [94]:
# NO 3

# series["Januari"] = 1000

series[series > rata] = rata

In [95]:
# NO 4

series

Januari      408.0
Februari     577.5
Maret        577.5
April        117.0
Mei          389.0
Juni         435.0
Juli         577.5
Agustus      356.0
September    577.5
Oktober      577.5
November     577.5
Desember     157.0
dtype: float64

CREATING, INDEXING, SELECTING DATAFRAME

In [97]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [99]:
data = [20,30,40,50]
df = pd.DataFrame(data)
df

    0
0  20
1  30
2  40
3  50

In [104]:
data = [
    [10,20,30],
    [40,50,60]
]

df = pd.DataFrame(data, columns=["satu", "dua", "tiga"])
df

   satu  dua  tiga
0    10   20    30
1    40   50    60

In [113]:
data = {
    "population" : [10,20,30,40],
    "gdp" : [11,12,13,14],
    "surface area" : [22,23,24,25]
}

df = pd.DataFrame(data, index = ["canada", "france", "germany", "italy"])

# df.index = ["canada", "france", "germany", "italy"]
# df.columns = ["satu", "dua", "tiga"]

df

         population  gdp  surface area
canada           10   11            22
france           20   12            23
germany          30   13            24
italy            40   14            25

In [114]:
df.columns

Index(['population', 'gdp', 'surface area'], dtype='object')

In [115]:
df[["population", "gdp"]]

         population  gdp
canada           10   11
france           20   12
germany          30   13
italy            40   14

In [120]:
# baris

print(df.loc["canada"])

# baris slicing

print(df.loc["canada" : "germany"])

# baris & kolom slicing 

print(df.loc["canada" : "germany", "population" : "gdp"])

population      10
gdp             11
surface area    22
Name: canada, dtype: int64
         population  gdp  surface area
canada           10   11            22
france           20   12            23
germany          30   13            24
         population  gdp
canada           10   11
france           20   12
germany          30   13

In [122]:
# baris

print(df.iloc[0])

# baris slicing

print(df.iloc[0:3])

# baris & kolom slicing 

print(df.iloc[0:3, 0:2])

population      10
gdp             11
surface area    22
Name: canada, dtype: int64
         population  gdp  surface area
canada           10   11            22
france           20   12            23
germany          30   13            24
         population  gdp
canada           10   11
france           20   12
germany          30   13

ASSIGNMENT

In [124]:
# NO 1

data = {
    "athlete": ["Michael Phelps", "Michael Phelps", "Michael Phelps", "Natalie Coughlin", "Aleskey Nemov"],
    "age": [23, 19, 27, 25, 24],
    "country": ["United States", "United States", "United States", "United States", "Russia"],
    "year": [2008, 2004, 2012, 2008, 2000],
    "gold medals": [8,6,4,1,2]
}

df = pd.DataFrame(data)
df

            athlete  age        country  year  gold medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19  United States  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25  United States  2008            1
4     Aleskey Nemov   24         Russia  2000            2

In [125]:
# NO 2

df.columns

Index(['athlete', 'age', 'country', 'year', 'gold medals'], dtype='object')

In [126]:
# NO 3

df[["athlete", "country", "year"]]

            athlete        country  year
0    Michael Phelps  United States  2008
1    Michael Phelps  United States  2004
2    Michael Phelps  United States  2012
3  Natalie Coughlin  United States  2008
4     Aleskey Nemov         Russia  2000

In [128]:
df.iloc[0:3]

          athlete  age        country  year  gold medals
0  Michael Phelps   23  United States  2008            8
1  Michael Phelps   19  United States  2004            6
2  Michael Phelps   27  United States  2012            4

In [133]:
df.loc[0:3]

            athlete  age        country  year  gold medals
0    Michael Phelps   23  United States  2008            8
1    Michael Phelps   19  United States  2004            6
2    Michael Phelps   27  United States  2012            4
3  Natalie Coughlin   25  United States  2008            1