MINI PROJECT PANDAS

In [19]:
import pandas as pd 
import numpy as np 
from scipy import stats as st 

data = pd.read_csv("data/tourist.csv")
data

,year,area,country,January,February,March,April,May,June,July,August,September,October,November,December
0,2019,ASIA PACIFIC,AUSTRALIAN,95536,67474,83002,90265.0,98625,110815,123293,118556,124416,119382,105312,110711
1,2019,ASIA PACIFIC,BHUTAN,60,30,47,38.0,31,31,46,67,43,32,56,60
2,2019,ASIA PACIFIC,BANGLADESH,2262,2094,2489,2264.0,1938,4265,2656,2307,2035,2371,2164,2671
3,2019,ASIA PACIFIC,FIJI,91,73,72,77.0,42,62,2656,80,68,78,89,189
4,2019,ASIA PACIFIC,HONGKONG,1313,1367,764,6.0,1,5,2,1,0,11,0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2018,MIDDLE EAST,TURKEY,899,615,750,960.0,712,909,1306,1630,979,707,514,521
358,2018,MIDDLE EAST,UNITED ARAB EMIRATES,170,132,266,264.0,111,293,375,306,164,151,147,201
359,2018,MIDDLE EAST,YAMAN,98,49,76,55.0,23,62,40,52,67,37,60,85
360,2018,MIDDLE EAST,JORDAN,225,153,236,352.0,150,260,389,448,283,255,218,254
361,2018,OTHER NATIONALITIES,OTHER NATIONALITIES,6952,1704,1771,2484.0,2167,3711,2054,1269,1762,2604,3298,673

In [20]:
# NO 1

data.dtypes

year           int64
area          object
country       object
January        int64
February       int64
March          int64
April        float64
May            int64
June           int64
July           int64
August         int64
September      int64
October        int64
November       int64
December       int64
dtype: object

In [21]:
data2018 = data.loc[data["year"] == 2018]
total_2018 = data2018.iloc[0:, 3:].sum().sum()
total_2018

6073353.0

In [22]:
data2019 = data.loc[data["year"] == 2019]
total_2019 = data2019.iloc[0:, 3:].sum().sum()
total_2019

6275045.0

In [126]:
# NO 2

rata2018 = data2018.iloc[0:, 3:].sum().mean()
rata2018

506112.75

In [121]:
rata2019 = data2019.iloc[0:, 3:].sum().mean()
rata2019

522920.4166666667

In [35]:
# NO 3

bulan_2018 = data2018.iloc[0:, 3:].sum()
bulan_2019 = data2019.iloc[0:, 3:].sum()

print("max 2018 : ")
print(bulan_2018.idxmax())
print(bulan_2018.max())
print("max 2019 : ")
print(bulan_2019.idxmax())
print(bulan_2019.max())

max 2018 :
July
624366.0
max 2019 :
August
616706.0

In [37]:
# NO 4

bulan_2018 = data2018.iloc[0:, 3:].sum()
bulan_2019 = data2019.iloc[0:, 3:].sum()

print("min 2018 : ")
print(bulan_2018.idxmin())
print(bulan_2018.min())
print("min 2019 : ")
print(bulan_2019.idxmin())
print(bulan_2019.min())

min 2018 :
January
358065.0
min 2019 :
February
437537.0

In [131]:
# NO 5

bulan = data.iloc[:, 3:].columns

area2018 = data2018.groupby("area")[bulan].sum()
area2019 = data2019.groupby("area")[bulan].sum()

total2018 = area2018.sum(axis = 1)
total2019 = area2019.sum(axis = 1)

terbesar2018 = total2018.idxmax()
terbesar2019 = total2019.idxmax()

print(terbesar2018)
print(terbesar2019)

ASIA PACIFIC
ASIA PACIFIC

In [127]:
# NO 6

test = data.groupby("year")[bulan].sum()
test["Max"] = [bulan_2018.idxmax(),bulan_2019.idxmax()]
test["Min"] = [bulan_2018.idxmin(),bulan_2019.idxmin()]
test["Total Setahun"] = [total_2018, total_2019]
test["Rata setahun"] = [rata2018, rata2019]
test

,January,February,March,April,May,June,July,August,September,October,November,December,Max,Min,Total Setahun,Rata setahun
year,,,,,,,,,,,,,,,,
2018,358065,452423,492678,516777.0,528512,544550,624366,573766,555903,517889,407213,501211,July,January,6073353.0,506112.750000
2019,456218,437537,449637,476327.0,485634,549751,594279,616706,590565,568064,497925,552402,August,February,6275045.0,522920.416667

DATA CLEANING - DATAFRAME

In [135]:
dict = {
    "I" : [100, 90, np.nan, 95],
    "II" : [30, 45, 56, np.nan],
    "III" : [np.nan, 40, 80, 98]
}

df = pd.DataFrame(dict)

df

       I    II   III
0  100.0  30.0   NaN
1   90.0  45.0  40.0
2    NaN  56.0  80.0
3   95.0   NaN  98.0

ISNULL

In [137]:
print(df.isnull())
print(df.isnull().sum())

       I     II    III
0  False  False   True
1  False  False  False
2   True  False  False
3  False   True  False
I      1
II     1
III    1
dtype: int64

NOTNULL

In [139]:
print(df.notnull())
print(df.notnull().sum())

       I     II    III
0   True   True  False
1   True   True   True
2  False   True   True
3   True  False   True
I      3
II     3
III    3
dtype: int64

FILLNA

In [140]:
df.fillna(1)

       I    II   III
0  100.0  30.0   1.0
1   90.0  45.0  40.0
2    1.0  56.0  80.0
3   95.0   1.0  98.0

In [141]:
df.fillna(df.mean())

       I         II        III
0  100.0  30.000000  72.666667
1   90.0  45.000000  40.000000
2   95.0  56.000000  80.000000
3   95.0  43.666667  98.000000

REPLACE

In [143]:
df.replace(np.NaN, 10)

       I    II   III
0  100.0  30.0  10.0
1   90.0  45.0  40.0
2   10.0  56.0  80.0
3   95.0  10.0  98.0

In [144]:
df.replace(100, 5)

      I    II   III
0   5.0  30.0   NaN
1  90.0  45.0  40.0
2   NaN  56.0  80.0
3  95.0   NaN  98.0

DROPNA

In [146]:
df.dropna(axis = 0)

      I    II   III
1  90.0  45.0  40.0

In [147]:
df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

VALUE COUNT

In [155]:
df["II"].unique()

array([30., 45., 56., nan])

In [154]:
df["II"].value_counts()

II
30.0    1
45.0    1
56.0    1
Name: count, dtype: int64

In [156]:
df["II"].replace(30, 90)

0    90.0
1    45.0
2    56.0
3     NaN
Name: II, dtype: float64

In [167]:
data = pd.read_csv("data/employee.csv")
data

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
1        S Kumar   NaN  16000.0      F     Finance    G0                520
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
5  Satyam Sharma   NaN  62000.0    NaN       Sales    G3                649
6   James Authur  54.0      NaN      F  Operations    G3                 53
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [158]:
data.filter(['name', 'department'])

            name  department
0    Allen Smith  Operations
1        S Kumar     Finance
2    Jack Morgan     Finance
3      Ying Chin       Sales
4  Dheeraj Patel  Operations
5  Satyam Sharma       Sales
6   James Authur  Operations
7     Josh Wills     Finance
8       Leo Duck       Sales

In [159]:
data.filter([0,1,2], axis = 0)

          name   age   income gender  department grade  performance_score
0  Allen Smith  45.0      NaN    NaN  Operations    G3                723
1      S Kumar   NaN  16000.0      F     Finance    G0                520
2  Jack Morgan  32.0  35000.0      M     Finance    G2                674

In [161]:
data[data.department == 'Sales']

            name   age   income gender department grade  performance_score
3      Ying Chin  45.0  65000.0      F      Sales    G3                556
5  Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649
8       Leo Duck  23.0  98000.0      M      Sales    G4                709

In [162]:
data[data.department.isin(['Sales', 'Finance'])]

            name   age   income gender department grade  performance_score
1        S Kumar   NaN  16000.0      F    Finance    G0                520
2    Jack Morgan  32.0  35000.0      M    Finance    G2                674
3      Ying Chin  45.0  65000.0      F      Sales    G3                556
5  Satyam Sharma   NaN  62000.0    NaN      Sales    G3                649
7     Josh Wills  54.0  52000.0      F    Finance    G3                901
8       Leo Duck  23.0  98000.0      M      Sales    G4                709

In [163]:
data[data.performance_score >= 700]

            name   age   income gender  department grade  performance_score
0    Allen Smith  45.0      NaN    NaN  Operations    G3                723
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [166]:
data = data.dropna()
data

            name   age   income gender  department grade  performance_score
2    Jack Morgan  32.0  35000.0      M     Finance    G2                674
3      Ying Chin  45.0  65000.0      F       Sales    G3                556
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2                711
7     Josh Wills  54.0  52000.0      F     Finance    G3                901
8       Leo Duck  23.0  98000.0      M       Sales    G4                709

In [168]:
data["age"] = data.age.fillna(data.age.mean())
data

,name,age,income,gender,department,grade,performance_score
0,Allen Smith,45.000000,NaN,NaN,Operations,G3,723
1,S Kumar,40.428571,16000.0,F,Finance,G0,520
2,Jack Morgan,32.000000,35000.0,M,Finance,G2,674
3,Ying Chin,45.000000,65000.0,F,Sales,G3,556
4,Dheeraj Patel,30.000000,42000.0,F,Operations,G2,711
5,Satyam Sharma,40.428571,62000.0,NaN,Sales,G3,649
6,James Authur,54.000000,NaN,F,Operations,G3,53
7,Josh Wills,54.000000,52000.0,F,Finance,G3,901
8,Leo Duck,23.000000,98000.0,M,Sales,G4,709

In [172]:
upper = data["performance_score"].mean() + 3 * data["performance_score"].std()
lower = data["performance_score"].mean() - 3 * data["performance_score"].std()
data = data[(data["performance_score"] < upper) & (data["performance_score"] > lower)]
data

,name,age,income,gender,department,grade,performance_score
0,Allen Smith,45.000000,NaN,NaN,Operations,G3,723
1,S Kumar,40.428571,16000.0,F,Finance,G0,520
2,Jack Morgan,32.000000,35000.0,M,Finance,G2,674
3,Ying Chin,45.000000,65000.0,F,Sales,G3,556
4,Dheeraj Patel,30.000000,42000.0,F,Operations,G2,711
5,Satyam Sharma,40.428571,62000.0,NaN,Sales,G3,649
6,James Authur,54.000000,NaN,F,Operations,G3,53
7,Josh Wills,54.000000,52000.0,F,Finance,G3,901
8,Leo Duck,23.000000,98000.0,M,Sales,G4,709

In [173]:
upper = data["performance_score"].quantile(.99)
lower = data["performance_score"].quantile(.01)
data = data[(data["performance_score"] < upper) & (data["performance_score"] > lower)]
data

,name,age,income,gender,department,grade,performance_score
0,Allen Smith,45.000000,NaN,NaN,Operations,G3,723
1,S Kumar,40.428571,16000.0,F,Finance,G0,520
2,Jack Morgan,32.000000,35000.0,M,Finance,G2,674
3,Ying Chin,45.000000,65000.0,F,Sales,G3,556
4,Dheeraj Patel,30.000000,42000.0,F,Operations,G2,711
5,Satyam Sharma,40.428571,62000.0,NaN,Sales,G3,649
8,Leo Duck,23.000000,98000.0,M,Sales,G4,709